// @/components/common/sidebar/app-sidebar.tsx
"use client";

import type * as React from "react";

import { NavMain } from "@/components/common/sidebar/nav-main";
import { NavUser } from "@/components/common/sidebar/nav-user";
import {
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarHeader,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarRail,
} from "@/components/ui/sidebar";
import { sessionType } from "src/types/session";

import { ApplicationSvgLogo } from "@/components/logo";
import { sidebar_links } from "@/constants/links";
import Link from "next/link";
import { appConfig } from "@root/project.config";

const getSideNavLinks = (role: string, prefixPath?: string) => {
  return sidebar_links
    .filter(
      (link) =>
        link.allowed_roles.includes(role) || link.allowed_roles.includes("*")
    )
    .map((link) => ({
      title: link.title,
      icon: link.icon,
      href: prefixPath ? `/${prefixPath}${link.path}` : `/${role}${link.path}`,
      preserveParams: link?.preserveParams,
      items: link?.items
        ?.filter(
          (link) =>
            link.allowed_roles.includes(role) ||
            link.allowed_roles.includes("*")
        )
        ?.map((item) => ({
          title: item.title,
          href: prefixPath
            ? `/${prefixPath}${link.path}${item.path}`
            : `/${role}${link.path}${item.path}`,
        })),
    }));
};

interface SidebarProps extends React.ComponentProps<typeof Sidebar> {
  user: sessionType["user"];
  moderator: string;
  prefixPath?: string; // Optional prefix path for links
}

export function AppSidebar({
  user,
  moderator,
  prefixPath,
  ...props
}: SidebarProps) {
  const links = getSideNavLinks(moderator, prefixPath);

  return (
    <Sidebar collapsible="icon" className="border-r border-border" {...props}>
      <SidebarHeader>
        <SidebarMenu>
          <SidebarMenuItem>
            <SidebarMenuButton
              className="data-[slot=sidebar-menu-button]:!p-1.5"
              size="lg"
              asChild
            >
              <Link href={`/${prefixPath ? prefixPath : moderator}`}>
                <ApplicationSvgLogo className="!size-8" />
                <div className="grid flex-1 text-left text-sm leading-tight">
                  <span className="truncate font-semibold">
                    {appConfig.name}
                  </span>
                  <span className="truncate text-xs">
                    {appConfig.appDomain}
                  </span>
                </div>
              </Link>
            </SidebarMenuButton>
          </SidebarMenuItem>
        </SidebarMenu>
      </SidebarHeader>
      <SidebarContent>
        <NavMain items={links} />
      
      </SidebarContent>

      <SidebarFooter>
        <NavUser user={user} />
      </SidebarFooter>
      <SidebarRail />
    </Sidebar>
  );
}

// src/lib/components/common/sidebar/app-sidebar.svelte
<script lang="ts">
	import { appConfig } from "@root/project.config";
	import { page } from "$app/state";
	import * as Sidebar from "$lib/components/ui/sidebar";
	import Logo from "$lib/components/logo.svelte";
	import { getSideNavLinks } from "./sidebar-links";

	type SessionUser = {
		name?: string | null;
		email?: string | null;
		image?: string | null;
		role?: string;
	};

	let {
		user,
		moderator = "user",
		prefixPath = "dashboard"
	}: {
		user: SessionUser;
		moderator?: string;
		prefixPath?: string;
	} = $props();

	const links = $derived(getSideNavLinks(moderator, prefixPath));

	function isActive(href: string) {
		if (href === `/${prefixPath}`) return page.url.pathname === href;
		return page.url.pathname === href || page.url.pathname.startsWith(href + "/");
	}
</script>

<Sidebar.Root collapsible="icon">
	<Sidebar.Header>
		<Sidebar.Menu>
			<Sidebar.MenuItem>
				<Sidebar.MenuButton size="lg">
					{#snippet child({ props })}
						<a href="/" {...props}>
							<div
								class="bg-primary text-primary-foreground flex aspect-square size-8 items-center justify-center rounded-lg"
							>
								<Logo class="size-5" />
							</div>
							<div class="grid flex-1 text-left text-sm leading-tight">
								<span class="truncate font-semibold">{appConfig.name}</span>
								<span class="text-muted-foreground truncate text-xs font-medium">
									{appConfig.appDomain}
								</span>
							</div>
						</a>
					{/snippet}
				</Sidebar.MenuButton>
			</Sidebar.MenuItem>
		</Sidebar.Menu>
	</Sidebar.Header>

	<Sidebar.Content>
		<Sidebar.Group>
			<Sidebar.GroupLabel>Workspace</Sidebar.GroupLabel>
			<Sidebar.Menu>
				{#each links as link (link.path + link.title)}
					{@const Icon = link.icon}
					<Sidebar.MenuItem>
						<Sidebar.MenuButton isActive={isActive(link.path)} tooltipContent={link.title}>
							{#snippet child({ props })}
								<a href={link.path} {...props}>
									<Icon class="size-4" />
									<span>{link.title}</span>
								</a>
							{/snippet}
						</Sidebar.MenuButton>
						{#if link.items?.length}
							<Sidebar.MenuSub>
								{#each link.items as sub (sub.path)}
									<Sidebar.MenuSubItem>
										<Sidebar.MenuSubButton>
											{#snippet child({ props })}
												<a href={sub.path} {...props}>{sub.title}</a>
											{/snippet}
										</Sidebar.MenuSubButton>
									</Sidebar.MenuSubItem>
								{/each}
							</Sidebar.MenuSub>
						{/if}
					</Sidebar.MenuItem>
				{/each}
			</Sidebar.Menu>
		</Sidebar.Group>
	</Sidebar.Content>

	<Sidebar.Footer>
		<Sidebar.Menu>
			<Sidebar.MenuItem>
				<Sidebar.MenuButton size="lg">
					{#snippet child({ props })}
						<a href="/dashboard/settings/profile" {...props}>
							{#if user.image}
								<img
									src={user.image}
									alt={user.name ?? "Profile"}
									class="size-8 rounded-lg object-cover"
								/>
							{:else}
								<div
									class="bg-muted flex size-8 items-center justify-center rounded-lg text-sm font-medium"
								>
									{user.name?.charAt(0).toUpperCase() ?? "?"}
								</div>
							{/if}
							<div class="grid flex-1 text-left text-sm leading-tight">
								<span class="truncate font-medium">{user.name ?? "Profile"}</span>
								<span class="text-muted-foreground truncate text-xs">
									{user.email ?? ""}
								</span>
							</div>
						</a>
					{/snippet}
				</Sidebar.MenuButton>
			</Sidebar.MenuItem>
		</Sidebar.Menu>
	</Sidebar.Footer>

	<Sidebar.Rail />
</Sidebar.Root>
