// app/blog/page.tsx
import Link from "next/link";
import { getHomePagePosts } from "src/lib/blog/actions";
import { decodeHTMLEntities } from "src/utils/string";
import NewLetter from "./components/newsletter";
import { PostCard } from "./components/post-card";
export const revalidate = 60;

export default async function BlogPage() {
  const { posts } = await getHomePagePosts();
  
  // Decode HTML entities in post titles
  const decodedPosts = posts.map(post => ({
    ...post,
    title: decodeHTMLEntities(post.title)
  }));

  return (
    <div className="w-full">
      {/* Hero Section */}
      <section 
        id="hero" 
        className="py-16 md:py-24 px-4 sm:px-6 text-center "
      >
        <div className="max-w-4xl mx-auto">
          <h1 className="text-4xl sm:text-5xl md:text-6xl font-bold text-foreground mb-4">
            Welcome to our Blog
          </h1>
          <p className="text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto">
            Get the latest news, insights, and updates from our team
          </p>
        </div>
      </section>

      {/* Featured Posts */}
      <section className="py-12 md:py-16 px-4 sm:px-6 max-w-7xl mx-auto">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 md:gap-8">
          {decodedPosts.slice(0, 3).map((post, index) => (
            <Link 
              href={`/blog/articles/${post.slug}`} 
              key={index}
              className={cn(
                index === 0 ? "md:col-span-2 md:row-span-2" : "",
                "group"
              )}
            >
              <PostCard 
                post={post} 
                featured={index === 0}
              />
            </Link>
          ))}
        </div>
      </section>

      {/* All Posts */}
      <section className="py-12 md:py-16 px-4 sm:px-6 max-w-7xl mx-auto">
        <h2 className="text-2xl md:text-3xl font-bold mb-8 pb-2 border-b border-border">
          Latest Articles
        </h2>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 md:gap-8">
          {decodedPosts.slice(3).map((post, index) => (
            <Link 
              href={`/blog/articles/${post.slug}`} 
              key={index}
              className="group"
            >
              <PostCard post={post} />
            </Link>
          ))}
        </div>
      </section>

      {/* Newsletter */}
      <section className="py-16 md:py-24 px-4 sm:px-6 ">
        <div className="max-w-6xl mx-auto">
          <NewLetter />
        </div>
      </section>
    </div>
  );
}

// Add this helper function if not already in your project
function cn(...classes: string[]) {
  return classes.filter(Boolean).join(' ');
}

// src/routes/blog/+page.svelte
<script lang="ts">
	import PostCard from "$lib/components/blog/post-card.svelte";
	import Newsletter from "$lib/components/blog/newsletter.svelte";
	import { cn } from "$lib/utils";
	import type { PostWithId } from "src/models/post";

	let { data } = $props<{ data: { posts: PostWithId[] } }>();

	const featured = $derived(data.posts.slice(0, 3));
	const rest = $derived(data.posts.slice(3));
</script>

<svelte:head>
	<title>Blog — Nexonauts</title>
</svelte:head>

<div class="w-full">
	<section id="hero" class="px-4 py-16 text-center sm:px-6 md:py-24">
		<div class="mx-auto max-w-4xl">
			<h1 class="text-foreground mb-4 text-4xl font-bold sm:text-5xl md:text-6xl">
				Welcome to our Blog
			</h1>
			<p class="text-muted-foreground mx-auto max-w-2xl text-lg md:text-xl">
				Get the latest news, insights, and updates from our team
			</p>
		</div>
	</section>

	{#if featured.length > 0}
		<section class="mx-auto max-w-7xl px-4 py-12 sm:px-6 md:py-16">
			<div class="grid grid-cols-1 gap-6 md:grid-cols-2 md:gap-8 lg:grid-cols-3">
				{#each featured as post, index (post.slug)}
					<a
						href={`/blog/articles/${post.slug}`}
						class={cn("group", index === 0 && "md:col-span-2 md:row-span-2")}
					>
						<PostCard {post} featured={index === 0} />
					</a>
				{/each}
			</div>
		</section>
	{/if}

	{#if rest.length > 0}
		<section class="mx-auto max-w-7xl px-4 py-12 sm:px-6 md:py-16">
			<h2 class="mb-8 border-b border-border pb-2 text-2xl font-bold md:text-3xl">
				Latest Articles
			</h2>
			<div class="grid grid-cols-1 gap-6 md:grid-cols-2 md:gap-8 lg:grid-cols-3">
				{#each rest as post (post.slug)}
					<a href={`/blog/articles/${post.slug}`} class="group">
						<PostCard {post} />
					</a>
				{/each}
			</div>
		</section>
	{/if}

	<section class="px-4 py-16 sm:px-6 md:py-24">
		<div class="mx-auto max-w-6xl">
			<Newsletter />
		</div>
	</section>
</div>
