// app/dashboard/products/page.tsx
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Separator } from "@/components/ui/separator";

import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet";
import { ButtonLink } from "@/components/utils/link";
import {
  ArrowRight,
  ArrowUpRight,
  Import,
  LoaderCircle,
  Plus,
} from "lucide-react";
import { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Suspense } from "react";
import { Icon } from "src/lib/integrations/index";
import {
  deleteProduct,
  fetchFromIntegration,
  getProducts,
  importProduct,
} from "./actions";
import DeleteProductButton from "./components/delete-btn";
import { FilterAndSort, ImportedProductCard } from "./components/products";

export const metadata: Metadata = {
  title: "My Products",
  description: "My Products page",
};
type PageProps = {
  searchParams: Promise<{
    importFrom?: string;
    filter?: string;
    sort?: string;
  }>;
};
const availableIntegrations = ["gumroad"];

export default async function MyProducts(props: PageProps) {
  const searchParams = await props.searchParams;

  const { products, integrated } = await getProducts(
    searchParams.filter ?? "all",
    searchParams.sort ?? "latest"
  );

  const importFrom = availableIntegrations.includes(
    searchParams?.importFrom ?? "none"
  )
    ? searchParams.importFrom
    : null;

  const getFromIntegrations = async () => {
    "use server";
    if (importFrom === null) return Promise.resolve([]);

    if (!availableIntegrations.includes(importFrom as string)) {
      return Promise.resolve([]);
    }
    const data = await fetchFromIntegration(importFrom as string);
    return data;
  };
  const productsFromIntegrations = await getFromIntegrations();
  // filter out third-party products that are already in the database
  const productsIds = products
    .filter((product) => product?.third_party !== null)
    .map((product) => product?.third_party?.product_id);

  return (
    <div className="space-y-6 p-4 md:p-10 pb-16 w-full @container">
      <div className="flex justify-between items-center flex-wrap gap-4">
        <h1 className="text-xl font-semibold">My Products</h1>
        <div className="flex gap-2 flex-wrap">
          <Button variant="default_light" size="sm" rounded="full" asChild>
            <Link href={`/dashboard/products/new`}>
              <Plus />
              New Product
            </Link>
          </Button>
          <FilterAndSort />
          <Sheet>
            <SheetTrigger asChild>
              <Button variant="outline" size="sm">
                <Import />
                Import Products
              </Button>
            </SheetTrigger>
            <SheetContent>
              <SheetHeader>
                <SheetTitle>Import Products</SheetTitle>
                <SheetDescription>
                  From third party platforms like Gumroad.This will help you to
                  sync your products with the platform.
                </SheetDescription>
              </SheetHeader>
              {importFrom !== null ? (
                <>
                  <h2 className="text-lg font-semibold tracking-tight capitalize mt-5 mb-2">
                    {importFrom} Products
                  </h2>
                  <Suspense
                    fallback={
                      <div className="p-4 flex justify-center flex-col items-center gap-4 h-64">
                        <LoaderCircle className="size-24 m-auto animate-spin text-primary" />
                      </div>
                    }
                  >
                    <ScrollArea className="h-168 md:h-200 border-b">
                      <div className="grid grid-cols-1 divide-y">
                        {productsFromIntegrations
                          .filter(
                            (product) =>
                              !productsIds.includes(
                                product.third_party.product_id
                              )
                          )
                          .map((product) => (
                            <ImportedProductCard
                              key={product.third_party.product_id}
                              product={product}
                              importProduct={importProduct.bind(null, product)}
                            />
                          ))}
                      </div>
                    </ScrollArea>
                  </Suspense>
                </>
              ) : (
                <div className="space-y-4">
                  {availableIntegrations.map((integration) => {
                    return (
                      <div
                        key={integration}
                        className="p-4 flex justify-center flex-col items-center gap-4 h-64 rounded-lg bg-muted mt-5"
                      >
                        <Icon icon={integration} className="size-16" />
                        {integrated ? (
                          <ButtonLink size="sm" href={`?importFrom=${integration}`} shallow>
                              Import Products
                              <ArrowRight  />
                          </ButtonLink>
                        ) : (
                          <ButtonLink  
                              href={`/settings/integrations/${integration}?next=${encodeURI("/products?importFrom=" + integration)}`}
                            >
                              Connect {integration}
                              <ArrowUpRight  />
                          </ButtonLink>
                        )}
                      </div>
                    );
                  })}
                </div>
              )}
            </SheetContent>
          </Sheet>
        </div>
      </div>
      <Separator />
      <div className="grid gap-4 grid-cols-1 @4xl:grid-cols-4 @2xl:grid-cols-3 @sm:grid-cols-2">
        <Suspense fallback={<div>Loading...</div>}>
          {products.map((product) => {
            return (
              <div
                key={product._id}
                className="flex flex-col space-y-2 bg-card p-3 rounded-xl"
              >
                <Image
                  width={256}
                  height={160}
                  src={product.preview_url!}
                  alt={product.name}
                  className="w-full h-auto aspect-video object-cover rounded-lg"
                />
                <h2 className="text-base font-semibold truncate">
                  {product.name}
                </h2>
                <div className="flex justify-end gap-2 p-2">
                  <DeleteProductButton
                    deleteProduct={deleteProduct.bind(null, product._id)}
                  />
                  <Button variant="outline" size="xs" asChild>
                    <Link
                      href={`/dashboard/products/${product.slug}/edit`}
                      className="text-primary"
                    >
                      Edit
                    </Link>
                  </Button>
                  <Button variant="link" size="xs" asChild>
                    <Link
                      href={`/marketplace/products/${product.slug}`}
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      View <ArrowUpRight />
                    </Link>
                  </Button>
                </div>
              </div>
            );
          })}
        </Suspense>
      </div>
    </div>
  );
}

// src/routes/dashboard/products/+page.svelte
<script lang="ts">
	import { enhance } from "$app/forms";
	import { Badge } from "$lib/components/ui/badge";
	import { Button, buttonVariants } from "$lib/components/ui/button";
	import * as Card from "$lib/components/ui/card";
	import { Separator } from "$lib/components/ui/separator";
	import * as Sheet from "$lib/components/ui/sheet";
	import * as Table from "$lib/components/ui/table";
	import Import from "@lucide/svelte/icons/import";
	import Pencil from "@lucide/svelte/icons/pencil";
	import Plus from "@lucide/svelte/icons/plus";
	import Trash2 from "@lucide/svelte/icons/trash-2";
	import { toast } from "svelte-sonner";

	let { data, form } = $props();

	let importSheetOpen = $state(false);

	$effect(() => {
		if (data.showImportPanel) importSheetOpen = true;
	});

	$effect(() => {
		if (!form?.message) return;
		if (form.success) toast.success(form.message);
		else toast.error(form.message);
	});
</script>

<svelte:head>
	<title>Products - Dashboard</title>
</svelte:head>

<div class="space-y-6 p-4 pb-16 md:p-10">
	<div class="flex flex-wrap items-start justify-between gap-3">
		<div>
			<h1 class="text-lg font-semibold">Products</h1>
			<p class="text-muted-foreground text-sm font-medium">Manage your marketplace listings.</p>
		</div>
		<div class="flex flex-wrap items-center gap-2">
			<Sheet.Root bind:open={importSheetOpen}>
				<Sheet.Trigger class={buttonVariants({ variant: "outline", size: "sm" })}>
					<Import class="mr-1 h-4 w-4" />
					Import from Gumroad
				</Sheet.Trigger>
				<Sheet.Content class="w-full overflow-y-auto sm:max-w-lg">
					<Sheet.Header>
						<Sheet.Title>Import from Gumroad</Sheet.Title>
						<Sheet.Description>
							Pull a product from your connected Gumroad library into Nexonauts.
						</Sheet.Description>
					</Sheet.Header>

					{#if !data.gumroad}
						<div class="space-y-3 p-6">
							<a
								href="?importFrom=gumroad"
								class={buttonVariants({ variant: "default" })}
								data-sveltekit-keepfocus
							>
								Load my Gumroad library
							</a>
							<p class="text-muted-foreground text-xs">
								You'll need a Gumroad access token connected under
								<a class="text-primary underline" href="/dashboard/settings/integrations">
									Settings → Integrations
								</a>.
							</p>
						</div>
					{:else if !data.gumroad.ok}
						<div class="space-y-3 p-6">
							<p class="text-destructive text-sm">{data.gumroad.message}</p>
							<a
								href="/dashboard/settings/integrations"
								class={buttonVariants({ variant: "outline", size: "sm" })}
							>
								Manage integrations
							</a>
						</div>
					{:else if data.gumroad.products.length === 0}
						<p class="text-muted-foreground p-6 text-sm">No importable products on Gumroad.</p>
					{:else}
						<div class="space-y-3 p-6">
							{#each data.gumroad.products as product (product.id)}
								<div class="flex items-start gap-3 rounded-lg border p-3">
									{#if product.preview_url}
										<img
											src={product.preview_url}
											alt={product.name}
											class="h-16 w-16 rounded-md border object-cover"
										/>
									{/if}
									<div class="min-w-0 flex-1">
										<p class="truncate text-sm font-medium">{product.name}</p>
										<p class="text-muted-foreground text-xs">${product.price}</p>
									</div>
									<form
										method="POST"
										action="?/importGumroad"
										use:enhance={() => async ({ update }) => {
											await update();
										}}
									>
										<input type="hidden" name="gumroadProductId" value={product.id} />
										<Button type="submit" size="sm">Import</Button>
									</form>
								</div>
							{/each}
						</div>
					{/if}
				</Sheet.Content>
			</Sheet.Root>

			<a href="/dashboard/products/new" class={buttonVariants({ size: "sm" })}>
				<Plus class="mr-1 h-4 w-4" />
				New product
			</a>
		</div>
	</div>
	<Separator />

	<Card.Root>
		<Card.Header>
			<Card.Title>Your products</Card.Title>
			<Card.Description>Marketplace listings attached to your profile.</Card.Description>
		</Card.Header>
		<Card.Content>
			{#if data.products.length === 0}
				<p class="text-muted-foreground text-sm">No products yet.</p>
			{:else}
				<Table.Root>
					<Table.Header>
						<Table.Row>
							<Table.Head>Name</Table.Head>
							<Table.Head>Categories</Table.Head>
							<Table.Head>Price</Table.Head>
							<Table.Head>Status</Table.Head>
							<Table.Head>Created</Table.Head>
							<Table.Head class="text-right">Actions</Table.Head>
						</Table.Row>
					</Table.Header>
					<Table.Body>
						{#each data.products as product (product._id)}
							<Table.Row>
								<Table.Cell>
									<div class="flex flex-col">
										<span class="font-medium">{product.name}</span>
										<span class="text-muted-foreground text-xs">{product.slug}</span>
									</div>
								</Table.Cell>
								<Table.Cell>{product.categories.join(", ") || "Uncategorized"}</Table.Cell>
								<Table.Cell>${product.price}</Table.Cell>
								<Table.Cell>
									<Badge variant={product.published ? "default" : "secondary"}>
										{product.published ? "Published" : "Draft"}
									</Badge>
								</Table.Cell>
								<Table.Cell>{new Date(product.createdAt).toLocaleDateString()}</Table.Cell>
								<Table.Cell class="text-right">
									<div class="flex items-center justify-end gap-1">
										<a
											href="/dashboard/products/{product.slug}/edit"
											class={buttonVariants({ variant: "ghost", size: "icon-sm" })}
											title="Edit product"
										>
											<Pencil class="h-4 w-4" />
										</a>
										<form
											method="POST"
											action="?/delete"
											use:enhance={() => async ({ update }) => {
												await update();
											}}
											onsubmit={(event) => {
												if (!confirm(`Delete "${product.name}"? This cannot be undone.`)) {
													event.preventDefault();
												}
											}}
										>
											<input type="hidden" name="productId" value={product._id} />
											<Button
												type="submit"
												size="icon-sm"
												variant="ghost"
												class="text-destructive hover:bg-destructive/10"
												title="Delete product"
											>
												<Trash2 class="h-4 w-4" />
											</Button>
										</form>
									</div>
								</Table.Cell>
							</Table.Row>
						{/each}
					</Table.Body>
				</Table.Root>
			{/if}
		</Card.Content>
	</Card.Root>
</div>
