// src/routes/admin/+page.svelte
<script lang="ts">
	import StatsCard from "$lib/components/application/stats-card.svelte";
	import { cn } from "$lib/utils";
	import CircleDashed from "@lucide/svelte/icons/circle-dashed";
	import TrendingDown from "@lucide/svelte/icons/trending-down";
	import TrendingUp from "@lucide/svelte/icons/trending-up";
	import Users from "@lucide/svelte/icons/users";
	import Wrench from "@lucide/svelte/icons/wrench";

	let { data } = $props();

	function trendClass(trend: string) {
		return trend === "increase"
			? "text-green-500"
			: trend === "decrease"
				? "text-red-500"
				: "text-primary/80";
	}
</script>

<svelte:head>
	<title>Admin — Nexonauts</title>
</svelte:head>

<div class="my-5 space-y-6">
	<div>
		<h2 class="mb-2 text-3xl font-semibold">Hi, {data.session.user.name}</h2>
		<p class="text-muted-foreground">Let's check out your platform today!</p>
	</div>

	<div
		class="divide-border flex w-full flex-col justify-between gap-2 divide-y @4xl:flex-row @4xl:divide-x"
	>
		<div class="grid w-full grid-cols-1 gap-4 pr-1.5 @lg:grid-cols-2 @4xl:grid-cols-12 @4xl:pr-0">
			<StatsCard class="col-span-1 @4xl:col-span-4" title="Total Users">
				{#snippet icon()}
					<Users class="mr-2 inline-block size-4" />
				{/snippet}

				<div class={cn("text-3xl font-bold text-primary", trendClass(data.usersStats.trend))}>
					{data.usersStats.count.toLocaleString()}
					{#if data.usersStats.trend === "increase"}
						<span class="text-xs">↑{data.usersStats.growth.toFixed(2)}</span>
					{:else if data.usersStats.trend === "decrease"}
						<span class="text-xs">↓{Math.abs(data.usersStats.growth).toFixed(2)}</span>
					{/if}
				</div>

				<p class="text-muted-foreground text-xs">
					<span class={cn("text-base", trendClass(data.usersStats.trend))}>
						{#if data.usersStats.trend === "increase"}
							<TrendingUp class="mr-2 inline-block size-4" />
						{:else if data.usersStats.trend === "decrease"}
							<TrendingDown class="mr-2 inline-block size-4" />
						{:else}
							<CircleDashed class="mr-2 inline-block size-4" />
						{/if}
						{data.usersStats.growth.toFixed(2)}%
					</span>
					from this month
				</p>
			</StatsCard>

			<StatsCard class="col-span-1 @4xl:col-span-4" title="Total Tools">
				{#snippet icon()}
					<Wrench class="mr-2 inline-block size-4" />
				{/snippet}

				<div class={cn("text-3xl font-bold text-primary", trendClass(data.toolsStats.trend))}>
					{data.toolsStats.count.toLocaleString()}
					{#if data.toolsStats.trend === "increase"}
						<span class="text-xs">↑{data.toolsStats.growth.toFixed(2)}</span>
					{:else if data.toolsStats.trend === "decrease"}
						<span class="text-xs">↓{Math.abs(data.toolsStats.growth).toFixed(2)}</span>
					{/if}
				</div>

				<p class="text-muted-foreground text-xs">
					<span class={cn("text-base", trendClass(data.toolsStats.trend))}>
						{#if data.toolsStats.trend === "increase"}
							<TrendingUp class="mr-2 inline-block size-4" />
						{:else if data.toolsStats.trend === "decrease"}
							<TrendingDown class="mr-2 inline-block size-4" />
						{:else}
							<CircleDashed class="mr-2 inline-block size-4" />
						{/if}
						{data.toolsStats.growth.toFixed(2)}%
					</span>
					from this month
				</p>
			</StatsCard>
		</div>
	</div>
</div>

// app/admin/page.tsx
import { NumberTicker } from "@/components/animation/number-ticker";
import { StatsCard } from "@/components/application/stats-card";
import { Icon } from "@/components/icons";
import { cn } from "@/lib/utils";
import { CircleDashed, TrendingDown, TrendingUp } from "lucide-react";
import { getSession } from "~/auth/server";

import { changeCase } from "src/utils/string";
import { tools_CountAndGrowth, users_CountAndGrowth } from "./actions";
import { Session } from "~/auth";

export default async function DashboardPage() {
  const session = (await getSession()) as Session;

  console.log(session);
  const usersStats = await users_CountAndGrowth("this_month");

  const toolsStats = await tools_CountAndGrowth("this_month");

  return (
    <div className="space-y-6 my-5">
      <div>
        <h2 className="text-3xl font-semibold mb-2">Hi, {session.user.name}</h2>
        <p className="text-muted-foreground">
          Let{`'`}s check out your Platform today!
        </p>
      </div>
      <div className="flex justify-between gap-2 w-full flex-col @4xl:flex-row divide-y @4xl:divide-x divide-border">
        <div className="w-full grid grid-cols-1 @lg:grid-cols-2 @4xl:grid-cols-12 gap-4 pr-1.5 @4xl:pr-0">
          <StatsCard
            className="col-span-1   @4xl:col-span-4"
            title="Total Users"
            Icon={<Icon name="users" className="inline-block mr-2 size-4" />}
          >
            <NumberTicker
              value={usersStats.count}
              className={cn(
                "text-3xl font-bold text-primary after:text-xs",
                usersStats.trend === "increase"
                  ? "after:text-green-500"
                  : usersStats.trend === "decrease"
                    ? "after:text-red-500"
                    : "after:text-primary/80"
              )}
              suffix={
                usersStats.trend === "increase"
                  ? "↑" + usersStats.growth
                  : usersStats.trend === "decrease"
                    ? "↓" + usersStats.growth
                    : ""
              }
            />

            <p className="text-xs text-muted-foreground">
              <span
                className={`${usersStats.trend === "increase"
                  ? "text-green-500"
                  : usersStats.trend === "decrease"
                    ? "text-red-500"
                    : "text-primary/80"
                  } text-base`}
              >
                {usersStats.trend === "increase" ? (
                  <TrendingUp className="inline-block mr-2 size-4" />
                ) : usersStats.trend === "decrease" ? (
                  <TrendingDown className="inline-block mr-2 size-4" />
                ) : (
                  <CircleDashed className="inline-block mr-2 size-4" />
                )}
                {usersStats.growth?.toFixed(2)}%
              </span>{" "}
              from {changeCase("this_month", "title")}
            </p>

          </StatsCard>
          <StatsCard
            className="col-span-1   @4xl:col-span-4"
            title="Total Tools"
            Icon={<Icon name="tools" className="inline-block mr-2 size-4" />}
            >
            <NumberTicker
              value={toolsStats.count}
              className={cn(
                "text-3xl font-bold text-primary after:text-xs",
                toolsStats.trend === "increase"
                  ? "after:text-green-500"
                  : toolsStats.trend === "decrease"
                    ? "after:text-red-500"
                    : "after:text-primary/80"
              )}
              suffix={
                toolsStats.trend === "increase"
                  ? "↑" + toolsStats.growth
                  : toolsStats.trend === "decrease"
                    ? "↓" + toolsStats.growth
                    : ""
              }
            />
            <p className="text-xs text-muted-foreground">
              <span
                className={`${toolsStats.trend === "increase"
                  ? "text-green-500"
                  : toolsStats.trend === "decrease"
                    ? "text-red-500"
                    : "text-primary/80"
                  } text-base`}
              >
                {toolsStats.trend === "increase" ? (
                  <TrendingUp className="inline-block mr-2 size-4" />
                ) : toolsStats.trend === "decrease" ? (
                  <TrendingDown className="inline-block mr-2 size-4" />
                ) : (
                  <CircleDashed className="inline-block mr-2 size-4" />
                )}
                {toolsStats.growth?.toFixed(2)}%
              </span>{" "}
              from {changeCase("this_month", "title")}
            </p>
            </StatsCard>

         
        </div>
      </div>

    </div>
  );
}
