// src/lib/components/ui/alert/alert.svelte
<script lang="ts" module>
import { tv, type VariantProps } from "tailwind-variants";

/**
 * Alert: editorial inset notice.
 * Hairline border, soft tinted background, ink text.
 */
export const alertVariants = tv({
	base: [
		"group/alert relative grid w-full gap-1 rounded-xl border px-4 py-3 text-left text-sm",
		"has-data-[slot=alert-action]:relative has-data-[slot=alert-action]:pr-20",
		"has-[>svg]:grid-cols-[auto_1fr] has-[>svg]:gap-x-3",
		"*:[svg]:row-span-2 *:[svg]:translate-y-0.5 *:[svg]:text-current",
		"*:[svg:not([class*='size-'])]:size-4"
	].join(" "),
	variants: {
		variant: {
			default: "bg-paper text-foreground border-border",
			info: "bg-info/8 text-info border-info/25",
			success: "bg-success/10 text-success border-success/25",
			warning: "bg-warning/10 text-warning border-warning/25",
			destructive:
				"bg-destructive/8 text-destructive border-destructive/25 *:data-[slot=alert-description]:text-destructive/85"
		}
	},
	defaultVariants: {
		variant: "default"
	}
});

export type AlertVariant = VariantProps<typeof alertVariants>["variant"];
</script>

<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements";
	import { cn, type WithElementRef } from "$lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		variant = "default",
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> & {
		variant?: AlertVariant;
	} = $props();
</script>

<div
	bind:this={ref}
	data-slot="alert"
	role="alert"
	class={cn(alertVariants({ variant }), className)}
	{...restProps}
>
	{@render children?.()}
</div>

// @/components/ui/alert.tsx
'use client';
import { cva, type VariantProps } from 'class-variance-authority';
import * as React from 'react';

import { cn } from '@/lib/utils';

const alertVariants = cva(
  'relative w-full rounded-lg border p-4 [&>svg~*]:pl-7 [&>svg+div]:translate-y-[-3px] [&>svg]:absolute [&>svg]:left-4 [&>svg]:top-4 [&>svg]:text-foreground',
  {
    variants: {
      variant: {
        default: 'bg-background text-foreground',
        destructive:
          'border-destructive/50 text-destructive dark:border-destructive [&>svg]:text-destructive',
        success:
          'border-green-500/50 text-green-500 dark:border-green-500 [&>svg]:text-green-500',
      },
    },
    defaultVariants: {
      variant: 'default',
    },
  }
);

const Alert = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement> & VariantProps<typeof alertVariants>
>(({ className, variant, ...props }, ref) => (
  <div
    ref={ref}
    role="alert"
    className={cn(alertVariants({ variant }), className)}
    {...props}
  />
));
Alert.displayName = 'Alert';

const AlertTitle = React.forwardRef<
  HTMLParagraphElement,
  React.HTMLAttributes<HTMLHeadingElement>
>(({ className, ...props }, ref) => (
  <h5
    ref={ref}
    className={cn('mb-1 font-medium leading-none tracking-tight', className)}
    {...props}
  />
));
AlertTitle.displayName = 'AlertTitle';

const AlertDescription = React.forwardRef<
  HTMLParagraphElement,
  React.HTMLAttributes<HTMLParagraphElement>
>(({ className, ...props }, ref) => (
  <div
    ref={ref}
    className={cn('text-sm [&_p]:leading-relaxed', className)}
    {...props}
  />
));
AlertDescription.displayName = 'AlertDescription';

export { Alert, AlertDescription, AlertTitle };
