// src/lib/components/ui/textarea/textarea.svelte
<script lang="ts">
import type { HTMLTextareaAttributes } from "svelte/elements";
import { cn, type WithElementRef, type WithoutChildren } from "$lib/utils.js";

let {
	ref = $bindable(null),
	value = $bindable(),
	class: className,
	"data-slot": dataSlot = "textarea",
	...restProps
}: WithoutChildren<WithElementRef<HTMLTextareaAttributes>> = $props();
</script>

<textarea
	bind:this={ref}
	data-slot={dataSlot}
	class={cn(
		"flex w-full field-sizing-content min-h-24 px-4 py-3 outline-none",
		"font-sans text-sm leading-relaxed tracking-[0.01em]",
		"bg-card text-foreground placeholder:text-muted-foreground",
		"border border-border-control rounded-xl",
		"transition-[border-color,box-shadow] duration-150",
		"focus-visible:border-primary focus-visible:shadow-[inset_0_0_0_1px_var(--primary)]",
		"aria-invalid:border-destructive aria-invalid:focus-visible:shadow-[inset_0_0_0_1px_var(--destructive)]",
		"disabled:bg-background disabled:text-muted-foreground disabled:cursor-not-allowed disabled:opacity-70",
		"dark:bg-card/60",
		className
	)}
	bind:value
	{...restProps}
></textarea>

// @/components/ui/textarea.tsx
import * as React from "react"

import { cn } from "@/lib/utils"

export interface TextareaProps
  extends React.TextareaHTMLAttributes<HTMLTextAreaElement> {}

const Textarea = React.forwardRef<HTMLTextAreaElement, TextareaProps>(
  ({ className, ...props }, ref) => {
    return (
      <textarea
        className={cn(
          "flex min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground  focus-visible:outline-none focus-visible:border-primary/80 disabled:cursor-not-allowed disabled:opacity-50",
          className
        )}
        ref={ref}
        {...props}
      />
    )
  }
)
Textarea.displayName = "Textarea"

export { Textarea }
