// src/routes/marketplace/products/[slug]/+page.svelte
<script lang="ts">
	import ProductCard from "$lib/components/marketplace/product-card.svelte";
	import RenderPost from "$lib/components/blog/render-post.svelte";
	import { Badge } from "$lib/components/ui/badge";
	import { Button } from "$lib/components/ui/button";
	import ArrowUpRight from "@lucide/svelte/icons/arrow-up-right";
	import CalendarDays from "@lucide/svelte/icons/calendar-days";
	import Download from "@lucide/svelte/icons/download";
	import Edit from "@lucide/svelte/icons/edit";
	import Heart from "@lucide/svelte/icons/heart";
	import Share2 from "@lucide/svelte/icons/share-2";
	import ShieldCheck from "@lucide/svelte/icons/shield-check";
	import Sparkles from "@lucide/svelte/icons/sparkles";
	import TagIcon from "@lucide/svelte/icons/tag";
	import { decodeHTMLEntities, marketwiseLink } from "src/utils/string";
	import { appConfig } from "@root/project.config";
	import { toast } from "svelte-sonner";

	let { data } = $props();

	async function shareProduct() {
		const url = `${appConfig.url}/marketplace/products/${data.product.slug}`;
		try {
			if (navigator.share) {
				await navigator.share({ title: data.product.name, url });
			} else {
				await navigator.clipboard.writeText(url);
				toast.success("Product link copied");
			}
		} catch {
			/* dismissed */
		}
	}
</script>

<div class="min-h-screen bg-background selection:text-primary">
	<div class="pointer-events-none fixed inset-0 z-0">
		<div
			class="absolute inset-0 bg-[linear-gradient(to_right,#80808008_1px,transparent_1px),linear-gradient(to_bottom,#80808008_1px,transparent_1px)] bg-[size:24px_24px]"
		></div>
		<div class="absolute top-20 left-1/4 h-[500px] w-[500px] rounded-full bg-primary/5 blur-[150px]"></div>
	</div>

	<div class="relative z-10 mx-auto w-full max-w-[1400px] px-4 pt-24 pb-16 md:px-6 lg:px-8">
		<nav class="mb-8 flex items-center gap-2 text-sm text-muted-foreground">
			<a href="/marketplace" class="transition-colors hover:text-foreground">Marketplace</a>
			<span>/</span>
			<span class="text-foreground">{decodeHTMLEntities(data.product.name)}</span>
		</nav>

		<div class="grid grid-cols-1 gap-8 lg:grid-cols-12 lg:gap-12">
			<div class="space-y-8 lg:col-span-8">
				<div class="relative aspect-video w-full overflow-hidden rounded-2xl border border-border/50 bg-muted shadow-lg">
					<img
						src={data.product.preview_url}
						alt={decodeHTMLEntities(data.product.name)}
						class="h-full w-full object-cover"
					/>
					{#if data.product.categories?.[0]}
						<div class="absolute top-4 left-4">
							<Badge class="rounded-full border-border/50 bg-background/80 px-3 py-1.5 shadow-lg backdrop-blur-md">
								{data.product.categories[0]}
							</Badge>
						</div>
					{/if}
				</div>

				<div class="space-y-6">
					<div>
						<h1 class="mb-3 text-3xl font-bold tracking-tight md:text-4xl">
							{decodeHTMLEntities(data.product.name)}
						</h1>

						<div class="flex flex-wrap items-center gap-4 text-sm text-muted-foreground">
							<a
								href={`/profiles/${data.product.creator?.username}`}
								class="group flex items-center gap-2 font-medium text-foreground transition-colors hover:text-primary"
							>
								<div class="h-6 w-6 rounded-full bg-linear-to-br from-primary to-violet-500"></div>
								<span class="underline-offset-4 group-hover:underline">
									@{data.product.creator?.username}
								</span>
							</a>

							<span class="h-1 w-1 rounded-full bg-border"></span>

							<span class="flex items-center gap-1.5">
								<CalendarDays class="h-4 w-4" />
								{new Date(data.product.createdAt).toLocaleDateString("en-US", {
									month: "short",
									day: "numeric",
									year: "numeric"
								})}
							</span>
						</div>
					</div>

					<div class="rounded-xl border border-border/50 bg-card/50 p-6 backdrop-blur-sm">
						<h2 class="mb-4 flex items-center gap-2 text-lg font-semibold">
							<Sparkles class="h-5 w-5 text-primary" />
							About this Asset
						</h2>
						<RenderPost content={data.product.description} />
					</div>

					<div class="space-y-3">
						<h3 class="flex items-center gap-2 text-sm font-semibold text-muted-foreground">
							<TagIcon class="h-4 w-4" />
							Tags
						</h3>
						<div class="flex flex-wrap gap-2">
							{#each data.product.tags.filter((tag) => tag.trim() !== "") as tag (tag)}
								<a
									href={`/marketplace/explore?tags=${encodeURIComponent(tag)}`}
									class="rounded-full border border-border/50 bg-card/50 px-3 py-1.5 text-sm text-muted-foreground transition-all hover:border-primary/50 hover:bg-primary/5 hover:text-foreground"
								>
									{tag}
								</a>
							{/each}
						</div>
					</div>

					<section class="border-t border-border/40 pt-8">
						<div class="mb-6 flex items-center justify-between">
							<h2 class="text-xl font-bold">
								More from {data.product.creator?.name ?? data.product.creator?.username}
							</h2>
							<a href={`/profiles/${data.product.creator?.username}`} class="text-primary inline-flex items-center">
								View Profile
								<ArrowUpRight class="ml-1 h-4 w-4" />
							</a>
						</div>

						{#if data.moreFromCreator.length === 0}
							<p class="text-sm text-muted-foreground">No other products from this creator yet.</p>
						{:else}
							<div class="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-3">
								{#each data.moreFromCreator as product (product._id)}
									<ProductCard {product} />
								{/each}
							</div>
						{/if}
					</section>
				</div>
			</div>

			<aside class="space-y-6 lg:col-span-4">
				<div class="sticky top-24 space-y-6">
					<div class="space-y-5 rounded-2xl border border-border/50 bg-card/80 p-6 shadow-lg backdrop-blur-sm">
						<div class="flex items-baseline justify-between border-b border-border/50 pb-4">
							<span class="text-sm font-medium text-muted-foreground">Price</span>
							<div class="text-right">
								<span class="text-3xl font-bold">
									{data.product.price ? `$${data.product.price}` : "Free"}
								</span>
								{#if data.product.price > 0}
									<p class="mt-1 ml-2 text-xs text-muted-foreground">One-time payment</p>
								{/if}
							</div>
						</div>

						<div class="space-y-3">
							<Button
								size="lg"
								class="h-12 w-full text-base font-semibold shadow-md"
								href={marketwiseLink(data.product.url, {
									utm_source: appConfig.url,
									utm_medium: "marketplace_product_page",
									utm_campaign: data.product.price ? "product_purchase" : "product_download"
								})}
								target="_blank"
							>
								{data.product.price ? "Buy Now" : "Download Free"}
								{#if data.product.price}
									<ArrowUpRight class="ml-2 h-4 w-4" />
								{:else}
									<Download class="ml-2 h-4 w-4" />
								{/if}
							</Button>

							<div class="grid grid-cols-2 gap-2">
								<Button variant="outline">
									<Heart class="mr-2 h-4 w-4" />
									Save
								</Button>
								<Button variant="outline" onclick={shareProduct}>
									<Share2 class="mr-2 h-4 w-4" />
									Share
								</Button>
							</div>
						</div>

						<div class="flex items-center justify-center gap-2 border-t border-border/50 pt-3 text-xs text-muted-foreground">
							<ShieldCheck class="h-4 w-4 text-emerald-500" />
							Secure & Instant Delivery
						</div>

						{#if data.isCreator}
							<div class="border-t border-border/50 pt-3">
								<Button variant="ghost" class="w-full text-muted-foreground hover:text-foreground" size="sm" href={`/dashboard/products`}>
									<Edit class="mr-2 h-4 w-4" />
									Manage Products
								</Button>
							</div>
						{/if}
					</div>

					<div class="space-y-4">
						<h3 class="text-lg font-semibold">Similar Assets</h3>
						{#if data.similarProducts.length === 0}
							<p class="text-sm text-muted-foreground">No similar products available.</p>
						{:else}
							<div class="space-y-4">
								{#each data.similarProducts.slice(0, 3) as product (product.slug)}
									<ProductCard {product} class="border-border/50 bg-card/50 shadow-sm hover:bg-card hover:shadow-md" />
								{/each}
							</div>
						{/if}
					</div>
				</div>
			</aside>
		</div>
	</div>
</div>

// _legacy/app/scout/tools/[slug]/page.tsx
import AdUnit from "@/components/common/adsense";
import ShareButton from "@/components/common/share-button";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import Navbar from "app/layouts/navbar-dynamic";
import {
  getPublicToolBySlug,
  getRatingsAndReviews,
  getSimilarTools,
  getToolMetaBySlug,
  postRatingAndReview,
  toggleBookmark,
} from "app/scout/lib/actions";
import { getAverageRating } from "app/scout/lib/utils";
import {
  ArrowUpRight,
  BarChart3,
  Calendar,
  CheckCircle2,
  Eye,
  Globe,
  Hash,
  MessageSquare,
  Share2,
  ShieldCheck,
  Sparkles,
  Star,
  Zap
} from "lucide-react";
import type { Metadata, ResolvingMetadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Suspense } from "react";
import MarkdownView from "src/components/markdown/view";
import { getImages } from "src/lib/scout";
import { RatingTypeWithId } from "src/models/tool-rating";
import { formatNumber } from "src/utils/formaters";
import { getSession } from "~/auth/server";
import { PublicToolTypeWithId } from "~/models/tool";

// Components
import { marketwiseLink } from "src/utils/string";
import { BookMarkButton } from "./bookmark";
import { PostReview } from "./post-review";
import RatingComponent from "./rating";
import SimilarTools from "./similar-tools";

// Type Definitions
interface Category {
  name: string;
  slug: string;
}

type Tool = PublicToolTypeWithId & {
  categories: Category[];
}

type Props = {
  params: Promise<{ slug: string }>;
};

// Metadata Generation
export async function generateMetadata(
  props: Props,
  parent: ResolvingMetadata
): Promise<Metadata> {
  const params = await props.params;
  const tool = await getToolMetaBySlug(params.slug);

  if (!tool) return {};

  return {
    title: `${tool.name} - Review & Pricing`,
    description: tool.description.substring(0, 160),
    keywords:
      tool.tags?.join(", ") ||
      tool.categories.map((category: Category) => category.name).join(", "),
    openGraph: {
      images: [tool.coverImage, tool?.bannerImage || tool.coverImage],
      title: tool.name,
      description: tool.description.substring(0, 160),
      url: `${process.env.NEXT_PUBLIC_WEBSITE_URL || "https://nexonauts.com"}/scout/tools/${tool.slug}`,
    },
    category: tool.categories.map((category: Category) => category.name).join(", "),
  };
}

const cache = new Map<string, boolean>();

export default async function ToolPage(props: Props) {
  const params = await props.params;

  // Fetch Tool Data
  const tool = (await getPublicToolBySlug(
    params.slug,
    cache.get(params.slug) || false
  )) as Tool | null;

  if (!tool) {
    return notFound();
  }

  cache.set(params.slug, true);

  // Fetch Context Data
  const session = await getSession();
  const ratings = (await getRatingsAndReviews(tool._id)) as RatingTypeWithId[];
  const similarTools = await getSimilarTools(tool.categories);
  const { bannerURL } = getImages(tool.link);

  const averageRating = getAverageRating(ratings || []);
  const reviewCount = ratings.length;

  // Server Action for Ratings
  async function publishRating(data: { rating: number; comment: string }) {
    "use server";
    try {
      if (!session || !session?.user) {
        throw new Error("You need to be logged in to rate a tool");
      }
      const rating = await postRatingAndReview({
        toolId: tool!._id,
        userId: session.user.id,
        rating: data.rating,
        comment: data.comment,
      });
      return rating;
    } catch (e) {
      console.error(e);
      throw e;
    }
  }

  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Navbar />

      {/* Subtle Background */}
      <div className="fixed inset-0 z-0 pointer-events-none">
        <div className="absolute inset-0 bg-[linear-gradient(to_right,#80808008_1px,transparent_1px),linear-gradient(to_bottom,#80808008_1px,transparent_1px)] bg-[size:24px_24px]" />
        <div className="absolute top-20 left-1/4 w-[500px] h-[500px] bg-primary/5 blur-[150px] rounded-full" />
      </div>

      <div className="relative z-10 w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-24 pb-16">

        {/* Breadcrumb */}
        <nav className="flex items-center gap-2 text-sm text-muted-foreground mb-6">
          <Link href="/scout/browse" className="hover:text-foreground transition-colors">Browse</Link>
          <span>/</span>
          <span className="text-foreground">{tool.name}</span>
        </nav>

        {/* Compact Header */}
        <div className="flex flex-col md:flex-row gap-5 mb-8 items-start">
          <div className="relative w-16 h-16 md:w-20 md:h-20 rounded-xl overflow-hidden border border-border/50 shadow-md shrink-0 bg-muted">
            <Image
              src={tool.coverImage}
              alt={tool.name}
              fill
              className="object-cover"
            />
          </div>

          <div className="flex-1 space-y-3">
            <div className="flex flex-wrap items-center gap-3">
              <h1 className="text-3xl md:text-4xl font-bold tracking-tight">{tool.name}</h1>
              {tool.verified && (
                <Badge className="px-2 py-1 rounded-md bg-emerald-500/10 border-emerald-500/20 text-emerald-600 text-xs font-semibold">
                  <CheckCircle2 className="w-3 h-3 mr-1" />
                  Verified
                </Badge>
              )}
            </div>

            <div className="flex flex-wrap items-center gap-3 text-sm text-muted-foreground">
              <div className="flex items-center gap-1.5">
                <Star className="w-4 h-4 text-amber-500 fill-amber-500" />
                <span className="font-semibold text-foreground">{averageRating}</span>
                <span>({reviewCount})</span>
              </div>
              <span className="w-1 h-1 rounded-full bg-border" />
              <div className="flex items-center gap-1.5">
                <Eye className="w-4 h-4" />
                <span className="font-medium text-foreground">{formatNumber(tool.views)}</span>
              </div>
              <span className="w-1 h-1 rounded-full bg-border" />
              <Badge variant="secondary" className="rounded-md px-2 py-0.5 text-xs capitalize bg-muted/50">
                {tool.pricing_type}
              </Badge>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">

          {/* LEFT COLUMN: Content */}
          <main className="lg:col-span-8 space-y-10">

            {/* Hero Image */}
            <div className="relative w-full aspect-video rounded-xl overflow-hidden border border-border/50 shadow-lg bg-muted">
              <Image
                fill
                src={bannerURL || tool.coverImage}
                alt={`${tool.name} screenshot`}
                className="object-cover"
                priority
                sizes="(max-width: 1024px) 100vw, 700px"
              />
            </div>

            {/* About Section */}
            <section className="space-y-4">
              <div className="flex items-center gap-2 pb-3 border-b border-border/40">
                <Zap className="w-5 h-5 text-primary" />
                <h2 className="text-xl font-semibold">About</h2>
              </div>
              <div className="prose prose-sm prose-zinc dark:prose-invert max-w-none prose-p:text-muted-foreground prose-headings:font-semibold prose-a:text-primary">
                <MarkdownView>{tool.description}</MarkdownView>
              </div>

              {/* Categories */}
              {tool.categories.length > 0 && (
                <div className="pt-4">
                  <div className="flex flex-wrap gap-2">
                    {tool.categories.map((category, i) => (
                      <Link
                        key={i}
                        href={`/scout/browse?category=${category.slug}`}
                        className="px-3 py-1.5 rounded-full border border-border/50 bg-card/50 text-sm text-muted-foreground hover:text-foreground hover:border-primary/50 hover:bg-primary/5 transition-all flex items-center gap-1.5"
                      >
                        <Hash className="w-3 h-3 opacity-50" />
                        {category.name}
                      </Link>
                    ))}
                  </div>
                </div>
              )}
            </section>

            {/* TOP IN-CONTENT AD */}
            <div className="w-full min-h-[250px] rounded-xl border border-border/40 bg-card/30 backdrop-blur-sm flex flex-col items-center justify-center overflow-hidden relative">
              <div className="absolute inset-0 bg-[radial-gradient(#00000008_1px,transparent_1px)] bg-size-[20px_20px]" />
              <div className="absolute top-3 left-1/2 -translate-x-1/2 px-3 py-1 rounded-full bg-muted/70 backdrop-blur-sm">
                <span className="text-[9px] font-bold text-muted-foreground uppercase tracking-widest">
                  Sponsored
                </span>
              </div>
              <div className="relative z-10 w-full flex items-center justify-center py-6">
                <AdUnit adSlot="in_feed" />
              </div>
            </div>

            {/* Reviews Section */}
            <section id="reviews" className="pt-8 border-t border-border/40">
              <div className="flex items-center gap-2 mb-6">
                <MessageSquare className="w-5 h-5 text-primary" />
                <h2 className="text-xl font-semibold">Reviews</h2>
              </div>

              <Tabs defaultValue="all" className="w-full">
                <TabsList className="bg-muted/50 border border-border/50 mb-6">
                  <TabsTrigger value="all">All ({ratings.length})</TabsTrigger>
                  <TabsTrigger value="write">Write Review</TabsTrigger>
                </TabsList>

                <TabsContent value="all" className="space-y-5">
                  {ratings.length > 0 ? (
                    <div className="space-y-5">
                      {ratings.map((rating) => (
                        <RatingComponent key={rating._id} rating={rating} />
                      ))}
                    </div>
                  ) : (
                    <div className="text-center py-12 bg-muted/20 rounded-xl border border-dashed border-border/50">
                      <Star className="w-10 h-10 text-muted-foreground/30 mx-auto mb-3" />
                      <p className="text-sm text-muted-foreground">No reviews yet. Be the first!</p>
                    </div>
                  )}
                </TabsContent>

                <TabsContent value="write">
                  {session?.user ? (
                    <PostReview tool={tool} postRatingAndReview={publishRating} />
                  ) : (
                    <div className="flex flex-col items-center justify-center py-12 bg-muted/20 rounded-xl border border-border/50">
                      <ShieldCheck className="w-10 h-10 text-muted-foreground/40 mb-4" />
                      <p className="mb-4 text-sm text-muted-foreground">Sign in to leave a review</p>
                      <Button asChild variant="outline" size="sm">
                        <Link href={`/auth/sign-in?callbackUrl=/scout/tools/${tool.slug}`}>Sign In</Link>
                      </Button>
                    </div>
                  )}
                </TabsContent>
              </Tabs>
            </section>

            {/* BOTTOM MULTIPLEX AD */}
            <div className="pt-8">
              <div className="flex items-center gap-3 mb-4">
                <Sparkles className="w-4 h-4 text-primary" />
                <span className="text-xs font-bold text-muted-foreground uppercase tracking-widest">
                  Related Tools
                </span>
                <div className="h-px flex-1 bg-border/50" />
              </div>
              <div className="min-h-[280px] w-full bg-card/40 backdrop-blur-sm rounded-xl border border-border/40 flex items-center justify-center p-4 overflow-hidden relative">
                <div className="absolute inset-0 bg-[radial-gradient(#00000005_1px,transparent_1px)] [background-size:16px_16px]" />
                <div className="relative z-10">
                  <AdUnit adSlot="multiplex_horizontal" />
                </div>
              </div>
            </div>

          </main>

          {/* RIGHT COLUMN: Sticky Sidebar */}
          <aside className="lg:col-span-4 space-y-6">
            <div className="sticky top-24 space-y-6">

              {/* CTA Card */}
              <div className="rounded-xl border border-border/50 bg-card/80 backdrop-blur-sm shadow-lg p-5 space-y-4">

                <div className="flex justify-between items-baseline pb-4 border-b border-border/50">
                  <span className="text-sm font-medium text-muted-foreground">Pricing</span>
                  <span className="text-2xl font-bold capitalize">{tool.pricing_type}</span>
                </div>

                <div className="space-y-3">
                  <Button
                    asChild
                    size="lg"
                    className="w-full h-11 text-base font-semibold shadow-md"
                  >
                    <Link href={marketwiseLink(tool.link,{
                      utm_medium: "referral",
                      utm_campaign: "tool_cta_button",
                      
                    })} target="_blank" rel="noopener noreferrer">
                      Visit Website
                      <ArrowUpRight className="ml-2 w-4 h-4" />
                    </Link>
                  </Button>

                  <div className="grid grid-cols-2 gap-2">
                    <BookMarkButton
                      tool={tool}
                      toggleBookmark={toggleBookmark}
                      userId={session?.user?.id || null}
                    />
                    <ShareButton
                      data={{
                        title: `Check out ${tool.name} on Nexonauts`,
                        url: `https://nexonauts.com/scout/tools/${tool.slug}`,
                      }}
                      variant="outline"
                      className="w-full justify-center"
                    >
                      <Share2 className="w-4 h-4 mr-2" />
                      Share
                    </ShareButton>
                  </div>
                </div>

                <Separator className="my-4" />

                {/* Stats */}
                <div className="space-y-3">
                  <h4 className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Details</h4>
                  <div className="space-y-3 text-sm">
                    <div className="flex items-center justify-between">
                      <span className="text-muted-foreground flex items-center gap-2">
                        <Globe className="w-3.5 h-3.5" /> Website
                      </span>
                      <span className="font-medium truncate max-w-[150px]" title={tool.link}>
                        {new URL(tool.link).hostname}
                      </span>
                    </div>
                    <div className="flex items-center justify-between">
                      <span className="text-muted-foreground flex items-center gap-2">
                        <BarChart3 className="w-3.5 h-3.5" /> Views
                      </span>
                      <span className="font-medium">{formatNumber(tool.views)}</span>
                    </div>
                    <div className="flex items-center justify-between">
                      <span className="text-muted-foreground flex items-center gap-2">
                        <Calendar className="w-3.5 h-3.5" /> Added
                      </span>
                      <span className="font-medium text-xs">
                        {new Date(tool?.createdAt || "").toLocaleDateString("en-US", {
                          month: "short",
                          day: "numeric",
                          year: "numeric",
                        })}
                      </span>
                    </div>
                  </div>
                </div>
              </div>

              {/* SIDEBAR AD (300x250) */}
              <div className="w-full min-h-[280px] rounded-xl bg-card/40 backdrop-blur-sm border border-border/40 flex flex-col overflow-hidden">
                <div className="w-full py-2 bg-muted/50 border-b border-border/40 text-center">
                  <span className="text-[9px] font-bold text-muted-foreground uppercase tracking-widest">
                    Sponsored
                  </span>
                </div>
                <div className="flex-1 flex items-center justify-center p-4">
                  <AdUnit adSlot="display-square" />
                </div>
              </div>

              {/* Similar Tools */}
              <div className="rounded-xl border border-border/50 bg-card/50 backdrop-blur-sm p-5">
                <h3 className="font-semibold mb-4 text-base">Similar Tools</h3>
                <Suspense fallback={
                  <div className="space-y-3">
                    {[1, 2, 3].map(i => (
                      <div key={i} className="h-16 animate-pulse bg-muted/50 rounded-lg" />
                    ))}
                  </div>
                }>
                  <SimilarTools tools={similarTools} toolName={tool.name} />
                </Suspense>
              </div>

              {/* SECOND SIDEBAR AD */}
              <div className="w-full min-h-[280px] rounded-xl bg-card/40 backdrop-blur-sm border border-border/40 flex flex-col overflow-hidden">
                <div className="w-full py-2 bg-muted/50 border-b border-border/40 text-center">
                  <span className="text-[9px] font-bold text-muted-foreground uppercase tracking-widest">
                    Sponsored
                  </span>
                </div>
                <div className="flex-1 flex items-center justify-center p-4">
                  <AdUnit adSlot="display-square" />
                </div>
              </div>

            </div>
          </aside>

        </div>
      </div>
    </div>
  );
}
