// src/routes/dashboard/products/+page.svelte
<script lang="ts">
	import { enhance } from "$app/forms";
	import { Badge } from "$lib/components/ui/badge";
	import { Button, buttonVariants } from "$lib/components/ui/button";
	import * as Card from "$lib/components/ui/card";
	import { Separator } from "$lib/components/ui/separator";
	import * as Sheet from "$lib/components/ui/sheet";
	import * as Table from "$lib/components/ui/table";
	import Import from "@lucide/svelte/icons/import";
	import Pencil from "@lucide/svelte/icons/pencil";
	import Plus from "@lucide/svelte/icons/plus";
	import Trash2 from "@lucide/svelte/icons/trash-2";
	import { toast } from "svelte-sonner";

	let { data, form } = $props();

	let importSheetOpen = $state(false);

	$effect(() => {
		if (data.showImportPanel) importSheetOpen = true;
	});

	$effect(() => {
		if (!form?.message) return;
		if (form.success) toast.success(form.message);
		else toast.error(form.message);
	});
</script>

<svelte:head>
	<title>Products - Dashboard</title>
</svelte:head>

<div class="space-y-6 p-4 pb-16 md:p-10">
	<div class="flex flex-wrap items-start justify-between gap-3">
		<div>
			<h1 class="text-lg font-semibold">Products</h1>
			<p class="text-muted-foreground text-sm font-medium">Manage your marketplace listings.</p>
		</div>
		<div class="flex flex-wrap items-center gap-2">
			<Sheet.Root bind:open={importSheetOpen}>
				<Sheet.Trigger class={buttonVariants({ variant: "outline", size: "sm" })}>
					<Import class="mr-1 h-4 w-4" />
					Import from Gumroad
				</Sheet.Trigger>
				<Sheet.Content class="w-full overflow-y-auto sm:max-w-lg">
					<Sheet.Header>
						<Sheet.Title>Import from Gumroad</Sheet.Title>
						<Sheet.Description>
							Pull a product from your connected Gumroad library into Nexonauts.
						</Sheet.Description>
					</Sheet.Header>

					{#if !data.gumroad}
						<div class="space-y-3 p-6">
							<a
								href="?importFrom=gumroad"
								class={buttonVariants({ variant: "default" })}
								data-sveltekit-keepfocus
							>
								Load my Gumroad library
							</a>
							<p class="text-muted-foreground text-xs">
								You'll need a Gumroad access token connected under
								<a class="text-primary underline" href="/dashboard/settings/integrations">
									Settings → Integrations
								</a>.
							</p>
						</div>
					{:else if !data.gumroad.ok}
						<div class="space-y-3 p-6">
							<p class="text-destructive text-sm">{data.gumroad.message}</p>
							<a
								href="/dashboard/settings/integrations"
								class={buttonVariants({ variant: "outline", size: "sm" })}
							>
								Manage integrations
							</a>
						</div>
					{:else if data.gumroad.products.length === 0}
						<p class="text-muted-foreground p-6 text-sm">No importable products on Gumroad.</p>
					{:else}
						<div class="space-y-3 p-6">
							{#each data.gumroad.products as product (product.id)}
								<div class="flex items-start gap-3 rounded-lg border p-3">
									{#if product.preview_url}
										<img
											src={product.preview_url}
											alt={product.name}
											class="h-16 w-16 rounded-md border object-cover"
										/>
									{/if}
									<div class="min-w-0 flex-1">
										<p class="truncate text-sm font-medium">{product.name}</p>
										<p class="text-muted-foreground text-xs">${product.price}</p>
									</div>
									<form
										method="POST"
										action="?/importGumroad"
										use:enhance={() => async ({ update }) => {
											await update();
										}}
									>
										<input type="hidden" name="gumroadProductId" value={product.id} />
										<Button type="submit" size="sm">Import</Button>
									</form>
								</div>
							{/each}
						</div>
					{/if}
				</Sheet.Content>
			</Sheet.Root>

			<a href="/dashboard/products/new" class={buttonVariants({ size: "sm" })}>
				<Plus class="mr-1 h-4 w-4" />
				New product
			</a>
		</div>
	</div>
	<Separator />

	<Card.Root>
		<Card.Header>
			<Card.Title>Your products</Card.Title>
			<Card.Description>Marketplace listings attached to your profile.</Card.Description>
		</Card.Header>
		<Card.Content>
			{#if data.products.length === 0}
				<p class="text-muted-foreground text-sm">No products yet.</p>
			{:else}
				<Table.Root>
					<Table.Header>
						<Table.Row>
							<Table.Head>Name</Table.Head>
							<Table.Head>Categories</Table.Head>
							<Table.Head>Price</Table.Head>
							<Table.Head>Status</Table.Head>
							<Table.Head>Created</Table.Head>
							<Table.Head class="text-right">Actions</Table.Head>
						</Table.Row>
					</Table.Header>
					<Table.Body>
						{#each data.products as product (product._id)}
							<Table.Row>
								<Table.Cell>
									<div class="flex flex-col">
										<span class="font-medium">{product.name}</span>
										<span class="text-muted-foreground text-xs">{product.slug}</span>
									</div>
								</Table.Cell>
								<Table.Cell>{product.categories.join(", ") || "Uncategorized"}</Table.Cell>
								<Table.Cell>${product.price}</Table.Cell>
								<Table.Cell>
									<Badge variant={product.published ? "default" : "secondary"}>
										{product.published ? "Published" : "Draft"}
									</Badge>
								</Table.Cell>
								<Table.Cell>{new Date(product.createdAt).toLocaleDateString()}</Table.Cell>
								<Table.Cell class="text-right">
									<div class="flex items-center justify-end gap-1">
										<a
											href="/dashboard/products/{product.slug}/edit"
											class={buttonVariants({ variant: "ghost", size: "icon-sm" })}
											title="Edit product"
										>
											<Pencil class="h-4 w-4" />
										</a>
										<form
											method="POST"
											action="?/delete"
											use:enhance={() => async ({ update }) => {
												await update();
											}}
											onsubmit={(event) => {
												if (!confirm(`Delete "${product.name}"? This cannot be undone.`)) {
													event.preventDefault();
												}
											}}
										>
											<input type="hidden" name="productId" value={product._id} />
											<Button
												type="submit"
												size="icon-sm"
												variant="ghost"
												class="text-destructive hover:bg-destructive/10"
												title="Delete product"
											>
												<Trash2 class="h-4 w-4" />
											</Button>
										</form>
									</div>
								</Table.Cell>
							</Table.Row>
						{/each}
					</Table.Body>
				</Table.Root>
			{/if}
		</Card.Content>
	</Card.Root>
</div>

// app/admin/products/page.tsx
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet";
import { ButtonLink } from "@/components/utils/link";
import {
  ArrowRight,
  Box,
  Import,
  Loader2,
  MoreVertical,
  Plus,
  Search
} from "lucide-react";
import { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Suspense } from "react";
import { Icon } from "src/lib/integrations/index";
import {
  deleteProduct,
  fetchFromIntegration,
  getProducts,
  importProduct,
} from "./actions";
import DeleteProductButton from "./components/delete-btn";
import { FilterAndSort, ImportedProductCard } from "./components/products";

export const metadata: Metadata = {
  title: "My Products - Dashboard",
  description: "Manage your digital assets.",
};

type PageProps = {
  searchParams: Promise<{
    importFrom?: string;
    filter?: string;
    sort?: string;
  }>;
};

const availableIntegrations = ["gumroad"];

export default async function MyProducts(props: PageProps) {
  const searchParams = await props.searchParams;

  const { products, integrated } = await getProducts(
    searchParams.filter ?? "all",
    searchParams.sort ?? "latest"
  );

  const importFrom = availableIntegrations.includes(
    searchParams?.importFrom ?? "none"
  )
    ? searchParams.importFrom
    : null;

  const getFromIntegrations = async () => {
    "use server";
    if (importFrom === null) return Promise.resolve([]);
    if (!availableIntegrations.includes(importFrom as string)) {
      return Promise.resolve([]);
    }
    const data = await fetchFromIntegration(importFrom as string);
    return data;
  };

  const productsFromIntegrations = await getFromIntegrations();
  const productsIds = products
    .filter((product) => product?.third_party !== null)
    .map((product) => product?.third_party?.product_id);

  return (
    <div className="min-h-screen w-full">


      <div className="relative z-10 max-w-[1600px] mx-auto px-4 sm:px-6 lg:px-8 py-8">

        {/* --- Header --- */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 mb-8">
          <div>
            <h1 className="text-3xl font-bold tracking-tight text-foreground flex items-center gap-3">
              Products
              <span className="text-sm font-medium text-muted-foreground bg-muted px-2 py-0.5 rounded-full">
                {products.length}
              </span>
            </h1>
            <p className="text-muted-foreground mt-1">Manage and track your digital assets.</p>
          </div>

          <div className="flex flex-wrap items-center gap-3">
            <Sheet>
              <SheetTrigger asChild>
                <Button variant="outline" className="gap-2">
                  <Import className="w-4 h-4" />
                  Import
                </Button>
              </SheetTrigger>
              <SheetContent className="w-full sm:max-w-lg">
                <SheetHeader className="mb-6">
                  <SheetTitle>Import Products</SheetTitle>
                  <SheetDescription>
                    Sync products from your connected platforms.
                  </SheetDescription>
                </SheetHeader>

                {importFrom ? (
                  <div className="space-y-4 h-full flex flex-col">
                    <div className="flex items-center justify-between">
                      <h3 className="text-sm font-semibold uppercase tracking-wider text-muted-foreground">
                        {importFrom} Library
                      </h3>
                      <Link href="?" className="text-xs text-primary hover:underline">
                        Change Source
                      </Link>
                    </div>

                    <Suspense fallback={
                      <div className="flex-1 flex flex-col items-center justify-center space-y-4">
                        <Loader2 className="w-8 h-8 animate-spin text-muted-foreground" />
                        <p className="text-sm text-muted-foreground">Fetching library...</p>
                      </div>
                    }>
                      <ScrollArea className="flex-1 -mx-6 px-6">
                        <div className="space-y-4 pb-10">
                          {productsFromIntegrations
                            .filter(p => !productsIds.includes(p.third_party.product_id))
                            .map((product) => (
                              <ImportedProductCard
                                key={product.third_party.product_id}
                                product={product}
                                importProduct={importProduct.bind(null, product)}
                              />
                            ))
                          }
                          {productsFromIntegrations.length === 0 && (
                            <p className="text-center text-muted-foreground py-10">No new products found.</p>
                          )}
                        </div>
                      </ScrollArea>
                    </Suspense>
                  </div>
                ) : (
                  <div className="grid gap-4 py-4">
                    {availableIntegrations.map((integration) => (
                      <ButtonLink
                        key={integration}
                        href={integrated ? `?importFrom=${integration}` : `/settings/integrations/${integration}`}
                        variant="outline"
                        className="h-16 justify-start px-4"
                      >
                        <div className="h-10 w-10 bg-muted rounded-lg flex items-center justify-center mr-4">
                          <Icon icon={integration} className="w-6 h-6" />
                        </div>
                        <div className="text-left">
                          <span className="block font-semibold capitalize">{integration}</span>
                          <span className="block text-xs text-muted-foreground">
                            {integrated ? "Browse library" : "Connect account"}
                          </span>
                        </div>
                        <ArrowRight className="ml-auto w-4 h-4 text-muted-foreground" />
                      </ButtonLink>
                    ))}
                  </div>
                )}
              </SheetContent>
            </Sheet>

            <ButtonLink href="/dashboard/products/new" className="gap-2 shadow-lg shadow-primary/20">
              <Plus className="w-4 h-4" />
              Create New
            </ButtonLink>
          </div>
        </div>

        {/* --- Toolbar --- */}
        <div className="flex flex-col sm:flex-row gap-4 items-center justify-between mb-6 p-1">
          <div className="relative w-full sm:max-w-xs">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
            <Input
              placeholder="Search products..."
              className="pl-9 bg-background/50 border-border/50"
            />
          </div>
          <FilterAndSort />
        </div>

        {/* --- Content Grid --- */}
        <Suspense fallback={<ProductGridSkeleton />}>
          {products.length > 0 ? (
            <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
              {products.map((product) => (
                <div
                  key={product._id}
                  className="group flex flex-col bg-card border border-border/50 rounded-2xl overflow-hidden hover:border-primary/30 hover:shadow-lg transition-all duration-300"
                >
                  {/* Image Header */}
                  <div className="relative h-48 w-full bg-muted border-b border-border/50 overflow-hidden">
                    <Image
                      src={product.preview_url || "/placeholder.png"}
                      alt={product.name}
                      fill
                      className="object-cover transition-transform duration-500 group-hover:scale-105"
                    />
                    <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300" />

                    <div className="absolute top-3 right-3 flex gap-2 opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                      <Button variant="secondary" size="icon" className="h-8 w-8 bg-background/90 backdrop-blur" asChild>
                        <Link href={`/dashboard/products/${product.slug}/edit`}>
                          <span className="sr-only">Edit</span>
                          <MoreVertical className="w-4 h-4" />
                        </Link>
                      </Button>
                    </div>
                  </div>

                  {/* Content */}
                  <div className="p-5 flex flex-col flex-1">
                    <div className="flex justify-between items-start mb-2">
                      <h3 className="font-semibold text-lg line-clamp-1 group-hover:text-primary transition-colors">
                        {product.name}
                      </h3>
                    </div>

                    <div className="mt-auto pt-4 flex items-center justify-between border-t border-border/50">
                      <div className="flex gap-2">
                        <ButtonLink variant="light" size="sm" href={`/marketplace/products/${product.slug}`} target="_blank">
                          View Live
                        </ButtonLink>
                        <ButtonLink variant="ghost" size="sm" href={`/dashboard/products/${product.slug}/edit`}>
                          Edit
                        </ButtonLink>
                      </div>
                      <DeleteProductButton deleteProduct={deleteProduct.bind(null, product._id)} />
                    </div>
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <EmptyState />
          )}
        </Suspense>

      </div>
    </div>
  );
}

function ProductGridSkeleton() {
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
      {[1, 2, 3].map(i => (
        <div key={i} className="h-[300px] rounded-2xl bg-muted/20 animate-pulse border border-border/50" />
      ))}
    </div>
  )
}

function EmptyState() {
  return (
    <div className="flex flex-col items-center justify-center py-20 text-center border-2 border-dashed border-border/50 rounded-3xl bg-muted/5">
      <div className="w-16 h-16 bg-muted/50 rounded-full flex items-center justify-center mb-6">
        <Box className="w-8 h-8 text-muted-foreground" />
      </div>
      <h3 className="text-xl font-semibold text-foreground">No products yet</h3>
      <p className="text-muted-foreground max-w-sm mx-auto mb-8">
        Start building your library by creating a new product or importing from Gumroad.
      </p>
      <ButtonLink href="/dashboard/products/new">
        Create First Product
      </ButtonLink>
    </div>
  )
}
