// src/routes/blog/articles/[slug]/+page.svelte
<script lang="ts">
	import PostHeader from "$lib/components/blog/post-header.svelte";
	import RenderPost from "$lib/components/blog/render-post.svelte";
	import Sidebar from "$lib/components/blog/sidebar.svelte";

	let { data } = $props();
	const post = $derived(data.post);
</script>

<svelte:head>
	<title>{post.title}</title>
	<meta name="description" content={post.description ?? ""} />
</svelte:head>

<div class="w-full">
	<PostHeader
		title={post.title}
		image={post.image}
		author={post.author}
		createdAt={String(post.createdAt)}
	/>

	<main class="mx-auto w-full max-w-7xl px-4 py-8 sm:px-6">
		<div class="flex flex-col gap-8 lg:flex-row lg:gap-12">
			<div class="flex-1">
				<RenderPost content={String(post.content ?? "")} />
			</div>
			<div class="lg:w-80">
				<Sidebar
					author={post.author}
					createdAt={String(post.createdAt)}
					content={String(post.content ?? "")}
				/>
			</div>
		</div>
	</main>
</div>

// app/blog/articles/[slug]/page.tsx
import { Metadata } from "next";
import { notFound } from "next/navigation";
import { getPostBySlug } from "src/lib/blog/actions";
import { CommentsSection, PostHeader, RenderPost, SideBar } from "./components";

export const revalidate = 60;

export async function generateMetadata({
  params,
}: {
  params: {
    slug: string;
  };
}) {
  const { post, success } = await getPostBySlug(params.slug);
  if (!post || success === false) {
    console.log("Post not found, Slug :", params.slug);
    return notFound();
  }
  const metadata: Metadata = {
    title: post.title,
    description: post.description,
  };
  return metadata;
}

export default async function PostPage({
  params,
}: {
  params: {
    slug: string;
  };
}) {
  const { post, success } = await getPostBySlug(params.slug);

  if (!post || success === false) {
    console.log("Post not found, Slug :", params.slug);
    return notFound();
  }

  return (
    <>
      <PostHeader
        title={post.title}
        image={post.image}
        author={post.author}
        createdAt={post.createdAt.toString()}
      />
      <main className="w-full mx-auto flex justify-around items-start gap-4 flex-col @4xl:flex-row px-4 lg:px-8 pt-8">
        <RenderPost content={post.content} />
        <SideBar
          author={post.author}
          createdAt={post.createdAt.toString()}
          content={post.content}
        />
      </main>
      <div id="comments-section" className="w-full mx-auto max-w-5xl">
        <CommentsSection />
      </div>
    </>
  );
}
