// src/lib/components/marketplace/product-card.svelte
<script lang="ts">
	import { Badge } from "$lib/components/ui/badge";
	import ArrowUpRight from "@lucide/svelte/icons/arrow-up-right";
	import type { MarketplaceProduct } from "$lib/server/marketplace";
	import { decodeHTMLEntities } from "src/utils/string";

	let { product, class: className = "" }: { product: MarketplaceProduct; class?: string } = $props();

	const displayPrice = $derived(product.price ? `$${product.price}` : "Free");
</script>

<a
	href={`/marketplace/products/${product.slug}`}
	class={`group flex w-full flex-col gap-3 rounded-xl transition-all duration-300 ${className}`}
>
	<div
		class="relative aspect-[16/10] w-full overflow-hidden rounded-xl border border-border/40 bg-muted shadow-sm transition-all duration-500 hover:border-primary/30 hover:shadow-xl hover:shadow-primary/5"
	>
		<img
			src={product.preview_url}
			alt={decodeHTMLEntities(product.name)}
			class="h-full w-full object-cover transition-transform duration-700 ease-in-out group-hover:scale-105"
		/>

		<div class="absolute top-3 right-3 z-10">
			<Badge
				variant="secondary"
				class={product.price ? "bg-white/90 text-black dark:bg-black/80 dark:text-white" : "bg-emerald-500/90 text-white"}
			>
				{displayPrice}
			</Badge>
		</div>
	</div>

	<div class="space-y-1">
		<div class="flex items-start justify-between gap-2">
			<h3 class="line-clamp-1 text-base leading-tight font-semibold transition-colors group-hover:text-primary">
				{decodeHTMLEntities(product.name)}
			</h3>
			<ArrowUpRight
				class="h-4 w-4 -translate-x-2 text-muted-foreground opacity-0 transition-all duration-300 group-hover:translate-x-0 group-hover:opacity-100"
			/>
		</div>

		{#if product.categories?.length}
			<p class="text-xs text-muted-foreground">{product.categories[0]}</p>
		{/if}
	</div>
</a>

// app/marketplace/products/[slug]/product-card.tsx
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";
import { ArrowUpRight } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { ProductType } from "src/models/product";
import { decodeHTMLEntities } from "src/utils/string";

export function ProductCard({ product, className }: { product: ProductType, className?: string }) {
  return (
    <Link
      key={product._id}
      href={`/marketplace/products/${product.slug!}`}
      className={cn(
        "flex flex-col rounded-xl overflow-hidden border border-border/50",
        "bg-card shadow-sm transition-all duration-300 group",
        "hover:shadow-md hover:border-primary/30",
        className
      )}
    >
      <div className="relative w-full aspect-video">
        <Image
          fill
          src={product.preview_url!}
          alt={decodeHTMLEntities(product.name)}
          className="object-cover"
          sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw"
        />
      </div>

      <div className="p-4">
        <div className="flex justify-between items-start gap-2 ">
          <h3 className="font-semibold line-clamp-1 text-base">
            {decodeHTMLEntities(product.name)}
          </h3>
          <ArrowUpRight className="size-4 shrink-0 mt-1 text-muted-foreground opacity-0 group-hover:opacity-100 group-hover:text-primary group-hover:-translate-y-1 transition-transform duration-500" />
        </div>

        <div className="flex justify-between items-center">
          <div>
            {product.price ? (
              <Badge variant="info_light" size="sm" className="font-medium">
                ${product.price}
              </Badge>
            ) : (
              <Badge variant="default" size="sm" className="font-medium">
                Free
              </Badge>
            )}
          </div>

          <div>
            {product.categories!.length > 0 ? (
              <Badge variant="default_light" className="font-medium">
                {product.categories![0]}
              </Badge>
            ) : null}
          </div>
        </div>
      </div>
    </Link>);
}
