// src/lib/components/scout/tool-card.svelte
<script lang="ts">
	import { Badge } from "$lib/components/ui/badge";
	import type { ScoutTool } from "$lib/server/scout";
	import { getImages } from "$lib/scout";
	import { cn } from "$lib/utils";
	import ArrowUpRight from "@lucide/svelte/icons/arrow-up-right";
	import Hash from "@lucide/svelte/icons/hash";
	import Verified from "@lucide/svelte/icons/verified";
	import { decodeHTMLEntities } from "src/utils/string";

	type ViewMode = "grid" | "list";

	let {
		tool,
		view = "grid",
		class: className = ""
	}: {
		tool: ScoutTool;
		view?: ViewMode;
		class?: string;
	} = $props();

	const images = $derived(getImages(tool.link || ""));
	const isList = $derived(view === "list");
</script>

<a
	href={`/scout/tools/${tool.slug}`}
	class={cn(
		"group flex h-full rounded-xl border border-border/50 bg-card/50 backdrop-blur-sm overflow-hidden transition-all duration-300 hover:-translate-y-0.5 hover:border-primary/40 hover:shadow-lg hover:shadow-primary/5",
		isList ? "flex-row items-stretch" : "flex-col",
		className
	)}
>
	<div
		class={cn(
			"relative overflow-hidden bg-muted",
			isList ? "w-40 shrink-0 border-r border-border/50 md:w-56" : "aspect-video w-full border-b border-border/50"
		)}
	>
		<img
			src={images?.bannerURL || tool.coverImage || "/placeholder.png"}
			alt={decodeHTMLEntities(tool.name)}
			class="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105"
			loading="lazy"
		/>

		{#if tool.verified}
			<div class="absolute top-2 right-2 rounded-full border border-border/50 bg-background/90 p-1.5 shadow-sm backdrop-blur-md">
				<Verified class="h-3.5 w-3.5 text-emerald-500" />
			</div>
		{/if}
	</div>

	<div class="flex flex-1 flex-col p-4">
		<div class="mb-2 flex items-start justify-between gap-2">
			<h3 class="line-clamp-1 text-base font-semibold text-foreground transition-colors group-hover:text-primary">
				{decodeHTMLEntities(tool.name)}
			</h3>
			<Badge
				variant="secondary"
				class={cn(
					"shrink-0 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider",
					tool.pricing_type === "free"
						? "border-emerald-500/20 bg-emerald-500/10 text-emerald-600"
						: "bg-muted text-muted-foreground"
				)}
			>
				{tool.pricing_type}
			</Badge>
		</div>

		<p class="line-clamp-2 text-sm leading-relaxed text-muted-foreground">
			{tool.description}
		</p>

		<div class="mt-auto flex flex-wrap gap-1.5 pt-3">
			{#each (tool.categories ?? []).slice(0, 3) as category (category.slug)}
				<span
					class="inline-flex items-center gap-1 rounded-md border border-transparent bg-muted/50 px-2 py-1 text-xs text-muted-foreground transition-colors group-hover:border-border/50"
				>
					<Hash class="h-3 w-3 opacity-50" />
					{category.name}
				</span>
			{/each}
		</div>

		<div class="mt-3 flex items-center text-xs font-medium text-primary opacity-0 transition-all duration-300 group-hover:opacity-100">
			View details
			<ArrowUpRight class="ml-1 h-3 w-3" />
		</div>
	</div>
</a>

// _legacy/app/dev-tools/components/tool-card.tsx
"use client";

import { ArrowRight, Box, Sparkles, Wrench } from "lucide-react";
import Link from "next/link";

// Helper to determine icon based on category (optional, adds visual flair)
const getCategoryIcon = (category: string) => {
  const lower = category?.toLowerCase() || "";
  if (lower.includes("ai") || lower.includes("bot")) return Sparkles;
  if (lower.includes("design") || lower.includes("ui")) return Box;
  return Wrench;
};

interface ToolCardProps {
  title: string;
  description: string;
  path: string;
  category?: string; // Added category to props
  id?: string;
  style?: React.CSSProperties;
  className?: string;
}

export function ToolCard({
  title,
  description,
  path,
  category = "Utility",
  style,
  className,
}: ToolCardProps) {
  const Icon = getCategoryIcon(category);

  return (
    <Link
      href={path}
      style={style}
      className={`group relative flex flex-col justify-between h-full p-6 rounded-2xl border border-border/60 bg-card/40 backdrop-blur-sm transition-all duration-300 hover:shadow-2xl hover:shadow-primary/10 hover:border-primary/50 hover:-translate-y-1 ${className}`}
    >
      {/* --- Hover Gradient Effect --- */}
      <div
        aria-hidden="true"
        className="absolute inset-0 rounded-2xl bg-gradient-to-br from-primary/5 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500"
      />

      {/* --- Header Section --- */}
      <div className="relative z-10 flex items-start justify-between mb-4">
        {/* Icon Box */}
        <div className="h-12 w-12 rounded-xl bg-background border border-border/50 shadow-inner flex items-center justify-center text-primary transition-transform duration-300 group-hover:scale-110 group-hover:rotate-3">
          <span className="text-xl font-bold font-mono">
            {/* Fallback to first letter if no icon provided */}
            {title.charAt(0)}
          </span>
        </div>

        {/* Category Pill */}
        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-muted/50 border border-border/50 text-[10px] uppercase tracking-wider font-semibold text-muted-foreground">
          <Icon className="w-3 h-3" />
          {category}
        </div>
      </div>

      {/* --- Content Section --- */}
      <div className="relative z-10 flex flex-col grow">
        <h3 className="text-lg font-semibold tracking-tight text-foreground mb-2 group-hover:text-primary transition-colors duration-300">
          {title}
        </h3>

        <p className="text-sm text-muted-foreground leading-relaxed line-clamp-3 mb-6">
          {description}
        </p>
      </div>

      {/* --- Footer / Action --- */}
      <div className="relative z-10 mt-auto pt-4 border-t border-border/30 flex items-center text-sm font-medium text-primary">
        <span className="mr-2">Try this tool</span>
        <ArrowRight className="w-4 h-4 transition-transform duration-300 transform group-hover:translate-x-1" />
      </div>
    </Link>
  );
}
