// src/routes/scout/browse/+page.svelte
<script lang="ts">
	import ToolCard from "$lib/components/scout/tool-card.svelte";
	import { Badge } from "$lib/components/ui/badge";
	import { Button } from "$lib/components/ui/button";
	import { Input } from "$lib/components/ui/input";
	import Grid2x2 from "@lucide/svelte/icons/grid-2x2";
	import List from "@lucide/svelte/icons/list";
	import Search from "@lucide/svelte/icons/search";
	import SearchX from "@lucide/svelte/icons/search-x";
	import Sparkles from "@lucide/svelte/icons/sparkles";
	import X from "@lucide/svelte/icons/x";

	let { data } = $props();
	const currentView = $derived(data.view === "list" ? "list" : "grid");

	const hasActiveFilters = $derived(
		Boolean(
			data.filter.category !== "all" ||
				data.filter.pricing_type !== "all" ||
				data.query ||
				data.offset
		)
	);

	function buildHref(next: Record<string, string | number>) {
		const params = new URLSearchParams();
		const entries: Record<string, string | number> = {
			query: data.query,
			page: data.page,
			offset: data.offset,
			view: data.view,
			category: data.filter.category,
			pricing_type: data.filter.pricing_type,
			...next
		};

		for (const [key, value] of Object.entries(entries)) {
			if (value === "" || value === "all" || value === 0) continue;
			params.set(key, String(value));
		}

		const query = params.toString();
		return query ? `/scout/browse?${query}` : "/scout/browse";
	}

	const paginationItems = $derived.by(() => {
		const start = Math.max(1, data.page - 2);
		const end = Math.min(data.totalPages, data.page + 2);
		return Array.from({ length: end - start + 1 }, (_, index) => start + index);
	});
</script>

<div class="min-h-screen bg-background">
	<div class="pointer-events-none fixed inset-0 z-0">
		<div
			class="absolute inset-0 bg-[linear-gradient(to_right,#80808008_1px,transparent_1px),linear-gradient(to_bottom,#80808008_1px,transparent_1px)] bg-[size:24px_24px]"
		></div>
		<div class="absolute top-20 right-0 h-[600px] w-[600px] rounded-full bg-primary/5 blur-[150px]"></div>
	</div>

	<div class="relative z-10 w-full border-b border-border/40 pt-20">
		<div class="mx-auto max-w-[1600px] px-4 py-10 sm:px-6">
			<div class="max-w-2xl">
				<div class="mb-3 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">
					<Sparkles class="h-3 w-3" />
					<span>Curated Tools</span>
				</div>
				<h1 class="mb-3 text-3xl font-bold tracking-tight md:text-4xl">{data.hero.title}</h1>
				<p class="text-base text-muted-foreground">{data.hero.description}</p>
			</div>
		</div>
	</div>

	<div class="relative z-10 mx-auto flex w-full max-w-[1600px] gap-8 px-4 py-8 sm:px-6">
		<aside class="hidden h-fit w-72 shrink-0 space-y-6 lg:block lg:sticky lg:top-24">
			<div class="rounded-xl border border-border/50 bg-card/50 p-4 backdrop-blur-sm">
				<h3 class="mb-4 text-sm font-semibold">Pricing</h3>
				<div class="flex flex-wrap gap-2">
					{#each data.pricingTypes as pricingType (pricingType)}
						<a href={buildHref({ pricing_type: pricingType, page: 1 })}>
							<Badge variant={data.filter.pricing_type === pricingType ? "default" : "outline"}>
								{pricingType}
							</Badge>
						</a>
					{/each}
				</div>
			</div>

			<div class="rounded-xl border border-border/50 bg-card/50 p-4 backdrop-blur-sm">
				<h3 class="mb-4 text-sm font-semibold">Categories</h3>
				<div class="flex flex-wrap gap-2">
					{#each data.categories as category (category.slug)}
						<a href={buildHref({ category: category.slug, page: 1 })}>
							<Badge variant={data.filter.category === category.slug ? "default" : "outline"}>
								{category.name}
							</Badge>
						</a>
					{/each}
				</div>
			</div>
		</aside>

		<main class="min-w-0 flex-1 space-y-6">
			<div class="sticky top-20 z-30 rounded-xl border border-border/50 bg-background/80 p-3 shadow-sm backdrop-blur-xl">
				<div class="flex flex-col gap-3 sm:flex-row sm:items-center">
					<form action="/scout/browse" method="GET" class="relative w-full sm:flex-1">
						<div class="pointer-events-none absolute inset-y-0 left-3 flex items-center">
							<Search class="h-4 w-4 text-muted-foreground" />
						</div>
						<Input
							name="query"
							value={data.query}
							placeholder="Search tools, categories, or tags"
							class="h-11 rounded-full border-border/50 bg-card/70 pr-4 pl-10 backdrop-blur-sm"
						/>
						<input type="hidden" name="category" value={data.filter.category} />
						<input type="hidden" name="pricing_type" value={data.filter.pricing_type} />
						<input type="hidden" name="view" value={data.view} />
					</form>

					<div class="flex items-center gap-2">
						<a href={buildHref({ view: "grid" })}>
							<Badge variant={data.view === "grid" ? "default" : "outline"} class="gap-1.5 px-3 py-2">
								<Grid2x2 class="h-3.5 w-3.5" />
								Grid
							</Badge>
						</a>
						<a href={buildHref({ view: "list" })}>
							<Badge variant={data.view === "list" ? "default" : "outline"} class="gap-1.5 px-3 py-2">
								<List class="h-3.5 w-3.5" />
								List
							</Badge>
						</a>
					</div>
				</div>
			</div>

			<div class="px-1 text-sm text-muted-foreground">
				{#if data.query}
					<span>
						<span class="font-semibold text-foreground">{data.totalResults}</span>
						results for "{data.query}"
					</span>
				{:else}
					<span>
						<span class="font-semibold text-foreground">{data.totalResults}</span>
						tools available
					</span>
				{/if}
			</div>

			{#if hasActiveFilters}
				<div class="flex flex-wrap items-center gap-2">
					<span class="text-xs font-medium text-muted-foreground">Active:</span>
					{#if data.filter.category !== "all"}
						<a href={buildHref({ category: "", page: 1 })} class="inline-flex">
							<Badge class="gap-1.5 bg-primary/10 text-primary">
								{data.filter.category}
								<X class="h-3 w-3" />
							</Badge>
						</a>
					{/if}
					{#if data.filter.pricing_type !== "all"}
						<a href={buildHref({ pricing_type: "", page: 1 })} class="inline-flex">
							<Badge class="gap-1.5 bg-primary/10 text-primary">
								{data.filter.pricing_type}
								<X class="h-3 w-3" />
							</Badge>
						</a>
					{/if}
					{#if data.query}
						<a href={buildHref({ query: "", page: 1 })} class="inline-flex">
							<Badge class="gap-1.5 bg-primary/10 text-primary">
								Search
								<X class="h-3 w-3" />
							</Badge>
						</a>
					{/if}
					<a href="/scout/browse" class="text-xs text-muted-foreground underline underline-offset-2">
						Clear all
					</a>
				</div>
			{/if}

			{#if data.tools.length === 0}
				<div class="flex justify-center py-20">
					<div class="rounded-2xl border border-dashed border-border/60 bg-card/20 px-8 py-16 text-center">
						<div class="mb-5 flex justify-center">
							<div class="flex h-16 w-16 items-center justify-center rounded-full bg-muted/50">
								<SearchX class="h-7 w-7 text-muted-foreground" />
							</div>
						</div>
						<h3 class="mb-2 text-lg font-semibold">No tools found</h3>
						<p class="mb-6 max-w-sm text-sm text-muted-foreground">
							Try adjusting your filters or search query.
						</p>
						<Button href="/scout/browse" variant="outline">Reset Filters</Button>
					</div>
				</div>
			{:else}
				<div
					class={currentView === "list"
						? "grid grid-cols-1 gap-4"
						: "grid grid-cols-1 gap-6 sm:grid-cols-2 xl:grid-cols-3"}
				>
					{#each data.tools as tool (tool._id)}
						<ToolCard {tool} view={currentView} />
					{/each}
				</div>

				{#if data.totalPages > 1}
					<div class="flex flex-wrap items-center justify-center gap-2 border-t border-border/40 pt-8">
						<Button
							variant="outline"
							href={buildHref({ page: Math.max(1, data.page - 1) })}
							disabled={data.page <= 1}
						>
							Previous
						</Button>

						{#each paginationItems as pageNumber (pageNumber)}
							<a href={buildHref({ page: pageNumber })}>
								<Badge variant={pageNumber === data.page ? "default" : "outline"} class="px-3 py-2">
									{pageNumber}
								</Badge>
							</a>
						{/each}

						<Button
							variant="outline"
							href={buildHref({ page: Math.min(data.totalPages, data.page + 1) })}
							disabled={data.page >= data.totalPages}
						>
							Next
						</Button>
					</div>
				{/if}
			{/if}
		</main>
	</div>
</div>

// app/tool-scout/browse/page.tsx
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import Navbar from "app/layouts/navbar";
import { FilterButton, SearchBar } from "app/tool-scout/browse/search";
import { getTools } from 'app/tool-scout/lib/actions';
import LazyImage from "components/image";
import { Hash } from 'lucide-react';
import { Metadata } from "next";
import Link from "next/link";
import { TracingBeam } from "src/components/animations/tracing-beam";
import { PublicToolPricingType } from "src/models/tool";

export const metadata: Metadata = {
    title: "Browse Nexo Scout - AI Tools, Services, and Resources",
    description: "Nexo Scout is a curated list of AI tools, services, and resources. Find the best AI tools for your business.",
}




export default async function BrowsePage({
    searchParams,
}: {
    searchParams?: {
        query?: string,
        page?: string,
        pricing_type?: string,
        category?: string,
    };
}) {
    const query = searchParams?.query || '';
    const currentPage = Number(searchParams?.page) || 1;
    const filter = {
        pricing_type: searchParams?.pricing_type as PublicToolPricingType || "all",
        category: searchParams?.category || "all",
    }

    const { tools, categories, totalPages, pricing_types } = await getTools(query, currentPage, filter);


    return (<>
        <header>
            <Navbar />
        </header>
        <div className="relative" id="home">
            <div aria-hidden="true" className="fixed inset-0 grid grid-cols-2 -space-x-52 opacity-40 dark:opacity-20 -z-1">
                <div className="blur-[106px] h-56 bg-gradient-to-br from-primary to-purple-400 dark:from-blue-700" />
                <div className="blur-[106px] h-32 bg-gradient-to-r from-cyan-400 to-sky-300 dark:to-indigo-600" />
            </div>
        </div>
        <div className="flex items-start justify-start gap-4 h-full w-full max-w-[1440px] mx-auto pt-32">

            <main id="content" className="grow w-full">
                <TracingBeam>
                    <div className="p-3">
                        <SearchBar />
                        <div className="flex items-center justify-between w-full mt-4  z-10">
                            <h1 className="font-semibold text-foreground">
                                {query ? `Search results for "${query}"` : "Browse Tools"}
                            </h1>
                            <p className="text-sm text-muted-foreground">
                                {tools.length} results
                            </p>
                        </div>
                    </div>

                    <div id="results" className="@container">
                        <hr className="my-4" />
                        <div className="mx-auto w-full grow grid gap-4 grid-cols-1 @md:grid-cols-2 @lg:grid-cols-3">
                            {tools.map((tool) => {
                                return (<div key={tool._id}>
                                    <Link href={`/tool-scout/tools/${tool.slug}`} className="p-1">
                                        <Card className="rounded-2xl backdrop-blur backdrop-saturate bg-opacity-75 bg-white-300 border-0" variant="glass">
                                            <CardHeader className="p-2">
                                                <div className="flex flex-col w-full aspect-video overflow-hidden bg-gray-100 dark:bg-slate-800 rounded-lg h-32 sm:h-36">
                                                    <div className="relative flex items-center justify-center flex-shrink-0 h-full group">
                                                        <LazyImage className="w-9/10 sm:w-10/12 lg:w-9/10 xl:w-10/12 h-auto rounded-lg shadow-md mx-auto object-cover object-left-top transition ease-in-out duration-300"
                                                            width={350}
                                                            height={200}
                                                            src={tool.coverImage} alt={tool.name} />
                                                        <div className="absolute inset-0 transition duration-200 bg-gray-900 opacity-0 rounded-2xl group-hover:opacity-60"></div>
                                                    </div>
                                                </div>
                                            </CardHeader>
                                            <CardContent>
                                                <div className="w-full text-xl font-semibold mb-2 inline-flex gap-2 justify-between items-center flex-wrap" title={tool.name}>
                                                    {tool.name}
                                                    <Badge variant="default_light" size="sm" className="ml-auto">{tool.pricing_type}</Badge>
                                                </div>

                                                <div className="inline-flex flex-wrap gap-2 w-full items-center justify-start mt-2">
                                                    {tool.categories?.map((category, index) => {
                                                        return <Badge key={category.slug + "_" + index} variant="success_light" size="sm" className="text-xs px-1 leading-4 gap-1">
                                                            <Hash className="inline-block w-3 h-3" />
                                                            {category.name}
                                                        </Badge>
                                                    })}
                                                </div>
                                            </CardContent>
                                        </Card>
                                    </Link>
                                </div>)
                            })}
                        </div>
                    </div>
                </TracingBeam>

            </main>
            <aside id="filter" className="max-w-96 grow w-auto sticky top-24 px-4 hidden md:block">
                <div className="w-full flex flex-col space-y-2 text-center sm:text-left mb-5">
                    <h4 className="text-lg font-semibold text-foreground mb-2">
                        Filter Tools
                    </h4>
                    <p className="text-sm text-muted-foreground">
                        Filter Tools by category, pricing, and more.
                    </p>
                    <div className="mb-4">
                        <p className="text-base font-semibold text-muted-foreground mb-4">
                            By Categories
                        </p>
                        <div className="flex flex-wrap gap-2">
                            <FilterButton
                                active={filter.category === "all"}
                                filterKey="category"
                                filterValue="all"
                            >
                                All
                            </FilterButton>
                            {categories.map((category) => (
                                <FilterButton
                                    key={category.slug}
                                    size="sm"
                                    className="cursor-pointer"
                                    filterKey="category"
                                    filterValue={category.slug}
                                    active={filter.category === category.slug}

                                >
                                    {category.name.split("_").join(" ")}
                                </FilterButton>
                            ))}
                        </div>
                    </div>
                </div>
                <div className="mb-4">
                    <p className="text-base font-semibold text-slate-600 mb-4">
                        By Pricing
                    </p>
                    <div className="flex flex-wrap gap-2">
                        {pricing_types.map((pricing_type) => (
                            <FilterButton
                                key={pricing_type}
                                size="sm"
                                className="cursor-pointer"
                                filterKey="pricing_type"
                                filterValue={pricing_type}
                                active={filter?.pricing_type === pricing_type}
                            >
                                {pricing_type.split("_").join(" ")}
                            </FilterButton>
                        ))}
                    </div>
                </div>
            </aside>
        </div>

    </>)

}
