// _legacy/at_alias/components/ui/input.tsx
"use client";
import * as React from "react";

import { cn } from "@/lib/utils";
import { type VariantProps, cva } from "class-variance-authority";

const inputVariants = cva(
  "flex h-10 w-full rounded-md bg-input/60 dark:bg-input/30  border-input px-3 py-2 text-sm font-medium file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:bg-input/50 disabled:cursor-not-allowed disabled:opacity-50 disabled:border-input disabled:bg-input invalid:ring-red-500",
  {
    variants: {
      variant: {
        default: "border border-input focus:border-primary border-solid",
        outline: "border border-solid bg-slate-100 dark:bg-neutral-800",
        ghost:
          "border border-solid border-transparent bg-gray-200/40 dark:bg-gray-800 text-gray-900 dark:text-gray-200 dark:border-gray-700  focus:border-primary/70 dark:focus:border-primary/70",
        border: "border-2 focus:border-primary/70 border-solid",
        glass:
          "bg-white/75 dark:bg-white/5 backdrop-blur-lg border border-slate-500/10 dark:border-border/70 focus:border-primary/70",
      },
      rounded: {
        default: "rounded-md",
        sm: "rounded-sm",
        lg: "rounded-3xl",
        full: "rounded-full",
        none: "rounded-none",
      },
      "custom-size": {
        sm: "h-8 text-xs",
        md: "h-10 text-sm",
        lg: "h-12 text-base",
        xl: "h-14 text-lg",
      },
    },
    defaultVariants: {
      variant: "default",
      rounded: "default",
    },
  }
);
export interface InputProps
  // HTMLInputElement,
  //   React.ComponentProps<"input">,
  extends React.InputHTMLAttributes<HTMLInputElement>,
    VariantProps<typeof inputVariants> {}

const Input = React.forwardRef<HTMLInputElement, InputProps>(
  ({ className, variant, type, rounded, ...props }, ref) => {
    return (
      <input
        type={type}
        className={cn(
          inputVariants({
            variant,
            className,
            rounded,
            "custom-size": props["custom-size"],
          })
        )}
        ref={ref}
        {...props}
      />
    );
  }
);
Input.displayName = "Input";

export { Input };

// src/lib/components/ui/input/input.svelte
<script lang="ts">
import type { HTMLInputAttributes, HTMLInputTypeAttribute } from "svelte/elements";
import { cn, type WithElementRef } from "$lib/utils.js";

type InputType = Exclude<HTMLInputTypeAttribute, "file">;

type Props = WithElementRef<
	Omit<HTMLInputAttributes, "type"> &
		({ type: "file"; files?: FileList } | { type?: InputType; files?: undefined })
>;

let {
	ref = $bindable(null),
	value = $bindable(),
	type,
	files = $bindable(),
	class: className,
	"data-slot": dataSlot = "input",
	...restProps
}: Props = $props();

/**
 * Input: editorial text field.
 *   - Card background with a --border-strong edge
 *   - 44px height (DESIGN.md text-input)
 *   - 8px radius (md)
 *   - Focus thickens border to 2px ink; no glow halo
 *   - Inter at body-md, +0.16px tracking
 */
const base = [
	"flex h-10 w-full min-w-0 px-4 py-2 outline-none",
	"font-sans text-sm tracking-[0.01em]",
	"bg-card text-foreground placeholder:text-muted-foreground",
	"border border-border-control rounded-xl",
	"transition-[border-color,box-shadow] duration-150",
	"focus-visible:border-primary focus-visible:shadow-[inset_0_0_0_1px_var(--primary)]",
	"aria-invalid:border-destructive aria-invalid:focus-visible:shadow-[inset_0_0_0_1px_var(--destructive)]",
	"disabled:bg-background disabled:text-muted-foreground disabled:cursor-not-allowed disabled:opacity-70",
	"file:inline-flex file:h-7 file:items-center file:rounded-pill file:border-0",
	"file:bg-primary file:text-primary-foreground file:px-3 file:mr-3 file:text-xs file:font-medium",
	"dark:bg-card/60"
].join(" ");
</script>

{#if type === "file"}
	<input
		bind:this={ref}
		data-slot={dataSlot}
		class={cn(base, className)}
		type="file"
		bind:files
		bind:value
		{...restProps}
	/>
{:else}
	<input
		bind:this={ref}
		data-slot={dataSlot}
		class={cn(base, className)}
		{type}
		bind:value
		{...restProps}
	/>
{/if}
