// @/components/ui/input.tsx
import * as React from "react"

import { cn } from "@/lib/utils"
import { VariantProps, cva } from "class-variance-authority"

const inputVarinats = cva(
  "flex h-10 w-full rounded-md border-input bg-background px-3 py-2 text-sm font-medium  file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50 disabled:border-slate-100 invalid:ring-red-500"
  ,{
  variants: {
    variant: {
      default: "border-input",
      outline: "border-input",
      ghost: "border border-solid border-transparent bg-slate-100 dark:bg-slate-900 text-slate-900 dark:text-slate-200 dark:border-slate-700  focus:border-primary/70",
      fluid: "border border-solid border-transparent bg-slate-100 dark:bg-slate-900 text-slate-900 dark:text-slate-200 dark:border-slate-700  focus:border-primary/70",
      border:" border-2 focus:border-primary/70 border-solid"
    },
    rounded: {
      default: "rounded-md",
      sm: "rounded-sm",
      lg: "rounded-3xl",
      full: "rounded-full",
      none: "rounded-none",
    },
  },
  defaultVariants: {
    variant: "default",
  },
})
export interface InputProps
  extends React.InputHTMLAttributes<HTMLInputElement>,
  VariantProps<typeof inputVarinats>{}

const Input = React.forwardRef<HTMLInputElement, InputProps>(
  ({ className,variant, type, ...props }, ref) => {
    return (
      <input
        type={type}
        className={cn(inputVarinats({ variant, className }))}

        ref={ref}
        {...props}
      />
    )
  }
)
Input.displayName = "Input"

export { Input }

// src/lib/components/ui/input/input.svelte
<script lang="ts">
import type { HTMLInputAttributes, HTMLInputTypeAttribute } from "svelte/elements";
import { cn, type WithElementRef } from "$lib/utils.js";

type InputType = Exclude<HTMLInputTypeAttribute, "file">;

type Props = WithElementRef<
	Omit<HTMLInputAttributes, "type"> &
		({ type: "file"; files?: FileList } | { type?: InputType; files?: undefined })
>;

let {
	ref = $bindable(null),
	value = $bindable(),
	type,
	files = $bindable(),
	class: className,
	"data-slot": dataSlot = "input",
	...restProps
}: Props = $props();

/**
 * Input: editorial text field.
 *   - Card background with a --border-strong edge
 *   - 44px height (DESIGN.md text-input)
 *   - 8px radius (md)
 *   - Focus thickens border to 2px ink; no glow halo
 *   - Inter at body-md, +0.16px tracking
 */
const base = [
	"flex h-10 w-full min-w-0 px-4 py-2 outline-none",
	"font-sans text-sm tracking-[0.01em]",
	"bg-card text-foreground placeholder:text-muted-foreground",
	"border border-border-control rounded-xl",
	"transition-[border-color,box-shadow] duration-150",
	"focus-visible:border-primary focus-visible:shadow-[inset_0_0_0_1px_var(--primary)]",
	"aria-invalid:border-destructive aria-invalid:focus-visible:shadow-[inset_0_0_0_1px_var(--destructive)]",
	"disabled:bg-background disabled:text-muted-foreground disabled:cursor-not-allowed disabled:opacity-70",
	"file:inline-flex file:h-7 file:items-center file:rounded-pill file:border-0",
	"file:bg-primary file:text-primary-foreground file:px-3 file:mr-3 file:text-xs file:font-medium",
	"dark:bg-card/60"
].join(" ");
</script>

{#if type === "file"}
	<input
		bind:this={ref}
		data-slot={dataSlot}
		class={cn(base, className)}
		type="file"
		bind:files
		bind:value
		{...restProps}
	/>
{:else}
	<input
		bind:this={ref}
		data-slot={dataSlot}
		class={cn(base, className)}
		{type}
		bind:value
		{...restProps}
	/>
{/if}
