// src/lib/components/extended/router-card.svelte
<script lang="ts">
	import { Badge } from "$lib/components/ui/badge";
	import { cn } from "$lib/utils";
	import ArrowRight from "@lucide/svelte/icons/arrow-right";
	import ArrowUpRight from "@lucide/svelte/icons/arrow-up-right";
	import Lock from "@lucide/svelte/icons/lock";
	import type { Component } from "svelte";

	type Props = {
		href: string;
		title: string;
		description: string;
		external?: boolean;
		Icon: Component<Record<string, unknown>>;
		disabled?: boolean;
		class?: string;
		style?: string;
	};

	let {
		href,
		title,
		description,
		external = false,
		Icon,
		disabled = false,
		class: className,
		style
	}: Props = $props();
</script>

<a
	href={disabled ? "#" : href}
	target={external && !disabled ? "_blank" : "_self"}
	rel={external && !disabled ? "noopener noreferrer" : undefined}
	{style}
	class={cn(
		"group bg-card border-border/50 relative flex flex-col justify-between overflow-hidden rounded-xl border p-6 transition-all duration-300",
		!disabled &&
			"hover:border-primary/20 hover:shadow-primary/5 hover:-translate-y-1 hover:shadow-lg",
		disabled && "bg-muted/20 cursor-not-allowed opacity-60 grayscale",
		className
	)}
	aria-disabled={disabled}
>
	<div class="flex w-full items-start justify-between">
		<div
			class={cn(
				"border-border/50 bg-muted/50 flex size-10 items-center justify-center rounded-lg border transition-colors",
				!disabled && "group-hover:bg-primary/10 group-hover:border-primary/20"
			)}
		>
			<Icon
				class={cn(
					"text-muted-foreground size-5 transition-colors",
					!disabled && "group-hover:text-primary"
				)}
			/>
		</div>

		<div
			class="text-muted-foreground/50 group-hover:text-primary transition-transform duration-300 group-hover:-translate-y-0.5 group-hover:translate-x-0.5"
		>
			{#if disabled}
				<Lock class="size-5" />
			{:else if external}
				<ArrowUpRight class="size-5" />
			{:else}
				<ArrowRight class="size-5" />
			{/if}
		</div>
	</div>

	<div class="mt-4 flex flex-col gap-2">
		<div class="flex items-center gap-2">
			<h3 class="text-foreground font-semibold tracking-tight">{title}</h3>
			{#if disabled}
				<Badge
					variant="secondary"
					class="h-5 px-1.5 text-[10px] font-medium tracking-wide uppercase"
				>
					Soon
				</Badge>
			{/if}
		</div>
		<p class="text-muted-foreground text-sm leading-relaxed text-balance">{description}</p>
	</div>

	{#if !disabled}
		<span
			class="via-primary/40 absolute inset-x-0 bottom-0 h-px bg-linear-to-r from-transparent to-transparent opacity-0 transition-opacity duration-300 group-hover:opacity-100"
		></span>
		<span
			class="via-primary/20 absolute inset-x-0 bottom-0 h-[2px] bg-linear-to-r from-transparent to-transparent opacity-0 blur-sm transition-opacity duration-300 group-hover:opacity-100"
		></span>
	{/if}
</a>

// @/components/extended/router-card.tsx
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";
import { ArrowRight, ArrowUpRight } from "lucide-react";
import Link from "next/link";

type RouterCardLink = {
  href: string;
  title: string;
  description: string;
  external?: boolean;
  Icon: React.FC<React.SVGProps<SVGSVGElement>>;
  disabled?: boolean;
  // preserveParams?: boolean;
};

interface RouterCardProps extends RouterCardLink {
  style?: React.CSSProperties;
}

function RouterCard({
  href,
  title,
  description,
  external = false,
  Icon,
  style,
  disabled,
  // preserveParams,
}: RouterCardProps) {
  return (
    <Link
      href={href}
      className={cn(
        "@max-lg:col-span-full bg-card block border p-4 rounded-lg shadow-md text-card-foreground transition-all",
        "group flex flex-col justify-between gap-2 animate-in popup backdrop-blur-2xl shadow-sm relative",
        "hover:-translate-1",
        disabled ? "pointer-events-none cursor-not-allowed" : ""
      )}
      target={external ? "_blank" : "_self"}
      rel={external ? "noopener noreferrer" : undefined}
      style={style}
    >
      <div className="flex w-full flex-row gap-2 items-center justify-center">
        <div className="flex justify-center items-center size-10 rounded-full bg-muted font-bold text-lg shrink-0">
          <Icon className="size-5 text-primary inline-block" />
        </div>
        <div className="flex-auto">
          <h5 className="not-prose mb-1 text-sm font-medium">{title}</h5>
          {disabled ? (
            <Badge
              size="sm"
              className="text-xs text-muted-foreground prose-no-margin"
            >
              Maintenance
            </Badge>
          ) : null}
        </div>
      </div>
      <p className="max-w-[30ch] text-xs text-muted-foreground prose-no-margin">
        {description}
      </p>
      <p className="text-xs whitespace-nowrap font-semibold text-primary/80 transition-all group-hover:text-primary group-hover:translate-x-1 motion-reduce:transform-none  [&_svg]:size-4 [&_svg]:ml-1 [&_svg]:inline-block">
        Go to {title}
        {external ? <ArrowUpRight /> : <ArrowRight />}
      </p>
          {/* Decorative elements */}
        <span className="from-primary/0 via-primary to-primary/0 absolute -bottom-px left-1/2 h-px w-1/2 -translate-x-1/2 bg-gradient-to-r opacity-60"/>
        <span className="absolute inset-0 bg-[radial-gradient(30%_5%_at_50%_100%,hsl(var(--primary)/0.15)_0%,transparent_100%)] opacity-60"/>
    </Link>
  );
}

RouterCard.displayName = "RouterCard";

export { RouterCard, type RouterCardLink, type RouterCardProps };
