// _legacy/app/scout/tools/[slug]/page.tsx
import AdUnit from "@/components/common/adsense";
import ShareButton from "@/components/common/share-button";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import Navbar from "app/layouts/navbar-dynamic";
import {
  getPublicToolBySlug,
  getRatingsAndReviews,
  getSimilarTools,
  getToolMetaBySlug,
  postRatingAndReview,
  toggleBookmark,
} from "app/scout/lib/actions";
import { getAverageRating } from "app/scout/lib/utils";
import {
  ArrowUpRight,
  BarChart3,
  Calendar,
  CheckCircle2,
  Eye,
  Globe,
  Hash,
  MessageSquare,
  Share2,
  ShieldCheck,
  Sparkles,
  Star,
  Zap
} from "lucide-react";
import type { Metadata, ResolvingMetadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Suspense } from "react";
import MarkdownView from "src/components/markdown/view";
import { getImages } from "src/lib/scout";
import { RatingTypeWithId } from "src/models/tool-rating";
import { formatNumber } from "src/utils/formaters";
import { getSession } from "~/auth/server";
import { PublicToolTypeWithId } from "~/models/tool";

// Components
import { marketwiseLink } from "src/utils/string";
import { BookMarkButton } from "./bookmark";
import { PostReview } from "./post-review";
import RatingComponent from "./rating";
import SimilarTools from "./similar-tools";

// Type Definitions
interface Category {
  name: string;
  slug: string;
}

type Tool = PublicToolTypeWithId & {
  categories: Category[];
}

type Props = {
  params: Promise<{ slug: string }>;
};

// Metadata Generation
export async function generateMetadata(
  props: Props,
  parent: ResolvingMetadata
): Promise<Metadata> {
  const params = await props.params;
  const tool = await getToolMetaBySlug(params.slug);

  if (!tool) return {};

  return {
    title: `${tool.name} - Review & Pricing`,
    description: tool.description.substring(0, 160),
    keywords:
      tool.tags?.join(", ") ||
      tool.categories.map((category: Category) => category.name).join(", "),
    openGraph: {
      images: [tool.coverImage, tool?.bannerImage || tool.coverImage],
      title: tool.name,
      description: tool.description.substring(0, 160),
      url: `${process.env.NEXT_PUBLIC_WEBSITE_URL || "https://nexonauts.com"}/scout/tools/${tool.slug}`,
    },
    category: tool.categories.map((category: Category) => category.name).join(", "),
  };
}

const cache = new Map<string, boolean>();

export default async function ToolPage(props: Props) {
  const params = await props.params;

  // Fetch Tool Data
  const tool = (await getPublicToolBySlug(
    params.slug,
    cache.get(params.slug) || false
  )) as Tool | null;

  if (!tool) {
    return notFound();
  }

  cache.set(params.slug, true);

  // Fetch Context Data
  const session = await getSession();
  const ratings = (await getRatingsAndReviews(tool._id)) as RatingTypeWithId[];
  const similarTools = await getSimilarTools(tool.categories);
  const { bannerURL } = getImages(tool.link);

  const averageRating = getAverageRating(ratings || []);
  const reviewCount = ratings.length;

  // Server Action for Ratings
  async function publishRating(data: { rating: number; comment: string }) {
    "use server";
    try {
      if (!session || !session?.user) {
        throw new Error("You need to be logged in to rate a tool");
      }
      const rating = await postRatingAndReview({
        toolId: tool!._id,
        userId: session.user.id,
        rating: data.rating,
        comment: data.comment,
      });
      return rating;
    } catch (e) {
      console.error(e);
      throw e;
    }
  }

  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Navbar />

      {/* Subtle Background */}
      <div className="fixed inset-0 z-0 pointer-events-none">
        <div className="absolute inset-0 bg-[linear-gradient(to_right,#80808008_1px,transparent_1px),linear-gradient(to_bottom,#80808008_1px,transparent_1px)] bg-[size:24px_24px]" />
        <div className="absolute top-20 left-1/4 w-[500px] h-[500px] bg-primary/5 blur-[150px] rounded-full" />
      </div>

      <div className="relative z-10 w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-24 pb-16">

        {/* Breadcrumb */}
        <nav className="flex items-center gap-2 text-sm text-muted-foreground mb-6">
          <Link href="/scout/browse" className="hover:text-foreground transition-colors">Browse</Link>
          <span>/</span>
          <span className="text-foreground">{tool.name}</span>
        </nav>

        {/* Compact Header */}
        <div className="flex flex-col md:flex-row gap-5 mb-8 items-start">
          <div className="relative w-16 h-16 md:w-20 md:h-20 rounded-xl overflow-hidden border border-border/50 shadow-md shrink-0 bg-muted">
            <Image
              src={tool.coverImage}
              alt={tool.name}
              fill
              className="object-cover"
            />
          </div>

          <div className="flex-1 space-y-3">
            <div className="flex flex-wrap items-center gap-3">
              <h1 className="text-3xl md:text-4xl font-bold tracking-tight">{tool.name}</h1>
              {tool.verified && (
                <Badge className="px-2 py-1 rounded-md bg-emerald-500/10 border-emerald-500/20 text-emerald-600 text-xs font-semibold">
                  <CheckCircle2 className="w-3 h-3 mr-1" />
                  Verified
                </Badge>
              )}
            </div>

            <div className="flex flex-wrap items-center gap-3 text-sm text-muted-foreground">
              <div className="flex items-center gap-1.5">
                <Star className="w-4 h-4 text-amber-500 fill-amber-500" />
                <span className="font-semibold text-foreground">{averageRating}</span>
                <span>({reviewCount})</span>
              </div>
              <span className="w-1 h-1 rounded-full bg-border" />
              <div className="flex items-center gap-1.5">
                <Eye className="w-4 h-4" />
                <span className="font-medium text-foreground">{formatNumber(tool.views)}</span>
              </div>
              <span className="w-1 h-1 rounded-full bg-border" />
              <Badge variant="secondary" className="rounded-md px-2 py-0.5 text-xs capitalize bg-muted/50">
                {tool.pricing_type}
              </Badge>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">

          {/* LEFT COLUMN: Content */}
          <main className="lg:col-span-8 space-y-10">

            {/* Hero Image */}
            <div className="relative w-full aspect-video rounded-xl overflow-hidden border border-border/50 shadow-lg bg-muted">
              <Image
                fill
                src={bannerURL || tool.coverImage}
                alt={`${tool.name} screenshot`}
                className="object-cover"
                priority
                sizes="(max-width: 1024px) 100vw, 700px"
              />
            </div>

            {/* About Section */}
            <section className="space-y-4">
              <div className="flex items-center gap-2 pb-3 border-b border-border/40">
                <Zap className="w-5 h-5 text-primary" />
                <h2 className="text-xl font-semibold">About</h2>
              </div>
              <div className="prose prose-sm prose-zinc dark:prose-invert max-w-none prose-p:text-muted-foreground prose-headings:font-semibold prose-a:text-primary">
                <MarkdownView>{tool.description}</MarkdownView>
              </div>

              {/* Categories */}
              {tool.categories.length > 0 && (
                <div className="pt-4">
                  <div className="flex flex-wrap gap-2">
                    {tool.categories.map((category, i) => (
                      <Link
                        key={i}
                        href={`/scout/browse?category=${category.slug}`}
                        className="px-3 py-1.5 rounded-full border border-border/50 bg-card/50 text-sm text-muted-foreground hover:text-foreground hover:border-primary/50 hover:bg-primary/5 transition-all flex items-center gap-1.5"
                      >
                        <Hash className="w-3 h-3 opacity-50" />
                        {category.name}
                      </Link>
                    ))}
                  </div>
                </div>
              )}
            </section>

            {/* TOP IN-CONTENT AD */}
            <div className="w-full min-h-[250px] rounded-xl border border-border/40 bg-card/30 backdrop-blur-sm flex flex-col items-center justify-center overflow-hidden relative">
              <div className="absolute inset-0 bg-[radial-gradient(#00000008_1px,transparent_1px)] bg-size-[20px_20px]" />
              <div className="absolute top-3 left-1/2 -translate-x-1/2 px-3 py-1 rounded-full bg-muted/70 backdrop-blur-sm">
                <span className="text-[9px] font-bold text-muted-foreground uppercase tracking-widest">
                  Sponsored
                </span>
              </div>
              <div className="relative z-10 w-full flex items-center justify-center py-6">
                <AdUnit adSlot="in_feed" />
              </div>
            </div>

            {/* Reviews Section */}
            <section id="reviews" className="pt-8 border-t border-border/40">
              <div className="flex items-center gap-2 mb-6">
                <MessageSquare className="w-5 h-5 text-primary" />
                <h2 className="text-xl font-semibold">Reviews</h2>
              </div>

              <Tabs defaultValue="all" className="w-full">
                <TabsList className="bg-muted/50 border border-border/50 mb-6">
                  <TabsTrigger value="all">All ({ratings.length})</TabsTrigger>
                  <TabsTrigger value="write">Write Review</TabsTrigger>
                </TabsList>

                <TabsContent value="all" className="space-y-5">
                  {ratings.length > 0 ? (
                    <div className="space-y-5">
                      {ratings.map((rating) => (
                        <RatingComponent key={rating._id} rating={rating} />
                      ))}
                    </div>
                  ) : (
                    <div className="text-center py-12 bg-muted/20 rounded-xl border border-dashed border-border/50">
                      <Star className="w-10 h-10 text-muted-foreground/30 mx-auto mb-3" />
                      <p className="text-sm text-muted-foreground">No reviews yet. Be the first!</p>
                    </div>
                  )}
                </TabsContent>

                <TabsContent value="write">
                  {session?.user ? (
                    <PostReview tool={tool} postRatingAndReview={publishRating} />
                  ) : (
                    <div className="flex flex-col items-center justify-center py-12 bg-muted/20 rounded-xl border border-border/50">
                      <ShieldCheck className="w-10 h-10 text-muted-foreground/40 mb-4" />
                      <p className="mb-4 text-sm text-muted-foreground">Sign in to leave a review</p>
                      <Button asChild variant="outline" size="sm">
                        <Link href={`/auth/sign-in?callbackUrl=/scout/tools/${tool.slug}`}>Sign In</Link>
                      </Button>
                    </div>
                  )}
                </TabsContent>
              </Tabs>
            </section>

            {/* BOTTOM MULTIPLEX AD */}
            <div className="pt-8">
              <div className="flex items-center gap-3 mb-4">
                <Sparkles className="w-4 h-4 text-primary" />
                <span className="text-xs font-bold text-muted-foreground uppercase tracking-widest">
                  Related Tools
                </span>
                <div className="h-px flex-1 bg-border/50" />
              </div>
              <div className="min-h-[280px] w-full bg-card/40 backdrop-blur-sm rounded-xl border border-border/40 flex items-center justify-center p-4 overflow-hidden relative">
                <div className="absolute inset-0 bg-[radial-gradient(#00000005_1px,transparent_1px)] [background-size:16px_16px]" />
                <div className="relative z-10">
                  <AdUnit adSlot="multiplex_horizontal" />
                </div>
              </div>
            </div>

          </main>

          {/* RIGHT COLUMN: Sticky Sidebar */}
          <aside className="lg:col-span-4 space-y-6">
            <div className="sticky top-24 space-y-6">

              {/* CTA Card */}
              <div className="rounded-xl border border-border/50 bg-card/80 backdrop-blur-sm shadow-lg p-5 space-y-4">

                <div className="flex justify-between items-baseline pb-4 border-b border-border/50">
                  <span className="text-sm font-medium text-muted-foreground">Pricing</span>
                  <span className="text-2xl font-bold capitalize">{tool.pricing_type}</span>
                </div>

                <div className="space-y-3">
                  <Button
                    asChild
                    size="lg"
                    className="w-full h-11 text-base font-semibold shadow-md"
                  >
                    <Link href={marketwiseLink(tool.link,{
                      utm_medium: "referral",
                      utm_campaign: "tool_cta_button",
                      
                    })} target="_blank" rel="noopener noreferrer">
                      Visit Website
                      <ArrowUpRight className="ml-2 w-4 h-4" />
                    </Link>
                  </Button>

                  <div className="grid grid-cols-2 gap-2">
                    <BookMarkButton
                      tool={tool}
                      toggleBookmark={toggleBookmark}
                      userId={session?.user?.id || null}
                    />
                    <ShareButton
                      data={{
                        title: `Check out ${tool.name} on Nexonauts`,
                        url: `https://nexonauts.com/scout/tools/${tool.slug}`,
                      }}
                      variant="outline"
                      className="w-full justify-center"
                    >
                      <Share2 className="w-4 h-4 mr-2" />
                      Share
                    </ShareButton>
                  </div>
                </div>

                <Separator className="my-4" />

                {/* Stats */}
                <div className="space-y-3">
                  <h4 className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Details</h4>
                  <div className="space-y-3 text-sm">
                    <div className="flex items-center justify-between">
                      <span className="text-muted-foreground flex items-center gap-2">
                        <Globe className="w-3.5 h-3.5" /> Website
                      </span>
                      <span className="font-medium truncate max-w-[150px]" title={tool.link}>
                        {new URL(tool.link).hostname}
                      </span>
                    </div>
                    <div className="flex items-center justify-between">
                      <span className="text-muted-foreground flex items-center gap-2">
                        <BarChart3 className="w-3.5 h-3.5" /> Views
                      </span>
                      <span className="font-medium">{formatNumber(tool.views)}</span>
                    </div>
                    <div className="flex items-center justify-between">
                      <span className="text-muted-foreground flex items-center gap-2">
                        <Calendar className="w-3.5 h-3.5" /> Added
                      </span>
                      <span className="font-medium text-xs">
                        {new Date(tool?.createdAt || "").toLocaleDateString("en-US", {
                          month: "short",
                          day: "numeric",
                          year: "numeric",
                        })}
                      </span>
                    </div>
                  </div>
                </div>
              </div>

              {/* SIDEBAR AD (300x250) */}
              <div className="w-full min-h-[280px] rounded-xl bg-card/40 backdrop-blur-sm border border-border/40 flex flex-col overflow-hidden">
                <div className="w-full py-2 bg-muted/50 border-b border-border/40 text-center">
                  <span className="text-[9px] font-bold text-muted-foreground uppercase tracking-widest">
                    Sponsored
                  </span>
                </div>
                <div className="flex-1 flex items-center justify-center p-4">
                  <AdUnit adSlot="display-square" />
                </div>
              </div>

              {/* Similar Tools */}
              <div className="rounded-xl border border-border/50 bg-card/50 backdrop-blur-sm p-5">
                <h3 className="font-semibold mb-4 text-base">Similar Tools</h3>
                <Suspense fallback={
                  <div className="space-y-3">
                    {[1, 2, 3].map(i => (
                      <div key={i} className="h-16 animate-pulse bg-muted/50 rounded-lg" />
                    ))}
                  </div>
                }>
                  <SimilarTools tools={similarTools} toolName={tool.name} />
                </Suspense>
              </div>

              {/* SECOND SIDEBAR AD */}
              <div className="w-full min-h-[280px] rounded-xl bg-card/40 backdrop-blur-sm border border-border/40 flex flex-col overflow-hidden">
                <div className="w-full py-2 bg-muted/50 border-b border-border/40 text-center">
                  <span className="text-[9px] font-bold text-muted-foreground uppercase tracking-widest">
                    Sponsored
                  </span>
                </div>
                <div className="flex-1 flex items-center justify-center p-4">
                  <AdUnit adSlot="display-square" />
                </div>
              </div>

            </div>
          </aside>

        </div>
      </div>
    </div>
  );
}

// src/routes/scout/tools/[slug]/+page.svelte
<script lang="ts">
	import ToolCard from "$lib/components/scout/tool-card.svelte";
	import { Badge } from "$lib/components/ui/badge";
	import { Button } from "$lib/components/ui/button";
	import { Input } from "$lib/components/ui/input";
	import { Textarea } from "$lib/components/ui/textarea";
	import * as Tabs from "$lib/components/ui/tabs";
	import { getImages } from "$lib/scout";
	import { cn } from "$lib/utils";
	import { appConfig } from "@root/project.config";
	import ArrowUpRight from "@lucide/svelte/icons/arrow-up-right";
	import BarChart3 from "@lucide/svelte/icons/bar-chart-3";
	import Calendar from "@lucide/svelte/icons/calendar";
	import CheckCircle2 from "@lucide/svelte/icons/check-circle-2";
	import Eye from "@lucide/svelte/icons/eye";
	import Globe from "@lucide/svelte/icons/globe";
	import Hash from "@lucide/svelte/icons/hash";
	import Heart from "@lucide/svelte/icons/heart";
	import MessageSquare from "@lucide/svelte/icons/message-square";
	import Share2 from "@lucide/svelte/icons/share-2";
	import ShieldCheck from "@lucide/svelte/icons/shield-check";
	import Sparkles from "@lucide/svelte/icons/sparkles";
	import Star from "@lucide/svelte/icons/star";
	import Zap from "@lucide/svelte/icons/zap";
	import { toast } from "svelte-sonner";
	import { formatNumber } from "src/utils/formaters";
	import { decodeHTMLEntities, marketwiseLink } from "src/utils/string";

	let { data, form } = $props();

	const images = $derived(getImages(data.tool.link));
	const averageRatingLabel = $derived(data.averageRating.toFixed(1));
	const formMessage = $derived(form?.message ?? "");
	let activeTab = $state("all");
	$effect(() => {
		activeTab = form?.action === "review" ? "write" : "all";
	});

	async function shareTool() {
		const url = `${appConfig.url}/scout/tools/${data.tool.slug}`;
		try {
			if (navigator.share) {
				await navigator.share({ title: data.tool.name, url });
			} else {
				await navigator.clipboard.writeText(url);
				toast.success("Tool link copied");
			}
		} catch {
			/* user dismissed */
		}
	}

	function hostnameFor(url: string) {
		try {
			return new URL(url).hostname;
		} catch {
			return url;
		}
	}
</script>

<div class="min-h-screen bg-background">
	<div class="pointer-events-none fixed inset-0 z-0">
		<div
			class="absolute inset-0 bg-[linear-gradient(to_right,#80808008_1px,transparent_1px),linear-gradient(to_bottom,#80808008_1px,transparent_1px)] bg-[size:24px_24px]"
		></div>
		<div class="absolute top-20 left-1/4 h-[500px] w-[500px] rounded-full bg-primary/5 blur-[150px]"></div>
	</div>

	<div class="relative z-10 mx-auto w-full max-w-7xl px-4 pt-24 pb-16 sm:px-6 lg:px-8">
		<nav class="mb-6 flex items-center gap-2 text-sm text-muted-foreground">
			<a href="/scout/browse" class="transition-colors hover:text-foreground">Browse</a>
			<span>/</span>
			<span class="text-foreground">{decodeHTMLEntities(data.tool.name)}</span>
		</nav>

		<div class="mb-8 flex flex-col items-start gap-5 md:flex-row">
			<div class="relative h-16 w-16 shrink-0 overflow-hidden rounded-xl border border-border/50 bg-muted shadow-md md:h-20 md:w-20">
				<img src={data.tool.coverImage} alt={decodeHTMLEntities(data.tool.name)} class="h-full w-full object-cover" />
			</div>

			<div class="flex-1 space-y-3">
				<div class="flex flex-wrap items-center gap-3">
					<h1 class="text-3xl font-bold tracking-tight md:text-4xl">
						{decodeHTMLEntities(data.tool.name)}
					</h1>
					{#if data.tool.verified}
						<Badge class="rounded-md border-emerald-500/20 bg-emerald-500/10 px-2 py-1 text-xs font-semibold text-emerald-600">
							<CheckCircle2 class="mr-1 h-3 w-3" />
							Verified
						</Badge>
					{/if}
				</div>

				<div class="flex flex-wrap items-center gap-3 text-sm text-muted-foreground">
					<div class="flex items-center gap-1.5">
						<Star class="h-4 w-4 fill-amber-500 text-amber-500" />
						<span class="font-semibold text-foreground">{averageRatingLabel}</span>
						<span>({data.reviewCount})</span>
					</div>
					<span class="h-1 w-1 rounded-full bg-border"></span>
					<div class="flex items-center gap-1.5">
						<Eye class="h-4 w-4" />
						<span class="font-medium text-foreground">{formatNumber(data.tool.views)}</span>
					</div>
					<span class="h-1 w-1 rounded-full bg-border"></span>
					<Badge variant="secondary" class="rounded-md bg-muted/50 px-2 py-0.5 text-xs capitalize">
						{data.tool.pricing_type}
					</Badge>
				</div>
			</div>
		</div>

		<div class="grid grid-cols-1 gap-8 lg:grid-cols-12">
			<main class="space-y-10 lg:col-span-8">
				<div class="relative aspect-video w-full overflow-hidden rounded-xl border border-border/50 bg-muted shadow-lg">
					<img
						src={images?.bannerURL || data.tool.bannerImage || data.tool.coverImage}
						alt={`${decodeHTMLEntities(data.tool.name)} screenshot`}
						class="h-full w-full object-cover"
					/>
				</div>

				<section class="space-y-4">
					<div class="flex items-center gap-2 border-b border-border/40 pb-3">
						<Zap class="h-5 w-5 text-primary" />
						<h2 class="text-xl font-semibold">About</h2>
					</div>
					<div class="rounded-xl border border-border/50 bg-card/40 p-5 text-sm leading-7 text-muted-foreground backdrop-blur-sm">
						{data.tool.description}
					</div>

					{#if data.tool.categories.length > 0}
						<div class="pt-4">
							<div class="flex flex-wrap gap-2">
								{#each data.tool.categories as category (category.slug)}
									<a
										href={`/scout/browse?category=${category.slug}`}
										class="flex items-center gap-1.5 rounded-full border border-border/50 bg-card/50 px-3 py-1.5 text-sm text-muted-foreground transition-all hover:border-primary/50 hover:bg-primary/5 hover:text-foreground"
									>
										<Hash class="h-3 w-3 opacity-50" />
										{category.name}
									</a>
								{/each}
							</div>
						</div>
					{/if}
				</section>

				<section id="reviews" class="border-t border-border/40 pt-8">
					<div class="mb-6 flex items-center gap-2">
						<MessageSquare class="h-5 w-5 text-primary" />
						<h2 class="text-xl font-semibold">Reviews</h2>
					</div>

					{#if formMessage}
						<div
							class={cn(
								"mb-6 rounded-xl border px-4 py-3 text-sm",
								form?.success
									? "border-emerald-500/30 bg-emerald-500/10 text-emerald-700 dark:text-emerald-300"
									: "border-destructive/30 bg-destructive/10 text-destructive"
							)}
						>
							{formMessage}
						</div>
					{/if}

					<Tabs.Root bind:value={activeTab} class="w-full">
						<Tabs.List class="mb-6 border border-border/50 bg-muted/50">
							<Tabs.Trigger value="all">All ({data.ratings.length})</Tabs.Trigger>
							<Tabs.Trigger value="write">Write Review</Tabs.Trigger>
						</Tabs.List>

						<Tabs.Content value="all" class="space-y-5">
							{#if data.ratings.length > 0}
								<div class="space-y-5">
									{#each data.ratings as rating (rating._id)}
										<div class="rounded-xl border border-border/50 bg-card/30 p-5 backdrop-blur-sm">
											<div class="mb-3 flex items-start justify-between gap-4">
												<div>
													<p class="font-semibold text-foreground">{rating.userId.name}</p>
													<p class="text-xs text-muted-foreground">@{rating.userId.username}</p>
												</div>
												<div class="text-right">
													<div class="flex items-center gap-1 text-amber-500">
														{#each Array.from({ length: 5 }, (_, index) => index + 1) as value (value)}
															<Star
																class={cn(
																	"h-4 w-4",
																	value <= rating.rating ? "fill-current" : "text-muted-foreground/30"
																)}
															/>
														{/each}
													</div>
													<p class="mt-1 text-xs text-muted-foreground">
														{new Date(rating.createdAt ?? "").toLocaleDateString("en-US", {
															month: "short",
															day: "numeric",
															year: "numeric"
														})}
													</p>
												</div>
											</div>
											<p class="text-sm leading-relaxed text-muted-foreground">{rating.comment}</p>
										</div>
									{/each}
								</div>
							{:else}
								<div class="rounded-xl border border-dashed border-border/50 bg-muted/20 py-12 text-center">
									<Star class="mx-auto mb-3 h-10 w-10 text-muted-foreground/30" />
									<p class="text-sm text-muted-foreground">No reviews yet. Be the first.</p>
								</div>
							{/if}
						</Tabs.Content>

						<Tabs.Content value="write">
							{#if data.canReview}
								<form method="POST" action="?/review" class="space-y-4 rounded-xl border border-border/50 bg-card/40 p-5 backdrop-blur-sm">
									<div class="grid gap-4 sm:grid-cols-[140px,1fr] sm:items-start">
										<label for="rating" class="pt-2 text-sm font-medium">Rating</label>
										<Input id="rating" name="rating" type="number" min="1" max="5" step="1" placeholder="1 to 5" required />
									</div>

									<div class="grid gap-4 sm:grid-cols-[140px,1fr] sm:items-start">
										<label for="comment" class="pt-2 text-sm font-medium">Review</label>
										<Textarea
											id="comment"
											name="comment"
											required
											rows={5}
											minlength={10}
											maxlength={500}
											placeholder="What worked well, where does it fit, and who should use it?"
										/>
									</div>

									<div class="flex items-center justify-between gap-3">
										<p class="text-xs text-muted-foreground">Reviews require a signed-in, verified account with a profile.</p>
										<Button type="submit">Publish Review</Button>
									</div>
								</form>
							{:else}
								<div class="rounded-xl border border-border/50 bg-card/40 p-6 text-center backdrop-blur-sm">
									<p class="mb-4 text-sm text-muted-foreground">
										Sign in with a verified account and complete your profile to post reviews.
									</p>
									<Button href={`/auth/sign-in?callbackUrl=/scout/tools/${data.tool.slug}`} variant="outline">
										Sign In
									</Button>
								</div>
							{/if}
						</Tabs.Content>
					</Tabs.Root>
				</section>
			</main>

			<aside class="space-y-6 lg:col-span-4">
				<div class="sticky top-24 space-y-6">
					<div class="space-y-5 rounded-xl border border-border/50 bg-card/80 p-5 shadow-lg backdrop-blur-sm">
						<div class="flex items-baseline justify-between border-b border-border/50 pb-4">
							<span class="text-sm font-medium text-muted-foreground">Pricing</span>
							<span class="text-2xl font-bold capitalize">{data.tool.pricing_type}</span>
						</div>

						<div class="space-y-3">
							<Button
								size="lg"
								class="h-11 w-full text-base font-semibold shadow-md"
								href={marketwiseLink(data.tool.link, {
									utm_source: appConfig.url,
									utm_medium: "referral",
									utm_campaign: "tool_cta_button"
								})}
								target="_blank"
							>
								Visit Website
								<ArrowUpRight class="ml-2 h-4 w-4" />
							</Button>

							<div class="grid grid-cols-2 gap-2">
								<form method="POST" action="?/bookmark">
									<Button variant="outline" type="submit" class="w-full justify-center">
										<Heart class={cn("mr-2 h-4 w-4", data.isBookmarked && "fill-current text-rose-500")} />
										{data.isBookmarked ? "Saved" : "Save"}
									</Button>
								</form>
								<Button variant="outline" class="w-full justify-center" onclick={shareTool}>
									<Share2 class="mr-2 h-4 w-4" />
									Share
								</Button>
							</div>
						</div>

						<div class="flex items-center justify-center gap-2 border-t border-border/50 pt-3 text-xs text-muted-foreground">
							<ShieldCheck class="h-4 w-4 text-emerald-500" />
							Secure referral link tracking
						</div>

						<div class="space-y-3">
							<h4 class="text-xs font-bold tracking-wider text-muted-foreground uppercase">Details</h4>
							<div class="space-y-3 text-sm">
								<div class="flex items-center justify-between gap-4">
									<span class="flex items-center gap-2 text-muted-foreground">
										<Globe class="h-3.5 w-3.5" />
										Website
									</span>
									<span class="max-w-[150px] truncate font-medium" title={data.tool.link}>
										{hostnameFor(data.tool.link)}
									</span>
								</div>
								<div class="flex items-center justify-between">
									<span class="flex items-center gap-2 text-muted-foreground">
										<BarChart3 class="h-3.5 w-3.5" />
										Views
									</span>
									<span class="font-medium">{formatNumber(data.tool.views)}</span>
								</div>
								<div class="flex items-center justify-between">
									<span class="flex items-center gap-2 text-muted-foreground">
										<Calendar class="h-3.5 w-3.5" />
										Added
									</span>
									<span class="text-xs font-medium">
										{new Date(data.tool.createdAt ?? "").toLocaleDateString("en-US", {
											month: "short",
											day: "numeric",
											year: "numeric"
										})}
									</span>
								</div>
							</div>
						</div>
					</div>

					<div class="rounded-xl border border-border/50 bg-card/50 p-5 backdrop-blur-sm">
						<h3 class="mb-4 text-base font-semibold">Similar Tools</h3>
						{#if data.similarTools.length === 0}
							<p class="text-sm text-muted-foreground">No similar tools available.</p>
						{:else}
							<div class="space-y-4">
								{#each data.similarTools as tool (tool._id)}
									<ToolCard {tool} class="border-border/50 bg-card/50 shadow-sm hover:bg-card hover:shadow-md" />
								{/each}
							</div>
						{/if}
					</div>

					<div class="rounded-xl border border-border/40 bg-card/30 p-5 backdrop-blur-sm">
						<div class="mb-3 flex items-center gap-3">
							<Sparkles class="h-4 w-4 text-primary" />
							<span class="text-xs font-bold tracking-widest text-muted-foreground uppercase">
								Scout Insight
							</span>
						</div>
						<p class="text-sm leading-relaxed text-muted-foreground">
							Bookmarking and review posting are now live on this migrated route. Remaining parity work is focused on admin-side moderation flows.
						</p>
					</div>
				</div>
			</aside>
		</div>
	</div>
</div>
