// src/routes/blog/articles/[slug]/+page.svelte
<script lang="ts">
	import PostHeader from "$lib/components/blog/post-header.svelte";
	import RenderPost from "$lib/components/blog/render-post.svelte";
	import Sidebar from "$lib/components/blog/sidebar.svelte";

	let { data } = $props();
	const post = $derived(data.post);
</script>

<svelte:head>
	<title>{post.title}</title>
	<meta name="description" content={post.description ?? ""} />
</svelte:head>

<div class="w-full">
	<PostHeader
		title={post.title}
		image={post.image}
		author={post.author}
		createdAt={String(post.createdAt)}
	/>

	<main class="mx-auto w-full max-w-7xl px-4 py-8 sm:px-6">
		<div class="flex flex-col gap-8 lg:flex-row lg:gap-12">
			<div class="flex-1">
				<RenderPost content={String(post.content ?? "")} />
			</div>
			<div class="lg:w-80">
				<Sidebar
					author={post.author}
					createdAt={String(post.createdAt)}
					content={String(post.content ?? "")}
				/>
			</div>
		</div>
	</main>
</div>

// app/blog/posts/[slug]/page.tsx
import { PostHeader } from "app/blog/components/post-header";
import { RenderPost } from "app/blog/components/render-post";
import { SideBar } from "app/blog/components/sidebar";
import dbConnect from 'lib/dbConnect';
import { notFound } from 'next/navigation';
import { getPostBySlug } from "src/utils/blog";
import { PUBLICPostViewType } from 'types/post';


export default async function PostPage({ params }: {
    params: {
        slug: string
    }
}) {
    await dbConnect()

    const { post, success }: {
        post: PUBLICPostViewType | null,
        message: string,
        success: boolean
    } = await getPostBySlug(params.slug)
    if (!post || success === false) {
        console.log("Post not found, Slug :", params.slug)
        notFound()
    }
    console.log(post)
    return (
        <div>
            <PostHeader {...JSON.parse(JSON.stringify(post))} />
            <div className="px-4 lg:px-8 pt-8 bg-white dark:bg-slate-800">
                <main className="w-full max-w-7xl mx-auto py-16 px-6 md:px-12 lg:px-24 flex justify-around items-start gap-4 flex-row">
                    <RenderPost post={JSON.parse(JSON.stringify(post))} />
                    <SideBar />
                </main>
            </div>
        </div>
    )
}
