// src/routes/dev-tools/+page.svelte
<script lang="ts">
	import { Input } from "$lib/components/ui/input";
	import { cn } from "$lib/utils";
	import LayoutGrid from "@lucide/svelte/icons/layout-grid";
	import Search from "@lucide/svelte/icons/search";
	import Sparkles from "@lucide/svelte/icons/sparkles";
	import Terminal from "@lucide/svelte/icons/terminal";
	import { devTools, devToolCategories } from "./tools";

	let query = $state("");
	let activeCategory = $state("All");

	const filteredTools = $derived(
		devTools.filter((tool) => {
			const matchesCategory = activeCategory === "All" || tool.category === activeCategory;
			const q = query.trim().toLowerCase();
			const matchesQuery =
				q === "" ||
				tool.title.toLowerCase().includes(q) ||
				tool.description.toLowerCase().includes(q) ||
				tool.tags.some((t) => t.toLowerCase().includes(q));
			return matchesCategory && matchesQuery;
		})
	);
</script>

<svelte:head>
	<title>Developer Tools — Nexonauts</title>
	<meta
		name="description"
		content="A collection of tools that I have made to make your developer life easier."
	/>
</svelte:head>

<section class="relative py-12 md:py-20">
	<div class="mx-auto max-w-3xl space-y-4 text-center">
		<div
			class="bg-muted/50 text-muted-foreground inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs"
		>
			<Sparkles class="size-3" />
			Browser-first dev utilities
		</div>
		<h1 class="text-4xl font-bold tracking-tight md:text-5xl">Developer Tools</h1>
		<p class="text-muted-foreground mx-auto max-w-2xl text-base md:text-lg">
			A curated set of fast, private, browser-based tools to streamline your day.
		</p>
	</div>

	<div class="mt-10 flex w-full flex-col items-center gap-4">
		<div class="relative w-full max-w-md">
			<div
				class="text-muted-foreground pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3"
			>
				<Search class="size-4" />
			</div>
			<Input
				type="search"
				placeholder="Search tools…"
				bind:value={query}
				class="h-10 rounded-full pl-10"
			/>
		</div>

		<div class="flex flex-wrap justify-center gap-2">
			{#each devToolCategories as category (category)}
				<button
					type="button"
					onclick={() => (activeCategory = category)}
					class={cn(
						"rounded-full border px-3 py-1 text-xs font-medium transition-all",
						activeCategory === category
							? "bg-foreground text-background border-transparent"
							: "border-border bg-muted/50 text-muted-foreground hover:text-foreground"
					)}
				>
					{category}
				</button>
			{/each}
		</div>
	</div>

	{#if filteredTools.length === 0}
		<div class="text-muted-foreground mt-16 flex flex-col items-center gap-2 text-sm">
			<LayoutGrid class="size-8 opacity-50" />
			<p>No tools match your filters.</p>
		</div>
	{:else}
		<div class="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">
			{#each filteredTools as tool (tool.slug)}
				<a
					href={`/dev-tools/${tool.slug}`}
					class="group bg-card hover:border-primary/30 flex flex-col gap-3 rounded-xl border p-5 transition-all hover:-translate-y-0.5 hover:shadow-md"
				>
					<div class="flex items-center justify-between">
						<div
							class="bg-muted group-hover:bg-primary/10 flex size-10 items-center justify-center rounded-lg transition-colors"
						>
							<Terminal class="text-muted-foreground group-hover:text-primary size-5" />
						</div>
						<span
							class="text-muted-foreground/70 rounded-full bg-muted px-2 py-0.5 text-[10px] uppercase tracking-wider"
						>
							{tool.category}
						</span>
					</div>
					<div class="space-y-1">
						<h3 class="font-semibold tracking-tight">{tool.title}</h3>
						<p class="text-muted-foreground text-sm leading-relaxed">{tool.description}</p>
					</div>
				</a>
			{/each}
		</div>
	{/if}
</section>

// app/dev-tools/page.tsx
"use client";

import {
    ToolCard
} from "./components/tool-card";

import { Input } from "@/components/ui/input";
import { FAQs } from "./faqs";
// import bgImage from "./hero.png";
import { useState } from "react";
import { allDevTools } from "./list";

import { Search } from 'lucide-react';

export default function Tools() {

    const [query, setQuery] = useState("");
    const [tools, setTools] = useState(allDevTools);

    const handleSearch = (query) => {
        console.log("Search for:", query);
        setTools(allDevTools.filter(tool => {
            return tool.title.toLowerCase().includes(query.toLowerCase()) || tool.description.toLowerCase().includes(query.toLowerCase()) || tool.category.toLowerCase().includes(query.toLowerCase()) 
        }))

    }



    return (
        <>
            <section id="hero" className="relative mb-10 flex flex-col items-center justify-center text-center bg-cover bg-center bg-no-repeat py-24 backdrop-blur-xl min-h-96"
            // style={{ backgroundImage: `url(${bgImage.src})` }}
            >
                <div aria-hidden="true" className="absolute inset-0 grid grid-cols-2 -space-x-52 opacity-40 dark:opacity-20">
                    <div className="blur-[106px] h-56 bg-gradient-to-br from-primary to-purple-400 dark:from-blue-700" />
                    <div className="blur-[106px] h-32 bg-gradient-to-r from-cyan-400 to-sky-300 dark:to-indigo-600" />
                </div>
                <div className="max-w-7xl mx-auto px-6 md:px-12 xl:px-6 relative" >
                    <div className=" text-center mx-auto">
                        <h1 className="text-gray-900 dark:text-white font-bold text-5xl md:text-6xl xl:text-7xl relative bg-gradient-to-r from-primary to-violet-200 bg-clip-text text-transparent dark:from-primaryLight dark:to-secondaryLight">Developer Tools</h1>
                        <p className="mt-8 text-gray-700 dark:text-gray-300">
                            A collection of tools that I have made to make your developer life easier.
                        </p>
                    </div>
                    <div className="flex space-x-2 mt-4 relative">
                        <span className="absolute left-2 top-0 bottom-0 flex items-center pl-3">
                        <Search  className="text-primary w-5 h-5 z-10" />
                        </span>
                        <Input placeholder="Search dev tools curated from open source projects ..." variant="glass"
                        aria-label="Search Tools" id="search-tools"
                        className=" px-5 py-4 text-base h-12  pl-10 w-full max-w-3xl mx-auto rounded-lg shadow" type="search"
                        value={query} onChange={(e) =>  {
                            setQuery(e.target.value)
                            handleSearch(e.target.value)
                        }} />
                    </div>
                </div>

            </section>
            <div className="w-full grow grid gap-4 grid-cols-1 md:grid-cols-2 lg:grid-cols-3 pt-5">
                {tools.map((tool, index) => {
                    return <ToolCard  {...tool} index={index} style={{ animationDelay: (0.1 * index) + "s" }} key={index} />
                })}
            </div>
            {tools.length === 0 && <p className="text-center text-lg font-semibold">No tools found</p>}
            <FAQs />

        </>
    )
}
