// src/routes/scout/browse/+page.svelte
<script lang="ts">
	import ToolCard from "$lib/components/scout/tool-card.svelte";
	import { Badge } from "$lib/components/ui/badge";
	import { Button } from "$lib/components/ui/button";
	import { Input } from "$lib/components/ui/input";
	import Grid2x2 from "@lucide/svelte/icons/grid-2x2";
	import List from "@lucide/svelte/icons/list";
	import Search from "@lucide/svelte/icons/search";
	import SearchX from "@lucide/svelte/icons/search-x";
	import Sparkles from "@lucide/svelte/icons/sparkles";
	import X from "@lucide/svelte/icons/x";

	let { data } = $props();
	const currentView = $derived(data.view === "list" ? "list" : "grid");

	const hasActiveFilters = $derived(
		Boolean(
			data.filter.category !== "all" ||
				data.filter.pricing_type !== "all" ||
				data.query ||
				data.offset
		)
	);

	function buildHref(next: Record<string, string | number>) {
		const params = new URLSearchParams();
		const entries: Record<string, string | number> = {
			query: data.query,
			page: data.page,
			offset: data.offset,
			view: data.view,
			category: data.filter.category,
			pricing_type: data.filter.pricing_type,
			...next
		};

		for (const [key, value] of Object.entries(entries)) {
			if (value === "" || value === "all" || value === 0) continue;
			params.set(key, String(value));
		}

		const query = params.toString();
		return query ? `/scout/browse?${query}` : "/scout/browse";
	}

	const paginationItems = $derived.by(() => {
		const start = Math.max(1, data.page - 2);
		const end = Math.min(data.totalPages, data.page + 2);
		return Array.from({ length: end - start + 1 }, (_, index) => start + index);
	});
</script>

<div class="min-h-screen bg-background">
	<div class="pointer-events-none fixed inset-0 z-0">
		<div
			class="absolute inset-0 bg-[linear-gradient(to_right,#80808008_1px,transparent_1px),linear-gradient(to_bottom,#80808008_1px,transparent_1px)] bg-[size:24px_24px]"
		></div>
		<div class="absolute top-20 right-0 h-[600px] w-[600px] rounded-full bg-primary/5 blur-[150px]"></div>
	</div>

	<div class="relative z-10 w-full border-b border-border/40 pt-20">
		<div class="mx-auto max-w-[1600px] px-4 py-10 sm:px-6">
			<div class="max-w-2xl">
				<div class="mb-3 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">
					<Sparkles class="h-3 w-3" />
					<span>Curated Tools</span>
				</div>
				<h1 class="mb-3 text-3xl font-bold tracking-tight md:text-4xl">{data.hero.title}</h1>
				<p class="text-base text-muted-foreground">{data.hero.description}</p>
			</div>
		</div>
	</div>

	<div class="relative z-10 mx-auto flex w-full max-w-[1600px] gap-8 px-4 py-8 sm:px-6">
		<aside class="hidden h-fit w-72 shrink-0 space-y-6 lg:block lg:sticky lg:top-24">
			<div class="rounded-xl border border-border/50 bg-card/50 p-4 backdrop-blur-sm">
				<h3 class="mb-4 text-sm font-semibold">Pricing</h3>
				<div class="flex flex-wrap gap-2">
					{#each data.pricingTypes as pricingType (pricingType)}
						<a href={buildHref({ pricing_type: pricingType, page: 1 })}>
							<Badge variant={data.filter.pricing_type === pricingType ? "default" : "outline"}>
								{pricingType}
							</Badge>
						</a>
					{/each}
				</div>
			</div>

			<div class="rounded-xl border border-border/50 bg-card/50 p-4 backdrop-blur-sm">
				<h3 class="mb-4 text-sm font-semibold">Categories</h3>
				<div class="flex flex-wrap gap-2">
					{#each data.categories as category (category.slug)}
						<a href={buildHref({ category: category.slug, page: 1 })}>
							<Badge variant={data.filter.category === category.slug ? "default" : "outline"}>
								{category.name}
							</Badge>
						</a>
					{/each}
				</div>
			</div>
		</aside>

		<main class="min-w-0 flex-1 space-y-6">
			<div class="sticky top-20 z-30 rounded-xl border border-border/50 bg-background/80 p-3 shadow-sm backdrop-blur-xl">
				<div class="flex flex-col gap-3 sm:flex-row sm:items-center">
					<form action="/scout/browse" method="GET" class="relative w-full sm:flex-1">
						<div class="pointer-events-none absolute inset-y-0 left-3 flex items-center">
							<Search class="h-4 w-4 text-muted-foreground" />
						</div>
						<Input
							name="query"
							value={data.query}
							placeholder="Search tools, categories, or tags"
							class="h-11 rounded-full border-border/50 bg-card/70 pr-4 pl-10 backdrop-blur-sm"
						/>
						<input type="hidden" name="category" value={data.filter.category} />
						<input type="hidden" name="pricing_type" value={data.filter.pricing_type} />
						<input type="hidden" name="view" value={data.view} />
					</form>

					<div class="flex items-center gap-2">
						<a href={buildHref({ view: "grid" })}>
							<Badge variant={data.view === "grid" ? "default" : "outline"} class="gap-1.5 px-3 py-2">
								<Grid2x2 class="h-3.5 w-3.5" />
								Grid
							</Badge>
						</a>
						<a href={buildHref({ view: "list" })}>
							<Badge variant={data.view === "list" ? "default" : "outline"} class="gap-1.5 px-3 py-2">
								<List class="h-3.5 w-3.5" />
								List
							</Badge>
						</a>
					</div>
				</div>
			</div>

			<div class="px-1 text-sm text-muted-foreground">
				{#if data.query}
					<span>
						<span class="font-semibold text-foreground">{data.totalResults}</span>
						results for "{data.query}"
					</span>
				{:else}
					<span>
						<span class="font-semibold text-foreground">{data.totalResults}</span>
						tools available
					</span>
				{/if}
			</div>

			{#if hasActiveFilters}
				<div class="flex flex-wrap items-center gap-2">
					<span class="text-xs font-medium text-muted-foreground">Active:</span>
					{#if data.filter.category !== "all"}
						<a href={buildHref({ category: "", page: 1 })} class="inline-flex">
							<Badge class="gap-1.5 bg-primary/10 text-primary">
								{data.filter.category}
								<X class="h-3 w-3" />
							</Badge>
						</a>
					{/if}
					{#if data.filter.pricing_type !== "all"}
						<a href={buildHref({ pricing_type: "", page: 1 })} class="inline-flex">
							<Badge class="gap-1.5 bg-primary/10 text-primary">
								{data.filter.pricing_type}
								<X class="h-3 w-3" />
							</Badge>
						</a>
					{/if}
					{#if data.query}
						<a href={buildHref({ query: "", page: 1 })} class="inline-flex">
							<Badge class="gap-1.5 bg-primary/10 text-primary">
								Search
								<X class="h-3 w-3" />
							</Badge>
						</a>
					{/if}
					<a href="/scout/browse" class="text-xs text-muted-foreground underline underline-offset-2">
						Clear all
					</a>
				</div>
			{/if}

			{#if data.tools.length === 0}
				<div class="flex justify-center py-20">
					<div class="rounded-2xl border border-dashed border-border/60 bg-card/20 px-8 py-16 text-center">
						<div class="mb-5 flex justify-center">
							<div class="flex h-16 w-16 items-center justify-center rounded-full bg-muted/50">
								<SearchX class="h-7 w-7 text-muted-foreground" />
							</div>
						</div>
						<h3 class="mb-2 text-lg font-semibold">No tools found</h3>
						<p class="mb-6 max-w-sm text-sm text-muted-foreground">
							Try adjusting your filters or search query.
						</p>
						<Button href="/scout/browse" variant="outline">Reset Filters</Button>
					</div>
				</div>
			{:else}
				<div
					class={currentView === "list"
						? "grid grid-cols-1 gap-4"
						: "grid grid-cols-1 gap-6 sm:grid-cols-2 xl:grid-cols-3"}
				>
					{#each data.tools as tool (tool._id)}
						<ToolCard {tool} view={currentView} />
					{/each}
				</div>

				{#if data.totalPages > 1}
					<div class="flex flex-wrap items-center justify-center gap-2 border-t border-border/40 pt-8">
						<Button
							variant="outline"
							href={buildHref({ page: Math.max(1, data.page - 1) })}
							disabled={data.page <= 1}
						>
							Previous
						</Button>

						{#each paginationItems as pageNumber (pageNumber)}
							<a href={buildHref({ page: pageNumber })}>
								<Badge variant={pageNumber === data.page ? "default" : "outline"} class="px-3 py-2">
									{pageNumber}
								</Badge>
							</a>
						{/each}

						<Button
							variant="outline"
							href={buildHref({ page: Math.min(data.totalPages, data.page + 1) })}
							disabled={data.page >= data.totalPages}
						>
							Next
						</Button>
					</div>
				{/if}
			{/if}
		</main>
	</div>
</div>

// _legacy/app/scout/browse/page.tsx
import AdUnit from "@/components/common/adsense";
import { Badge } from "@/components/ui/badge";
import ConditionalRender from "@/components/utils/conditional-render";
import InfoArea from "@/components/utils/info-area";
import { cn } from "@/lib/utils";
import Navbar from "app/layouts/navbar-dynamic";
import { getTools } from "app/scout/lib/actions";
import {
  Hash,
  SearchX,
  Sparkles,
  Verified
} from "lucide-react";
import { Metadata } from "next";
import Link from "next/link";
import LazyImage from "src/components/image";
import { PublicToolPricingType, PublicToolTypeWithId } from "src/models/tool";

import { HERO_SECTION, METADATA } from "data/scout/browse";
import { SearchParams } from "nuqs/server";
import { Fragment } from "react";
import { getImages } from "src/lib/scout";
import { FilterSidebar, MobileFilterSheet, SearchBar, ViewToggle, ViewWrapper } from "./client-components";
import { loadSearchParams } from "./searchParams";

export const metadata: Metadata = METADATA;

type PageProps = {
  searchParams: Promise<SearchParams>
}

export default async function BrowsePage({ searchParams }: PageProps) {
  const {
    query,
    page: currentPage,
    offset,
    view: viewType,
    category,
    pricing_type
  } = await loadSearchParams(searchParams)

  const filter = {
    pricing_type: (pricing_type as PublicToolPricingType) || "all",
    category: category || "all",
  };

  const { tools, categories, pricing_types } = await getTools(
    query,
    currentPage,
    filter,
    offset
  );

  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Navbar />

      {/* Subtle Background */}
      <div className="fixed inset-0 z-0 pointer-events-none">
        <div className="absolute inset-0 bg-[linear-gradient(to_right,#80808008_1px,transparent_1px),linear-gradient(to_bottom,#80808008_1px,transparent_1px)] bg-[size:24px_24px]" />
        <div className="absolute top-20 right-0 w-[600px] h-[600px] bg-primary/5 blur-[150px] rounded-full" />
      </div>

      {/* Compact Header */}
      <div className="relative z-10 w-full border-b border-border/40 pt-20">
        <div className="max-w-[1600px] mx-auto px-4 sm:px-6 py-10">
          <div className="max-w-2xl">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 text-primary text-xs font-semibold mb-3 border border-primary/20">
              <Sparkles className="w-3 h-3" />
              <span>Curated Tools</span>
            </div>
            <h1 className="text-3xl md:text-4xl font-bold tracking-tight mb-3">
              {HERO_SECTION.title}
            </h1>
            <p className="text-base text-muted-foreground">
              {HERO_SECTION.description}
            </p>
          </div>
        </div>
      </div>

      {/* TOP LEADERBOARD AD */}
      <div className="relative z-10 w-full max-w-[1600px] mx-auto px-4 sm:px-6 mt-8">
        <div className="w-full min-h-[100px] rounded-xl border border-border/40 bg-card/30 backdrop-blur-sm flex items-center justify-center overflow-hidden relative">
          <div className="absolute inset-0 bg-[radial-gradient(#00000005_1px,transparent_1px)] [background-size:16px_16px]" />
          <div className="absolute top-2 left-4 text-[9px] font-bold text-muted-foreground uppercase tracking-widest">
            Sponsored
          </div>
          <div className="relative z-10">
            <AdUnit adSlot="display-horizontal" />
          </div>
        </div>
      </div>

      <div className="flex-1 w-full max-w-[1600px] mx-auto px-4 sm:px-6 py-8 relative z-10">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">

          {/* Streamlined Sidebar */}
          <aside className="hidden lg:block lg:col-span-3 space-y-6 sticky top-24 h-fit">
            
            {/* Filters Card */}
            <div className="rounded-xl border border-border/50 bg-card/50 backdrop-blur-sm p-4">
              <FilterSidebar
                categories={categories}
                pricing_types={pricing_types}
                currentFilter={filter}
              />
            </div>

            {/* SIDEBAR AD (160x600 or 300x250) */}
            <div className="w-full min-h-[600px] rounded-xl bg-card/40 backdrop-blur-sm border border-border/40 flex flex-col overflow-hidden">
              <div className="w-full py-2 bg-muted/50 border-b border-border/40 text-center">
                <span className="text-[9px] font-bold text-muted-foreground uppercase tracking-widest">
                  Sponsored
                </span>
              </div>
              <div className="flex-1 flex items-center justify-center p-4">
                <AdUnit adSlot="display-vertical" />
              </div>
            </div>

          </aside>

          {/* Main Content */}
          <main className="lg:col-span-9 space-y-6">

            {/* Toolbar */}
            <div className="sticky top-20 z-30 rounded-xl bg-background/80 backdrop-blur-xl border border-border/50 shadow-sm p-3">
              <div className="flex flex-col sm:flex-row gap-3 items-center">
                <div className="w-full sm:flex-1">
                  <SearchBar initialQuery={query} />
                </div>

                <div className="flex items-center gap-3 w-full sm:w-auto justify-end">
                  <div className="lg:hidden">
                    <MobileFilterSheet
                      categories={categories}
                      pricing_types={pricing_types}
                      currentFilter={filter}
                    />
                  </div>
                  <div className="h-6 w-px bg-border/50 hidden sm:block" />
                  <ViewToggle />
                </div>
              </div>
            </div>

            {/* Results Count */}
            <div className="px-1 text-sm text-muted-foreground">
              {query ? (
                <span>
                  <span className="font-semibold text-foreground">{tools.length}</span> results for &quot;{query}&quot;
                </span>
              ) : (
                <span>
                  <span className="font-semibold text-foreground">{tools.length}</span> tools available
                </span>
              )}
            </div>

            {/* Results Grid */}
            <div id="results" className="min-h-[50vh]">
              <ConditionalRender condition={tools.length > 0}>
                <ViewWrapper>
                  {tools.map((tool, index) => (
                    <Fragment key={tool._id}>
                      <ToolCard tool={tool} viewType={viewType} />

                      {/* IN-FEED AD every 6 items */}
                      {(index + 1) % 6 === 0 && index !== tools.length - 1 && (
                        <div className={cn(
                          "w-full rounded-xl border border-border/40 bg-card/30 backdrop-blur-sm overflow-hidden relative",
                          viewType === "list" ? "col-span-full" : "",
                          viewType === "masonry" ? "break-inside-avoid mb-6" : ""
                        )}>
                          <div className="absolute inset-0 bg-[radial-gradient(#00000008_1px,transparent_1px)] [background-size:20px_20px]" />
                          <div className="absolute top-3 left-1/2 -translate-x-1/2 px-3 py-1 rounded-full bg-muted/70 backdrop-blur-sm z-10">
                            <span className="text-[9px] font-bold text-muted-foreground uppercase tracking-widest">
                              Featured
                            </span>
                          </div>
                          <div className="relative min-h-[250px] flex items-center justify-center py-6">
                            <AdUnit adSlot="in_feed" />
                          </div>
                        </div>
                      )}
                    </Fragment>
                  ))}
                </ViewWrapper>
              </ConditionalRender>

              {/* BOTTOM MULTIPLEX AD */}
              <ConditionalRender condition={tools.length > 0}>
                <div className="mt-12 pt-8 border-t border-border/40">
                  <div className="flex items-center gap-3 mb-4">
                    <Sparkles className="w-4 h-4 text-primary" />
                    <span className="text-xs font-bold text-muted-foreground uppercase tracking-widest">
                      Discover More
                    </span>
                    <div className="h-px flex-1 bg-border/50" />
                  </div>
                  <div className="min-h-[280px] w-full bg-card/40 backdrop-blur-sm rounded-xl border border-border/40 flex items-center justify-center p-4 overflow-hidden relative">
                    <div className="absolute inset-0 bg-[radial-gradient(#00000005_1px,transparent_1px)] bg-size-[16px_16px]" />
                    <div className="relative z-10">
                      <AdUnit adSlot="multiplex_horizontal" />
                    </div>
                  </div>
                </div>
              </ConditionalRender>

              {/* Empty State */}
              <ConditionalRender condition={tools.length === 0}>
                <div className="py-20 flex justify-center">
                  <InfoArea
                    Icon={SearchX}
                    title="No tools found"
                    description="Try adjusting your filters or search query."
                    className="bg-muted/30 border-dashed"
                  />
                </div>
              </ConditionalRender>
            </div>

          </main>
        </div>
      </div>
    </div>
  );
}

// Tool Card Component
function ToolCard({ tool, viewType }: { tool: Partial<PublicToolTypeWithId>; viewType: string }) {
  const images = getImages(tool?.link || "");
  const isList = viewType === "list";

  return (
    <div className={cn(
      "h-full group",
      viewType === "masonry" && "mb-6 break-inside-avoid"
    )}>
      <Link
        href={`/scout/tools/${tool.slug}`}
        className={cn(
          "flex h-full rounded-xl border border-border/50 bg-card/50 backdrop-blur-sm overflow-hidden transition-all duration-300",
          "hover:border-primary/40 hover:shadow-lg hover:shadow-primary/5 hover:-translate-y-0.5",
          isList ? "flex-row items-stretch" : "flex-col"
        )}
      >
        {/* Image */}
        <div
          className={cn(
            "relative overflow-hidden bg-muted",
            isList 
              ? "w-40 md:w-56 shrink-0 border-r border-border/50" 
              : "aspect-video w-full border-b border-border/50"
          )}
        >
          <LazyImage
            className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105"
            width={isList ? 300 : 500}
            height={isList ? 300 : 300}
            src={images?.bannerURL || tool.coverImage || "/placeholder.png"}
            alt={tool.name || "Tool"}
          />

          {/* Verified Badge */}
          {tool.verified && (
            <div className="absolute top-2 right-2 bg-background/90 backdrop-blur-md rounded-full p-1.5 shadow-sm border border-border/50">
              <Verified className="w-3.5 h-3.5 text-emerald-500" />
            </div>
          )}
        </div>

        {/* Content */}
        <div className="flex flex-col flex-1 p-4">
          <div className="flex justify-between items-start gap-2 mb-2">
            <h3 className="font-semibold text-base text-foreground group-hover:text-primary transition-colors line-clamp-1">
              {tool.name}
            </h3>
            <Badge 
              variant="secondary" 
              className={cn(
                "shrink-0 text-[10px] uppercase font-bold tracking-wider px-2 py-0.5",
                tool.pricing_type === "free" 
                  ? "bg-emerald-500/10 text-emerald-600 border-emerald-500/20" 
                  : "bg-muted text-muted-foreground"
              )}
            >
              {tool.pricing_type}
            </Badge>
          </div>

          {/* Categories */}
          <div className="mt-auto pt-3 flex flex-wrap gap-1.5">
            {tool.categories?.slice(0, 3).map((category: any, idx: number) => (
              <span 
                key={idx} 
                className="inline-flex items-center gap-1 px-2 py-1 rounded-md bg-muted/50 text-xs text-muted-foreground border border-transparent group-hover:border-border/50 transition-colors"
              >
                <Hash className="w-3 h-3 opacity-50" />
                {category.name}
              </span>
            ))}
          </div>
        </div>
      </Link>
    </div>
  );
}
