// src/lib/components/blog/newsletter.svelte
<script lang="ts">
	import CalendarDays from "@lucide/svelte/icons/calendar-days";
	import Hand from "@lucide/svelte/icons/hand";
</script>

<div
	class="relative isolate overflow-hidden rounded-2xl bg-gray-900 py-16 sm:py-24 lg:py-32"
>
	<div class="mx-auto max-w-7xl px-6 lg:px-8">
		<div
			class="mx-auto grid max-w-2xl grid-cols-1 gap-x-8 gap-y-16 lg:max-w-none lg:grid-cols-2"
		>
			<div class="max-w-xl lg:max-w-lg">
				<h2 class="text-4xl font-semibold tracking-tight text-white">
					Subscribe to our newsletter
				</h2>
				<p class="mt-4 text-lg text-gray-300">
					Stay updated with the latest news, articles, and insights from our team. Join our
					community of readers and never miss an update!
				</p>
				<form class="mt-6 flex max-w-md gap-x-4" method="POST" action="/api/newsletter">
					<label for="newsletter-email" class="sr-only">Email address</label>
					<input
						id="newsletter-email"
						name="email"
						type="email"
						required
						placeholder="Enter your email"
						autocomplete="email"
						class="min-w-0 flex-auto rounded-md bg-white/5 px-3.5 py-2 text-base text-white outline outline-1 -outline-offset-1 outline-white/10 placeholder:text-gray-500 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-500 sm:text-sm/6"
					/>
					<button
						type="submit"
						class="flex-none rounded-md bg-indigo-500 px-3.5 py-2.5 text-sm font-semibold text-white shadow-xs hover:bg-indigo-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500"
					>
						Subscribe
					</button>
				</form>
			</div>

			<dl class="grid grid-cols-1 gap-x-8 gap-y-10 sm:grid-cols-2 lg:pt-2">
				<div class="flex flex-col items-start">
					<div class="rounded-md bg-white/5 p-2 ring-1 ring-white/10">
						<CalendarDays class="size-6 text-white" />
					</div>
					<dt class="mt-4 text-base font-semibold text-white">Weekly articles</dt>
					<dd class="mt-2 text-base/7 text-gray-400">
						Receive a curated selection of our latest articles and insights every week.
					</dd>
				</div>
				<div class="flex flex-col items-start">
					<div class="rounded-md bg-white/5 p-2 ring-1 ring-white/10">
						<Hand class="size-6 text-white" />
					</div>
					<dt class="mt-4 text-base font-semibold text-white">No spam</dt>
					<dd class="mt-2 text-base/7 text-gray-400">
						We value your privacy and will never share your email with third parties.
					</dd>
				</div>
			</dl>
		</div>
	</div>

	<div
		aria-hidden="true"
		class="absolute top-0 left-1/2 -z-10 -translate-x-1/2 blur-3xl xl:-top-6"
	>
		<div
			style:clip-path="polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)"
			class="aspect-1155/678 w-[1155px] bg-linear-to-tr from-[#ff80b5] to-[#9089fc] opacity-30"
		></div>
	</div>
</div>

// _legacy/src_components/newsletter.tsx
import { Button } from "@/components/ui/button";
import toast from "react-hot-toast";

export default function Newsletter() {
  return (
    <section className="bg-indigo-300 dark:bg-gray-900">
      <div className="py-8 px-4 mx-auto max-w-(--breakpoint-xl) lg:py-16 lg:px-6">
        <div className="mx-auto max-w-(--breakpoint-md) sm:text-center">
          <h2 className="mb-4 text-3xl tracking-tight font-extrabold text-gray-900 sm:text-4xl dark:text-white">
            Sign up for our newsletter
          </h2>
          <p className="mx-auto mb-8 max-w-2xl font-light text-gray-600 md:mb-12 sm:text-xl dark:text-gray-400">
            Stay up to date with the roadmap progress, announcements and
            exclusive discounts feel free to sign up with your email.
          </p>
          <form
            onSubmit={(e) => {
              e.preventDefault();
              console.log(e.target);
              toast.success("Will be implemented soon");
            }}
          >
            <div className="items-center mx-auto mb-3 space-y-4 max-w-(--breakpoint-sm) sm:flex sm:space-y-0">
              <div className="relative w-full">
                <label
                  htmlFor="email"
                  className="hidden mb-2 text-sm font-medium text-gray-900 dark:text-gray-300"
                >
                  Email address
                </label>
                <div className="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
                  <svg
                    className="w-5 h-5 text-gray-500 dark:text-gray-400"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path d="M2.003 5.884L10 9.882l7.997-3.998A2 2 0 0016 4H4a2 2 0 00-1.997 1.884z" />
                    <path d="M18 8.118l-8 4-8-4V14a2 2 0 002 2h12a2 2 0 002-2V8.118z" />
                  </svg>
                </div>
                <input
                  className="block p-3 pl-10 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 sm:rounded-none sm:rounded-l-lg focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"
                  placeholder="Enter your email"
                  type="email"
                  id="email"
                  name="email"
                  required
                />
              </div>
              <div>
                <Button
                  type="submit"
                  className="rounded-l-none text-md  px-8 h-11"
                >
                  Subscribe
                </Button>
              </div>
            </div>
            <div className="mx-auto max-w-(--breakpoint-sm) text-sm text-center text-slate-100 newsletter-form-footer dark:text-gray-300">
              We care about the protection of your data.{" "}
              <a
                href="#"
                className="font-medium text-indigo-600 dark:text-primary-500 hover:underline"
              >
                Read our Privacy Policy
              </a>
              .
            </div>
          </form>
        </div>
      </div>
    </section>
  );
}
