// src/lib/components/common/without-session.svelte
<script lang="ts">
import ArrowRight from "@lucide/svelte/icons/arrow-right";
import { page } from "$app/state";
import { env } from "$env/dynamic/public";
import { Button } from "$lib/components/ui/button";

const redirect = $derived(encodeURIComponent((env.PUBLIC_WEBSITE_URL ?? "") + page.url.pathname));
</script>

<div
	class="bg-primary/10 relative flex h-full min-h-screen w-full flex-col items-center justify-center overflow-hidden p-4"
>
	<div class="m-auto">
		<div
			class="mt-10 flex aspect-square items-center justify-center rounded-xl bg-gray-100 p-2 drop-shadow-lg dark:bg-gray-800"
		>
			<img
				src="/logo-square.png"
				alt="Nexonauts"
				class="h-28 w-28 dark:invert"
				draggable="false"
			/>
		</div>
		<p class="mt-5 text-center text-lg text-gray-600 dark:text-gray-400">You are not logged in</p>

		<Button size="lg" class="mt-5 w-full" href={`/auth/sign-in?redirect=${redirect}`}>
			Login to continue
			<ArrowRight class="ml-2 h-4 w-4" />
		</Button>
	</div>
</div>

// app/layouts/without-session.tsx
'use client';
import { Button } from '@/components/ui/button';
import { ArrowRight } from 'lucide-react';
import Image from 'next/image';
import Link from 'next/link';
import { usePathname } from 'next/navigation';

export default function Page403() {
  const pathname = usePathname() as string;
  const redirect = encodeURIComponent(
    process.env.NEXT_PUBLIC_WEBSITE_URL + pathname
  );

  return (
    <div className="min-h-screen h-full w-full relative overflow-hidden bg-primary/10 flex flex-col justify-center items-center p-4">
      {/* <h2 className="text-5xl font-bold text-slate-900 dark:text-gray-100 text-center">

            </h2> */}
      <div className="m-auto">
        <div className="flex items-center justify-center mt-10 bg-gray-100 dark:bg-gray-800 rounded-xl aspect-square p-2  filter drop-shadow-lg">
          <Image
            src="/logo-square.png"
            height={512}
            width={512}
            alt="Nexonauts"
            className="w-28 h-28 dark:invert"
            draggable={false}
          />
        </div>
        <p className="text-lg  text-gray-600 dark:text-gray-400 mt-5 text-center">
          You are not logged in
        </p>

        <Button
          size="lg"
          width="sm"
          className="mt-5"
          variant="gradient_blue"
          asChild
        >
          <Link href={`/login?redirect=${redirect}`}>
            Login to continue
            <ArrowRight />
          </Link>
        </Button>
      </div>
    </div>
  );
}
