// src/routes/profiles/[username]/+page.svelte
<script lang="ts">
	import { enhance } from "$app/forms";
	import * as Avatar from "$lib/components/ui/avatar";
	import { Button } from "$lib/components/ui/button";
	import { Skeleton } from "$lib/components/ui/skeleton";
	import Loader2 from "@lucide/svelte/icons/loader-2";
	import Share2 from "@lucide/svelte/icons/share-2";
	import UserCheck from "@lucide/svelte/icons/user-check";
	import UserPlus from "@lucide/svelte/icons/user-plus";
	import { toast } from "svelte-sonner";

	let { data } = $props();
	const developer = $derived(data.developer);

	let following = $state(false);
	let followLoading = $state(false);

	$effect(() => {
		following = Boolean(data.isFollowing);
	});

	const initials = $derived(
		((developer.username ?? "??").slice(0, 2) || "??").toUpperCase()
	);

	async function copyShare() {
		try {
			const url = `${location.origin}/profiles/${developer.username}`;
			if (navigator.share) {
				await navigator.share({ title: developer.user?.name ?? developer.username, url });
			} else {
				await navigator.clipboard.writeText(url);
				toast.success("Profile link copied");
			}
		} catch {
			/* user dismissed share sheet */
		}
	}
</script>

<svelte:head>
	<title>{developer.user?.name ?? developer.username} — Nexonauts</title>
	<meta name="description" content={developer.bio ?? `Profile of @${developer.username}`} />
</svelte:head>

<div
	id="basic_info"
	class="mb-8 flex w-full flex-col items-start justify-center space-x-6 space-y-2 px-4 py-8 lg:flex-row"
>
	<Avatar.Root class="h-40 w-40 shadow-lg">
		<Avatar.Image
			src={developer.user?.image ?? developer.user?.profilePicture}
			alt={developer.username}
		/>
		<Avatar.Fallback class="h-40 w-40 text-xl uppercase">{initials}</Avatar.Fallback>
	</Avatar.Root>

	<div class="flex flex-col items-start justify-center space-y-2">
		<h1 class="text-4xl font-bold">{developer.user?.name ?? developer.username}</h1>
		<h3 class="text-gray-500 dark:text-slate-400">@{developer.username}</h3>

		<div class="text-muted-foreground flex gap-4 text-sm">
			<span>
				<strong class="text-foreground">{developer.followers?.length ?? 0}</strong> Followers
			</span>
			<span>
				<strong class="text-foreground">{developer.following?.length ?? 0}</strong> Following
			</span>
		</div>

		<p class="max-w-xl font-medium text-slate-500">{developer.bio ?? ""}</p>

		{#if developer.socials?.length}
			<div class="flex flex-wrap gap-2">
				{#each developer.socials as social (social.platform ?? social.url)}
					<a
						href={social.url}
						target="_blank"
						rel="noopener noreferrer"
						class="bg-muted hover:bg-muted/80 text-muted-foreground rounded-md px-3 py-1 text-xs transition-colors"
					>
						{social.platform ?? social.label ?? "Link"}
					</a>
				{/each}
			</div>
		{/if}

		<div class="flex w-full flex-row items-center justify-start space-x-2">
			{#if data.isOwner}
				<Button variant="outline" href="/dashboard/settings/profile">Edit profile</Button>
			{:else}
				<form
					method="POST"
					action="?/follow"
					use:enhance={() => {
						followLoading = true;
						return async ({ result, update }) => {
							if (result.type === "success") {
								following = !following;
								toast.success(following ? "Following" : "Unfollowed");
							} else if (result.type === "failure") {
								const msg = (result.data as { message?: string } | undefined)?.message;
								toast.error(msg ?? "Could not update follow state");
							}
							await update({ reset: false });
							followLoading = false;
						};
					}}
				>
					<Button type="submit" disabled={followLoading} class="gap-2 rounded-full">
						{#if followLoading}
							<Loader2 class="h-4 w-4 animate-spin" />
						{:else if following}
							<UserCheck class="h-4 w-4" />
						{:else}
							<UserPlus class="h-4 w-4" />
						{/if}
						{following ? "Following" : "Follow"}
					</Button>
				</form>
			{/if}

			<Button variant="outline" class="gap-2 rounded-full" onclick={copyShare}>
				<Share2 class="h-4 w-4" />
				Share
			</Button>
		</div>
	</div>
</div>

<div id="showcase" class="relative w-full space-y-2 px-4 py-8">
	<h2 class="text-2xl font-bold">Showcase</h2>
	<div class="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
		{#each Array(6) as _, i (i)}
			<Skeleton class="h-48 w-full rounded-lg" />
		{/each}
	</div>
</div>

// app/profiles/[username]/page.tsx
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Skeleton } from "@/components/ui/skeleton";
import { notFound } from "next/navigation";
import { getSession } from "~/auth/server";

import { followUnFollowProfile, getProfile } from "./actions";
import { FollowButton } from "./components/follow-btn";
import FollowerFollow from "./components/follower-follow";
import { ShareProfile } from "./components/share";
import SocialLinks from "./components/social-links";

import { Metadata } from "next";
import { Session } from "src/auth";

export async function generateMetadata(props: {
  params: Promise<{ username: string }>;
}): Promise<Metadata> {
  const params = await props.params;
  const meta = await getProfile(params.username);

  if (!meta) return notFound();

  return {
    title: `${meta.user.name}'s profile on ${process.env.NEXT_PUBLIC_WEBSITE_NAME}`,
    description: meta.bio,
    openGraph: {
      type: "profile",
      username: meta.username,
      title: `${meta.user.name}'s profile on ${process.env.NEXT_PUBLIC_WEBSITE_NAME}`,
      siteName: process.env.NEXT_PUBLIC_WEBSITE_NAME,
      url: `${process.env.NEXT_PUBLIC_WEBSITE_URL}/devs/${meta.username}`,
      images: [{ url: meta.profilePicture, alt: meta.name }],
    },
  };
}

export default async function DeveloperPage(props: {
  params: Promise<{ username: string }>;
}) {
  const params = await props.params;
  const developer = await getProfile(params.username);

  if (!developer) return notFound();
  const session = (await getSession()) as Session | null;

  const isOwner = session?.user?.username === developer.username;
  const isFollowing =
    developer.followers.includes(session?.user?.profile) || false;

  console.log(developer);

  return (
    <>
      <div
        id="basic_info"
        className="w-full px-4 py-8 space-y-2 flex flex-col lg:flex-row items-start justify-center space-x-6 mb-8"
      >
        <Avatar className="w-40 h-40 shadow-lg">
          <AvatarImage
            src={developer.user.image}
            alt={developer.username}
            width={320}
            height={320}
            className="w-40 h-40"
          />
          <AvatarFallback className="w-40 h-40 uppercase text-xl">
            {developer.username[0] + developer.username[1]}
          </AvatarFallback>
        </Avatar>
        <div className="flex flex-col items-start justify-center space-y-2">
          <h1 className="text-4xl font-bold">{developer.user.name}</h1>
          <h3 className="text-gray-500 dark:text-slate-400">
            @{developer.username}
          </h3>
          {/* <div className="flex flex-row items-center justify-start space-x-2 text-xs">
                        <span className="text-gray-500">Joined on </span><span className="text-slate-600 font-semibold">{developer.createdAt.toLocaleDateString("en-US", {year: "numeric",month: "short",day: "numeric"})}</span>
                    </div> */}
          <FollowerFollow
            developer={developer}
            followUnfollowUser={followUnFollowProfile}
            isFollowing={isFollowing}
          />
          <p className="text-slate-500 font-medium max-w-xl">{developer.bio}</p>
          <SocialLinks socials={developer.socials} />
          <div className="flex flex-row items-center justify-start space-x-2 w-full">
            <FollowButton
              isFollowing={isFollowing}
              followUser={followUnFollowProfile.bind(null, developer.username)}
            />
            <ShareProfile
              profile={{
                username: developer.username,
                name: developer.user.name,
                profilePicture: developer.user.image,
                bio: developer.bio,
              }}
            />
          </div>
        </div>
      </div>

      <div id="showcase" className="w-full px-4 py-8 space-y-2 relative">
        <h1 className="text-2xl font-bold">Showcase</h1>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          <Skeleton className="w-full h-48  rounded-lg" />
          <Skeleton className="w-full h-48  rounded-lg" />
          <Skeleton className="w-full h-48  rounded-lg" />
          <Skeleton className="w-full h-48  rounded-lg" />
          <Skeleton className="w-full h-48  rounded-lg" />
          <Skeleton className="w-full h-48  rounded-lg" />
        </div>
      </div>
    </>
  );
}
