// src/lib/components/application/stats-card.svelte
<script lang="ts">
	import { cn } from "$lib/utils";
	import type { Snippet } from "svelte";

	type Props = {
		title: string;
		icon?: Snippet;
		children: Snippet;
		class?: string;
	};

	let { title, icon, children, class: className }: Props = $props();
</script>

<div
	class={cn(
		"bg-card border-border/60 flex flex-col gap-2 rounded-2xl border p-5 shadow-sm",
		className
	)}
>
	<div class="text-muted-foreground flex items-center text-sm font-medium">
		{#if icon}{@render icon()}{/if}
		{title}
	</div>
	{@render children()}
</div>

// @/components/application/stats-card.tsx
import { CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { cn } from "@/lib/utils";
import { MagicCard } from "../animation/magic-card";

export type StatsCardProps = {
  title: string;
  children: React.ReactNode;
  Icon?: React.ReactNode;
  className?: string;
};

export function StatsCard({
  title,
  children,
  Icon,
  className,
}: StatsCardProps) {
  return (
    <MagicCard
      layerClassName="bg-card"
      className={cn("hover:-translate-y-2.5 hover:shadow duration-500 rounded-lg shadow", className)}
    >

      <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2 @2xl:p-4">
        <CardTitle className="text-sm font-medium">{title}</CardTitle>
        {Icon}
      </CardHeader>
      <CardContent className="space-y-2 @2xl:p-4 @2xl:pt-0">
        {children}
      </CardContent>
    </MagicCard>
  );
}
