// src/routes/scout/+page.svelte
<script lang="ts">
	import ToolCard from "$lib/components/scout/tool-card.svelte";
	import { Badge } from "$lib/components/ui/badge";
	import { Button } from "$lib/components/ui/button";
	import * as Tabs from "$lib/components/ui/tabs";
	import { formatNumber } from "src/utils/formaters";
	import ArrowRight from "@lucide/svelte/icons/arrow-right";
	import ArrowUpDown from "@lucide/svelte/icons/arrow-up-down";
	import FolderOpen from "@lucide/svelte/icons/folder-open";
	import MonitorSmartphone from "@lucide/svelte/icons/monitor-smartphone";
	import ScanSearch from "@lucide/svelte/icons/scan-search";
	import Search from "@lucide/svelte/icons/search";
	import Sparkles from "@lucide/svelte/icons/sparkles";
	import Star from "@lucide/svelte/icons/star";
	import Zap from "@lucide/svelte/icons/zap";

	let { data } = $props();

	const features = [
		{
			name: "Effortless Search",
			description:
				"Powerful semantic search makes locating the perfect solution for your specific stack instant.",
			icon: Search
		},
		{
			name: "Curated Quality",
			description:
				"We manually verify every tool to ensure you only see best-in-class solutions, no vaporware.",
			icon: Star
		},
		{
			name: "Always Fresh",
			description:
				"Our database is updated daily with the latest AI breakthroughs and version updates.",
			icon: Zap
		},
		{
			name: "Developer Focused",
			description:
				"Filter by API availability, open-source license, and pricing models instantly.",
			icon: MonitorSmartphone
		},
		{
			name: "Smart Categories",
			description:
				"Navigate through specialized clusters like code assistants, workflow automation, and design tooling.",
			icon: FolderOpen
		},
		{
			name: "Community Ranked",
			description:
				"See what's trending based on real developer usage and popularity metrics.",
			icon: ArrowUpDown
		}
	];

	let activeCategory = $state("");
	$effect(() => {
		if (!activeCategory && data.categories[0]?.slug) {
			activeCategory = data.categories[0].slug;
		}
	});

	const activeGroup = $derived(
		data.categories.find((category) => category.slug === activeCategory) ?? data.categories[0]
	);
</script>

<div class="min-h-screen">
	<header class="relative overflow-hidden">
		<div class="relative mx-auto flex max-w-7xl flex-col items-center px-6 pt-32 pb-20 text-center lg:pt-48 lg:pb-32">
			<div class="mb-8 inline-flex items-center rounded-full border border-primary/20 bg-primary/10 px-3 py-1 text-sm font-medium text-primary backdrop-blur-sm">
				<Sparkles class="mr-2 h-3.5 w-3.5" />
				<span class="flex items-center gap-1">
					Database updated:
					<span class="font-bold">{new Date().toLocaleDateString()}</span>
				</span>
			</div>

			<h1 class="mb-6 text-5xl font-extrabold tracking-tight text-transparent bg-clip-text bg-gradient-to-b from-foreground to-foreground/60 md:text-7xl">
				The Knowledge Base for
				<br class="hidden md:block" />
				<span class="bg-linear-to-l from-indigo-400 from-10% via-sky-400 via-30% to-emerald-300 to-90% bg-clip-text text-transparent">
					AI & Dev Tools
				</span>
			</h1>

			<p class="mb-10 max-w-2xl text-xl leading-relaxed text-muted-foreground">
				Nexo Scout is the search engine for builders. Discover over
				<span class="font-semibold text-foreground">{formatNumber(data.totalTools)}+</span>
				curated tools, resources, and services to streamline your next project.
			</p>

			<div class="mb-20 flex w-full flex-col items-center justify-center gap-4 sm:flex-row">
				<Button size="lg" class="h-12 rounded-full px-8 text-base shadow-lg shadow-primary/20" href="/scout/browse">
					<ScanSearch class="mr-2 h-5 w-5" />
					Start Exploring
				</Button>
				<Button
					size="lg"
					variant="outline"
					class="h-12 rounded-full bg-background/50 px-8 text-base backdrop-blur-md"
					href="/dashboard/tools"
				>
					<Zap class="mr-2 h-5 w-5" />
					Submit a Tool
				</Button>
			</div>
		</div>
	</header>

	<section class="relative z-10 border-y border-border/50 bg-muted/20 px-6 py-24">
		<div class="mx-auto max-w-7xl">
			<div class="mb-12 flex flex-col gap-6 md:flex-row md:items-end md:justify-between">
				<div>
					<h2 class="mb-2 text-3xl font-bold tracking-tight">Trending Collections</h2>
					<p class="text-muted-foreground">Most searched categories this week.</p>
				</div>
				<a href="/scout/browse" class="flex items-center gap-1 font-medium text-primary hover:underline">
					View all tools
					<ArrowRight class="h-4 w-4" />
				</a>
			</div>

			{#if data.categories.length > 0}
				<Tabs.Root bind:value={activeCategory} class="w-full">
					<div class="mb-4 overflow-x-auto pb-4 scrollbar-hide">
						<Tabs.List class="inline-flex h-12 w-auto items-center justify-start rounded-full border border-border/50 bg-background p-1 text-muted-foreground">
							{#each data.categories as category (category.slug)}
								<Tabs.Trigger
									value={category.slug}
									class="rounded-full px-6 py-2 text-sm font-medium transition-all data-[state=active]:bg-primary data-[state=active]:text-primary-foreground data-[state=active]:shadow-sm"
								>
									{category.name}
								</Tabs.Trigger>
							{/each}
						</Tabs.List>
					</div>

					{#each data.categories as category (category.slug)}
						<Tabs.Content value={category.slug} class="mt-0">
							<div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
								{#each category.tools as tool (tool._id)}
									<ToolCard {tool} />
								{/each}
							</div>
						</Tabs.Content>
					{/each}
				</Tabs.Root>
			{:else}
				<div class="rounded-2xl border border-dashed border-border/60 bg-card/20 py-16 text-center">
					<p class="text-sm text-muted-foreground">Scout categories will appear here once tools are published.</p>
				</div>
			{/if}

			{#if activeGroup}
				<div class="mt-8 flex justify-center">
					<a href={`/scout/browse?category=${activeGroup.slug}`}>
						<Badge class="rounded-full px-4 py-1.5 text-sm">Browse all {activeGroup.name}</Badge>
					</a>
				</div>
			{/if}
		</div>
	</section>

	<section class="relative overflow-hidden px-6 py-24">
		<div class="pointer-events-none absolute top-[20%] left-[10%] h-[400px] w-[400px] rounded-full bg-primary/5 blur-[120px] mix-blend-screen"></div>

		<div class="mx-auto max-w-7xl">
			<div class="mx-auto mb-16 max-w-3xl text-center">
				<h2 class="mb-3 text-sm font-semibold tracking-widest text-primary uppercase">
					Why Nexo Scout?
				</h2>
				<p class="mb-6 text-3xl font-bold tracking-tight md:text-4xl">
					Built for the modern creator economy
				</p>
				<p class="text-lg text-muted-foreground">
					We stripped away the noise. No ads, no fluff, just the tools you need to build faster and better.
				</p>
			</div>

			<div class="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
				{#each features as feature (feature.name)}
					{@const Icon = feature.icon}
					<div class="group relative rounded-3xl border border-border/50 bg-card/30 p-8 backdrop-blur-sm transition-colors hover:border-primary/20 hover:bg-card/60">
						<div class="absolute top-8 right-8 text-primary/10 transition-colors group-hover:text-primary/20">
							<Icon class="h-24 w-24 rotate-12" />
						</div>

						<div class="relative z-10">
							<div class="mb-6 flex h-12 w-12 items-center justify-center rounded-2xl bg-primary/10 text-primary transition-transform duration-300 group-hover:scale-110">
								<Icon class="h-6 w-6" />
							</div>
							<h3 class="mb-3 text-xl font-bold text-foreground">{feature.name}</h3>
							<p class="leading-relaxed text-muted-foreground">{feature.description}</p>
						</div>
					</div>
				{/each}
			</div>
		</div>
	</section>
</div>

// _legacy/app/scout/page.tsx
import { NumberTicker } from "@/components/animation/number-ticker";
import NavbarGlobal from "@/components/common/navbar";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { AuthButtonLink, ButtonLink } from "@/components/utils/link";
import {
  ArrowRight,
  ArrowUpDown,
  FolderOpen,
  MonitorSmartphone,
  ScanSearch,
  Search,
  Sparkles,
  Star,
  Zap
} from "lucide-react";
import { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { cache, Suspense } from "react";
import dbConnect from "src/lib/db";
import PublicTool, { PublicToolTypeWithId } from "src/models/tool";
;

export const metadata: Metadata = {
  title: "Nexo Scout - The AI Tool Directory",
  description:
    "Discover the best AI tools, services, and resources to supercharge your workflow.",
};

const features = [
  {
    name: "Effortless Search",
    description:
      "Powerful semantic search makes locating the perfect solution for your specific stack instant.",
    icon: Search,
  },
  {
    name: "Curated Quality",
    description:
      "We manually verify every tool to ensure you only see best-in-class solutions, no vaporware.",
    icon: Star,
  },
  {
    name: "Always Fresh",
    description:
      "Our database is updated daily with the latest AI breakthroughs and version updates.",
    icon: Zap,
  },
  {
    name: "Developer Focused",
    description:
      "Filter by API availability, open-source license, and pricing models instantly.",
    icon: MonitorSmartphone,
  },
  {
    name: "Smart Categories",
    description:
      "Navigate through specialized clusters like 'Generative Video', 'Code Assistants', and 'LLMOps'.",
    icon: FolderOpen,
  },
  {
    name: "Community Ranked",
    description:
      "See what's trending based on real developer usage and popularity metrics.",
    icon: ArrowUpDown,
  },
];

// --- Data Fetching (Preserved) ---
async function getCategories() {
  const categories = await PublicTool.aggregate([
    { $unwind: "$categories" },
    {
      $group: {
        _id: "$categories.slug",
        name: { $first: "$categories.name" },
        slug: { $first: "$categories.slug" },
      },
    },
    { $project: { _id: 0, name: 1, slug: 1 } },
  ]).limit(5);
  const slugs = categories.map((category) => category.slug);

  const categorized_tools = await PublicTool.aggregate([
    { $unwind: "$categories" },
    {
      $group: {
        _id: "$categories.slug",
        name: { $first: "$categories.name" },
        slug: { $first: "$categories.slug" },
        tools: { $push: "$$ROOT" },
      },
    },
    {
      $project: { _id: 0, name: 1, slug: 1, tools: { $slice: ["$tools", 6] } },
    },
    { $match: { slug: { $in: slugs } } },
    { $sort: { name: 1 } },
  ]);
  return Promise.resolve(JSON.parse(JSON.stringify(categorized_tools)));
}

const getCategoriesPromise = cache(getCategories);
type CategorizedToolType = {
  name: string;
  slug: string;
  tools: PublicToolTypeWithId[];
}

export default async function Page() {
  await dbConnect();

  const noOfTools = await PublicTool.countDocuments({
    $or: [{ status: "published" }, { status: "approved" }],
  });

  const categorized_tools = (await getCategoriesPromise()) as CategorizedToolType[];

  return (
    <main className="min-h-screen ">
      <header className="relative overflow-hidden">
        <NavbarGlobal />

        {/* --- Hero Content --- */}
        <div className="relative pt-32 pb-20 lg:pt-48 lg:pb-32 px-6 max-w-7xl mx-auto flex flex-col items-center text-center">

          <div className="inline-flex items-center rounded-full border border-primary/20 bg-primary/10 px-3 py-1 text-sm font-medium text-primary mb-8 backdrop-blur-sm">
            <Sparkles className="mr-2 h-3.5 w-3.5" />
            <span className="flex items-center gap-1">
              Database updated: <span className="font-bold">{new Date().toLocaleDateString()}</span>
            </span>
          </div>

          <h1 className="text-5xl md:text-7xl font-extrabold tracking-tight mb-6 bg-clip-text text-transparent bg-gradient-to-b from-foreground to-foreground/60">
            The Knowledge Base for <br className="hidden md:block" />
            <span className="bg-linear-to-l from-indigo-400 from-10% via-sky-400 via-30% to-emerald-300 to-90% bg-clip-text text-transparent">
              AI & Dev Tools
            </span>
          </h1>

          <p className="text-xl text-muted-foreground max-w-2xl mb-10 leading-relaxed">
            Nexo Scout is the search engine for builders. Discover over{" "}
            <span className="font-semibold text-foreground">
              <NumberTicker value={noOfTools} />+
            </span>{" "}
            curated tools, resources, and services to streamline your next project.
          </p>

          <div className="flex flex-col sm:flex-row gap-4 items-center w-full justify-center mb-20">
            <ButtonLink size="lg" className="h-12 px-8 text-base rounded-full shadow-lg shadow-primary/20" href="/scout/browse">
              <ScanSearch className="mr-2 h-5 w-5" />
              Start Exploring
            </ButtonLink>
            <AuthButtonLink size="lg" variant="outline" className="h-12 px-8 text-base rounded-full bg-background/50 backdrop-blur-md"
              href="/dashboard/tools/submit">
              <Zap className="mr-2 h-5 w-5" />
              Submit a Tool
            </AuthButtonLink>
          </div>


        </div>
      </header>

      {/* --- Popular Categories Tabs --- */}
      <section className="py-24 px-6 relative z-10 bg-muted/20 border-y border-border/50">
        <div className="max-w-7xl mx-auto">
          <div className="flex flex-col md:flex-row md:items-end justify-between mb-12 gap-6">
            <div>
              <h2 className="text-3xl font-bold tracking-tight mb-2">Trending Collections</h2>
              <p className="text-muted-foreground">Most searched categories this week.</p>
            </div>
            <Link href="/scout/categories" className="text-primary font-medium hover:underline flex items-center gap-1">
              View all categories <ArrowRight className="w-4 h-4" />
            </Link>
          </div>

          <Suspense
            fallback={
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                {[1, 2, 3, 4, 5, 6].map((i) => (
                  <Skeleton key={i} className="h-64 w-full rounded-2xl" />
                ))}
              </div>
            }
          >
            {categorized_tools.length > 0 && (
              <Tabs defaultValue={categorized_tools[0].slug} className="w-full">
                <div className="overflow-x-auto pb-4 mb-4 scrollbar-hide">
                  <TabsList className="inline-flex h-12 items-center justify-start rounded-full bg-background border border-border/50 p-1 text-muted-foreground w-auto">
                    {categorized_tools.map((category) => (
                      <TabsTrigger
                        key={category.slug}
                        value={category.slug}
                        className="rounded-full px-6 py-2 text-sm font-medium transition-all data-[state=active]:bg-primary data-[state=active]:text-primary-foreground data-[state=active]:shadow-sm"
                      >
                        {category.name}
                      </TabsTrigger>
                    ))}
                  </TabsList>
                </div>

                {categorized_tools.map((category) => (
                  <TabsContent value={category.slug} key={category.slug} className="mt-0">
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                      {category.tools.map((tool) => (
                        <Link
                          href={`/scout/tools/${tool.slug}`}
                          key={tool.slug}
                          className="group relative flex flex-col overflow-hidden rounded-2xl border border-border/50 bg-background/50 backdrop-blur-sm transition-all hover:shadow-xl hover:-translate-y-1 hover:border-primary/30"
                        >
                          {/* Image Container */}
                          <div className="aspect-[16/9] w-full overflow-hidden bg-muted relative">
                            {tool.coverImage ? (
                              <Image
                                src={tool.coverImage}
                                alt={tool.name}
                                fill
                                className="object-cover transition-transform duration-500 group-hover:scale-105"
                                sizes="(max-width: 768px) 100vw, 33vw"
                              />
                            ) : (
                              <div className="w-full h-full flex items-center justify-center text-muted-foreground bg-secondary/30">
                                <FolderOpen className="w-10 h-10 opacity-20" />
                              </div>
                            )}
                            {/* Overlay Gradient */}
                            <div className="absolute inset-0 bg-gradient-to-t from-background/90 to-transparent opacity-60" />
                          </div>

                          {/* Content */}
                          <div className="flex flex-1 flex-col p-5">
                            <div className="flex items-start justify-between gap-4 mb-3">
                              <h3 className="text-xl font-bold tracking-tight text-foreground line-clamp-1 group-hover:text-primary transition-colors">
                                {tool.name}
                              </h3>
                              <Badge variant="default_light" className="shrink-0 text-[10px] h-5">
                                {category.name}
                              </Badge>
                            </div>

                            <p className="text-muted-foreground text-sm leading-relaxed line-clamp-2 mb-4 flex-1">
                              {tool.description}
                            </p>

                            <div className="flex items-center text-xs font-medium text-primary opacity-0 -translate-x-2 transition-all duration-300 group-hover:opacity-100 group-hover:translate-x-0">
                              View Details <ArrowRight className="ml-1 w-3 h-3" />
                            </div>
                          </div>
                        </Link>
                      ))}
                    </div>
                  </TabsContent>
                ))}
              </Tabs>
            )}
          </Suspense>
        </div>
      </section>

      {/* --- Features Grid --- */}
      <section className="py-24 px-6 relative overflow-hidden">
        <div className="absolute top-[20%] left-[10%] w-[400px] h-[400px] bg-primary/5 blur-[120px] rounded-full mix-blend-screen pointer-events-none" />

        <div className="mx-auto max-w-7xl">
          <div className="text-center max-w-3xl mx-auto mb-16">
            <h2 className="text-sm font-semibold text-primary uppercase tracking-widest mb-3">
              Why Nexo Scout?
            </h2>
            <p className="text-3xl md:text-4xl font-bold tracking-tight mb-6">
              Built for the modern creator economy
            </p>
            <p className="text-lg text-muted-foreground">
              We stripped away the noise. No ads, no fluff—just the tools you need to build faster and better.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map((feature, index) => (
              <div
                key={index}
                className="relative p-8 rounded-3xl border border-border/50 bg-card/30 backdrop-blur-sm transition-colors hover:bg-card/60 hover:border-primary/20 group"
              >
                <div className="absolute top-8 right-8 text-primary/10 group-hover:text-primary/20 transition-colors">
                  <feature.icon className="w-24 h-24 rotate-12" />
                </div>

                <div className="relative z-10">
                  <div className="w-12 h-12 rounded-2xl bg-primary/10 flex items-center justify-center text-primary mb-6 group-hover:scale-110 transition-transform duration-300">
                    <feature.icon className="w-6 h-6" />
                  </div>
                  <h3 className="text-xl font-bold mb-3 text-foreground">
                    {feature.name}
                  </h3>
                  <p className="text-muted-foreground leading-relaxed">
                    {feature.description}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>
    </main>
  );
}
