// _legacy/app/auth/waitlist/page.tsx

import { Button } from "@/components/ui/button";
import { Metadata } from "next";
import Link from "next/link";
import dbConnect from "src/lib/db";
import User from "src/models/user";
import { generateSlug } from "src/utils/string";
import WaitListForm from "./form";

export const metadata: Metadata = {
  title: "Waitlist | NexoNauts",
  description: "Waitlist for an account on " + process.env.NEXT_PUBLIC_APP_NAME,
  keywords: "Waitlist, account, " + process.env.NEXT_PUBLIC_APP_NAME,
};

export const dynamic = "force-dynamic";

export default async function Page() {
  async function joinWaitList(data: {
    name: string;
    email: string;
  }): Promise<boolean> {
    "use server";

    await dbConnect();
    const existingUser = await User.findOne({
      email: data.email.toLowerCase(),
    });
    if (existingUser) {
      return Promise.reject("Email already exists");
    }
    const user = new User({
      name: data.name,
      email: data.email,
      username: generateSlug(8),
      role: "waitlist",
      account_type: "free",
      verificationToken: null,
      password: generateSlug(8),
      verified: false,
      providers: [],
      additional_info: {},
    });
    await user.save();

    return Promise.resolve(true);
  }

  return (
    <>
      <Button
        className="absolute right-4 top-4 md:right-8 md:top-8"
        variant="link"
        asChild
      >
        <Link href="/auth/sign-in">Login</Link>
      </Button>
      <header className="flex flex-col space-y-2 text-center">
        <h1 className="text-2xl font-semibold tracking-tight">
          Join {process.env.NEXT_PUBLIC_WEBSITE_NAME}
        </h1>
        <p className="text-sm text-muted-foreground">It{`'`}s quick and easy.</p>
      </header>
      <main className="flex flex-col items-center justify-center w-full p-4">
        <WaitListForm key={"form"} joinWaitList={joinWaitList} />
      </main>
    </>
  );
}

// src/routes/auth/waitlist/+page.svelte
<script lang="ts">
	import { enhance } from "$app/forms";
	import { env } from "$env/dynamic/public";
	import { Button, buttonVariants } from "$lib/components/ui/button";
	import { Input } from "$lib/components/ui/input";
	import { cn } from "$lib/utils";
	import Loader2 from "@lucide/svelte/icons/loader-2";
	import Mail from "@lucide/svelte/icons/mail";
	import UserRound from "@lucide/svelte/icons/user-round";
	import { toast } from "svelte-sonner";

	type ActionResultData = {
		success?: boolean;
		errors?: Record<string, string>;
		values?: { name?: string; email?: string };
	};

	let { form } = $props<{ form?: ActionResultData | null }>();

	let isLoading = $state(false);

	const websiteName = env.PUBLIC_WEBSITE_NAME ?? "Nexonauts";
</script>

<a
	href="/auth/sign-in"
	class={cn(
		buttonVariants({ variant: "link" }),
		"absolute top-4 right-4 md:top-8 md:right-8"
	)}
>
	Login
</a>

<header class="flex flex-col space-y-2 text-center">
	<h1 class="text-2xl font-semibold tracking-tight">Join {websiteName}</h1>
	<p class="text-muted-foreground text-sm">It's quick and easy.</p>
</header>

<main class="flex w-full flex-col items-center justify-center p-4">
	{#if form?.success}
		<div class="text-center">
			<p class="text-sm">
				Thanks — you're on the waitlist. We'll be in touch.
			</p>
		</div>
	{:else}
		<form
			method="POST"
			class="grid w-full gap-2 text-left"
			use:enhance={() => {
				isLoading = true;
				return async ({ result, update }) => {
					if (result.type === "success" && result.data?.success) {
						toast.success("Added to waitlist successfully");
					} else if (result.type === "failure") {
						const errs = (result.data as ActionResultData)?.errors;
						toast.error(errs?._ ?? errs?.email ?? "Could not add to waitlist");
					}
					await update();
					isLoading = false;
				};
			}}
		>
			<div>
				<div class="relative">
					<label for="wl-name" class="absolute top-1/2 left-4 z-10 -translate-y-1/2">
						<UserRound class="h-4 w-4" />
					</label>
					<Input
						id="wl-name"
						name="name"
						placeholder="Your Name"
						type="text"
						autocapitalize="words"
						autocomplete="name"
						autocorrect="off"
						disabled={isLoading}
						class="pl-10"
						value={form?.values?.name ?? ""}
					/>
				</div>
				{#if form?.errors?.name}
					<p class="text-destructive mt-1 text-xs">{form.errors.name}</p>
				{/if}
			</div>

			<div>
				<div class="relative">
					<label for="wl-email" class="absolute top-1/2 left-4 z-10 -translate-y-1/2">
						<Mail class="h-4 w-4" />
					</label>
					<Input
						id="wl-email"
						name="email"
						placeholder="name@example.com"
						type="email"
						autocapitalize="none"
						autocomplete="email"
						autocorrect="off"
						disabled={isLoading}
						class="pl-10"
						value={form?.values?.email ?? ""}
					/>
				</div>
				{#if form?.errors?.email}
					<p class="text-destructive mt-1 text-xs">{form.errors.email}</p>
				{/if}
			</div>

			<Button type="submit" disabled={isLoading} class="mt-2">
				{#if isLoading}
					<Loader2 class="animate-spin" />
				{/if}
				Join Waitlist
			</Button>
		</form>
	{/if}
</main>
