// src/lib/components/blog/post-card.svelte
<script lang="ts">
	import { Badge } from "$lib/components/ui/badge";
	import { cn } from "$lib/utils";
	import { decodeHTMLEntities } from "src/utils/string";
	import { format } from "date-fns";
	import ArrowUpRight from "@lucide/svelte/icons/arrow-up-right";
	import type { PostWithId } from "src/models/post";

	let {
		post,
		featured = false
	}: {
		post: PostWithId;
		featured?: boolean;
	} = $props();
</script>

<div
	class={cn(
		"group bg-card border-border/50 flex flex-col overflow-hidden rounded-xl border",
		"group-hover:border-primary/30 transition-all duration-300 group-hover:shadow-lg",
		featured ? "h-auto" : "h-full"
	)}
>
	<div class="relative aspect-video overflow-hidden">
		<img
			src={post.image || "/placeholder.svg"}
			alt={post.title}
			loading="lazy"
			class="absolute inset-0 h-full w-full object-cover transition-transform duration-500 group-hover:scale-105"
		/>
		<div
			class="absolute inset-0 bg-linear-to-t from-black/70 to-transparent opacity-80"
		></div>
	</div>

	<div class={cn("flex flex-1 flex-col gap-2 p-4", featured && "md:p-6")}>
		<h3
			class={cn(
				"text-foreground line-clamp-2 font-semibold",
				featured ? "text-xl md:text-2xl" : "text-lg"
			)}
		>
			{decodeHTMLEntities(post.title)}
		</h3>

		<div class="mb-3 flex flex-wrap gap-2">
			{#each post.labels.slice(0, 2) as tag (tag)}
				<Badge variant="secondary" class="font-normal">{tag}</Badge>
			{/each}
		</div>

		<p
			class={cn(
				"text-muted-foreground mb-4 flex-1 text-pretty",
				featured ? "text-base md:text-lg" : "text-sm"
			)}
		>
			{(post.description ?? "").substring(0, featured ? 500 : 120)}…
		</p>

		<div class="mt-auto flex items-center justify-between">
			<span class="text-muted-foreground text-sm">
				{format(new Date(post.createdAt), "MMM dd, yyyy")}
			</span>
			<ArrowUpRight
				class="text-muted-foreground group-hover:text-primary h-4 w-4 transition-transform duration-500 group-hover:-translate-y-1 group-hover:translate-x-1"
			/>
		</div>
	</div>
</div>

// app/blog/components/post-card.tsx
import { cn } from "@/lib/utils";
import Image from "next/image";
import { PostWithId } from "src/models/post";

import { Badge } from "@/components/ui/badge";
import { format } from "date-fns";
import { ArrowUpRight } from "lucide-react";
import { decodeHTMLEntities } from "src/utils/string";

export function PostCard({ post, featured = false }: {
  post: PostWithId;

  featured?: boolean
}) {
  return (
    <div
      className={cn(
        "flex flex-col rounded-xl overflow-hidden border border-border/50 bg-card group",
        "transition-all duration-300 group-hover:shadow-lg group-hover:border-primary/30",
        featured ? "h-auto" : "h-full",
      )}
    >
      <div className="relative aspect-video overflow-hidden">
        <Image
          fill
          src={post.image || "/placeholder.svg"}
          alt={post.title}
          className="object-cover transition-transform duration-500 group-hover:scale-105"
          sizes={featured ? "(max-width: 768px) 100vw, 50vw" : "(max-width: 768px) 100vw, 33vw"}
        />
        <div className="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent opacity-80" />

      </div>

      <div className={cn("p-4 flex-1 flex flex-col gap-2", featured ? "md:p-6" : "")}>
        <h3
          className={cn(
            "text-foreground font-semibold line-clamp-2",
            featured ? "text-xl md:text-2xl" : "text-lg"
          )}
        >
          {decodeHTMLEntities(post.title)}
        </h3>
        <div className="mb-3 flex flex-wrap gap-2">
          {post.labels.slice(0, 2).map((tag: string, index: number) => (
            <Badge
              key={index}
              variant="default_light"
              className="font-normal"
            >
              {tag}
            </Badge>
          ))}
        </div>

        <p className={cn(
          "text-muted-foreground mb-4 flex-1 text-pretty",
          featured ? "text-base md:text-lg" : "text-sm"
        )}>
          {post.description?.substring(0, featured ? 500 : 120) + "..."}
        </p>

        <div className="flex justify-between items-center mt-auto">
          <span className="text-sm text-muted-foreground">
            {format(new Date(post.createdAt), "MMM dd, yyyy")}
          </span>
          <ArrowUpRight className="w-4 h-4 text-muted-foreground transition-transform duration-500 group-hover:text-primary group-hover:translate-x-1 group-hover:-translate-y-1" />
        </div>
      </div>
    </div>
  );
}
